### ISSUE TITLE
identitytoolkit: panic when http.DefaultTransport is not a *http.Transport instance 

### ISSUE THREAD

**Issue by Azuka** [googleapis/google-cloud-go#10159]
**Client**

identitytoolkit

**Environment**

Google Cloud Functions 

**Go Environment**

$ go version: 1.22.3
$ go env

**Code**

e.g.
```go

http.DefaultTransport = otelhttp.NewTransport(&http.Transport{...})

identityClient, err := identitytoolkit.NewService(
		ctx,
		option.WithAPIKey(cfg.FirebaseAPIKey),
		option.WithGRPCDialOption(
			grpc.WithStatsHandler(otelgrpc.NewClientHandler()),
		),
	)
```

**Expected behavior**

Construction does not panic

**Actual behavior**

Panic

**Screenshots**

**Additional context**

Modifying the global http.DefaultTransport (e.g. to wrap an opentelemetry http roundtripper with new defaults) results in a panic when the client constructor tries to clone an expected `*http.Transport`. Is there a way to bypass the call when using grpc?

https://github.com/googleapis/google-cloud-go/blame/main/auth/httptransport/transport.go#L97

Also related: https://github.com/golang/go/issues/39299

**Comment by noahdietz** [comment]
This seems like a bug. Since `http.DefaultTransport` is a `RoundTripper` interface and mutable global variable, it is not safe to assume it is always going to concretely be `*http.Transport`. If it is not, I suppose we should just use the value directly instead of making a `Clone`. The `http.DefaultTransport` being overridden is pretty intentional by application authors, so it is best if we respect that and just reuse it direct.
