### ISSUE TITLE
/apiv1/v2/cloudbuildpb: include IncludeBuildLogs option

### ISSUE THREAD

**Issue by lucasfarias2** [googleapis/google-cloud-go#10383]
Greetings, 
I am developing a platform that wraps cloud build service to manage deployments and in this case I am facing some trouble to create the Build Trigger including the option to push build logs to GitHub automatically.

I am using **apiv1**/**v2** of **cloudbuildpb** as I need it's functionality, and I noticed it is currently not possible to specify to include build logs option, such as to GitHub.

This is the option in the UI:

<img width="304" alt="image" src="https://github.com/googleapis/google-cloud-go/assets/19575942/5173f1c0-cecf-423e-b12a-bda1da6e09de">

For example:

```go
req := &cloudbuildpb.CreateBuildTriggerRequest{
		Parent:    fmt.Sprintf("projects/%s/locations/%s", *serviceAccountProjectId, "us-central1"),
		ProjectId: *serviceAccountProjectId,
		Trigger: &cloudbuildpb.BuildTrigger{
			ServiceAccount: fmt.Sprintf("projects/%s/serviceAccounts/%s", *serviceAccountProjectId, *serviceAccountEmail),
			Name:           project.Name,
			Description:    "Test description",
			SourceToBuild: &cloudbuildpb.GitRepoSource{
				Source: &cloudbuildpb.GitRepoSource_Repository{
					Repository: repo,
				},
			},
```

if would be nice if we could specify like this:

```go
...CreateBuildTriggerRequest{
...
		Trigger: &cloudbuildpb.BuildTrigger{
                            ...,
                            IncludeBuildLogs: cloudbuildpb.INCLUDE_BUILD_LOGS_WITH_STATUS
                  }
...

```

There is no alternative that I have found for this. I will evaluate other options such as, allow my users to edit it after creation using the previous version of the lib.

We can se that it was included in [cloudbuildv1](https://github.com/googleapis/google-api-go-client/blob/v0.184.0/cloudbuild/v1/cloudbuild-gen.go#L1488) vs [v2/cloudbuildpb](https://github.com/googleapis/google-cloud-go/blob/cloudbuild/v1.16.1/cloudbuild/apiv1/v2/cloudbuildpb/cloudbuild.pb.go#L4734) that is not there.

I would like to also ask because maybe I am wrong in the way I am using the structures.

thanks!

**Comment by quartzmo** [comment]
The Cloud Build client is auto-generated from an interface description published by the product team. We are only able to assist with issues that pertain to the behaviors of this library. Because the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

You can also check the existing [Cloud Build issues](https://issuetracker.google.com/savedsearches/5226584) and file an issue there if there is not one already. All cloud issue trackers can be found at https://cloud.google.com/support/docs/issue-trackers.
