### ISSUE TITLE
alias fix only contains details for `StatusMigrated`, so it is missing everything else.

### ISSUE THREAD

**Issue by gchux** [googleapis/google-cloud-go#10700]
https://github.com/googleapis/google-cloud-go/blob/d0b38903e25495f5ba5dece1bfcf297ae0562237/internal/aliasfix/mappings.go#L44

**Comment by gchux** [comment]
it would also be convenient to know what's/where's the original `proto` file

**Comment by codyoss** [comment]
This was a tool to move sources from https://github.com/googleapis/go-genproto to this repo. This migration has been complete for libraries that we generate clients for. Because of this everything is of the migrated status. But this is an implementation detail -- the tool just helps re-write imports if needed.

Proto locations for all client libraries are in https://github.com/googleapis/googleapis. Looking at an old genproto import path just trim off the prefix of the import path and it maps exactly to the folder structure of that repo. Does that answer your questions?

**Comment by gchux** [comment]
I agree with the shared details; however, there are some inconsistencies, i/e: for datastore:

is uses import `pb "google.golang.org/genproto/googleapis/datastore/v1"`
> https://github.com/googleapis/google-cloud-go/blob/main/datastore/datastore.go#L31

and the `proto` reports the incorrect `option go_package = "cloud.google.com/go/datastore/apiv1/datastorepb;datastorepb";`:

https://github.com/googleapis/googleapis/blob/master/google/datastore/v1/datastore.proto#L30

but that package does not exist: https://github.com/googleapis/google-cloud-go/tree/main/datastore

for example, it only contains PBs for `admin/v1` which is reported in the `aliasfix` tool:

- https://github.com/googleapis/google-cloud-go/blob/main/internal/aliasfix/mappings.go#L709-L712
- https://github.com/googleapis/google-cloud-go/tree/main/datastore/admin/apiv1

**Comment by codyoss** [comment]
You are correct about datastore. It is the only client library that has not had sources moved yet, but will next week :)

Internal Bug: 330610884

**Comment by gchux** [comment]
amazing! thanks!
