### ISSUE TITLE
texttospeech api StreamingSynthesize input params not support AudioConfig?

### ISSUE THREAD

**Issue by lvzeyang01** [googleapis/google-cloud-go#10839]
```go
go func (){
                  reqs := []*texttospeechpb.StreamingSynthesizeRequest{
			{
				StreamingRequest: &texttospeechpb.StreamingSynthesizeRequest_StreamingConfig{
					StreamingConfig: &texttospeechpb.StreamingSynthesizeConfig{
						Voice: &texttospeechpb.VoiceSelectionParams{
							LanguageCode: lang,
							Name:         voiceName,
						},
					},
				},
			},
			{
				StreamingRequest: &texttospeechpb.StreamingSynthesizeRequest_Input{
					Input: &texttospeechpb.StreamingSynthesisInput{
						InputSource: &texttospeechpb.StreamingSynthesisInput_Text{Text: content},
					},
				},
			},
		}

		for _, req := range reqs {
			if err := stream.Send(req); err != nil {
				slf.Errorf("error sending request：%+v", err)
				return
			}
		}
		stream.CloseSend()
}()
```

the above code no field to apply AudioConfig?

**Comment by quartzmo** [comment]
The client libraries in this repo are based on interface descriptions published by product teams. We are only able to assist with issues that pertain to the behavior of the client libraries themselves.  If the issue you're experiencing is due to the design and/or behavior of the product and/or its API, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers. Please also check the existing [Cloud Text-to-Speech issues](https://issuetracker.google.com/savedsearches/5235428) and file an issue there if there is not one already. All cloud issue trackers can be found at https://cloud.google.com/support/docs/issue-trackers.
