### ISSUE TITLE
compute: ListRegionZonesRequest{Region: "europe-west1"} returns zones from other regions

### ISSUE THREAD

**Issue by dn0** [googleapis/google-cloud-go#10851]
## Client

compute.RegionsZonesClient

## Code and Dependencies

```go
package main

import (
    "context"
    "errors"
    "fmt"
    cloudCompute "cloud.google.com/go/compute/apiv1"
    "cloud.google.com/go/compute/apiv1/computepb"
    "google.golang.org/api/iterator"
)

func main() {
    client, _ := cloudCompute.NewRegionZonesRESTClient(context.Background())
    defer client.Close()

    iter := client.List(ctx, &computepb.ListRegionZonesRequest{
        Project: "some-project",
        Region:  "europe-west1",
    })

    for {
        res, err := iter.Next()
        if errors.Is(err, iterator.Done) {
            break
        }

        if res.GetStatus() == "UP" && res.GetDeprecated() == nil {
            fmt.Println(res.GetName()) // Shows `europe-west10-a`, `europe-west12-b`, ... !!!
        }
    }
}
```

<details>
  <summary>go.mod</summary>

```text
module modname

go 1.23

require (
   cloud.google.com/go/compute v1.28.0
)
```

</details>

## Expected behavior

The code should return zones that are in `europe-west1` only.

## Actual behavior

Result contains all zones in `europe-west1` and **`europe-west10` and `europe-west12`**.

## Additional context

Started after I've deployed first VMs in `europe-west10` and `europe-west12` in addition to existing VM in `europe-west1`.

**Comment by quartzmo** [comment]
Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behavior of this client library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers. You can also check the existing [Compute Engine issues](https://issuetracker.google.com/savedsearches/559755) and file an issue there if there is not one already. All cloud issue trackers can be found at https://cloud.google.com/support/docs/issue-trackers.
