### ISSUE TITLE
bigquery: FileConfig.MaxBadRecords int64 type should be int32

### ISSUE THREAD

**Issue by jonathaningram** [googleapis/google-cloud-go#11004]
## Client

BigQuery

Version: v1.61.0. But I can see the code is still the same on `main` at the time of writing: https://github.com/googleapis/google-cloud-go/blob/40c3a5b9c4cd4db2f1695e180419197b6a03ed7f/bigquery/file.go#L61

## Code and dependencies

```go
cfg := bigquery.FileConfig{
	MaxBadRecords: math.MaxInt64, // the Go client allows this but the API rejects it
}
```

## Expected behavior

The Go client's type matches the API's expected type.

## Actual behavior

Cannot pass an int64 despite the Go client suggesting I can.

API error is: `googleapi: Error 400: Invalid value at 'job.configuration.load.max_bad_records.value' (TYPE_INT32), 9223372036854775807`

## Additional context

See the proto spec which shows it should be an int32: https://github.com/googleapis/googleapis/blob/8a54a42f4af577626d8bf0d86cc7ef982951cd77/google/cloud/bigquery/v2/job_config.proto#L454

```protobuf
google.protobuf.Int32Value max_bad_records = 12 [(google.api.field_behavior) = OPTIONAL];
```

**Comment by alvarowolfx** [comment]
hey @jonathaningram thanks for the report. This is similar to some discussion on other REST based APIs like https://github.com/googleapis/google-api-go-client/issues/334 and https://github.com/googleapis/google-api-go-client/issues/1933. The problem is on the client generator, that uses int64 by default for all integer types. There is an old internal CL to change that on the generator https://code-review.git.corp.google.com/c/google-api-go-client/+/41831, but it was rejected because that would cause a breaking change on a lot of other clients and fields. You're facing this issue with the `FileConfig.MaxBadRecords`, but there are other fields with the same behavior.

**Comment by jonathaningram** [comment]
@alvarowolfx thanks for the references. Apologies I didn't find these existing precedents prior to posting. I'm fine to keep using our workaround. I'll close this. Please reopen if you want to track it so.
