### ISSUE TITLE
storage: v.1.44.0 release pulls in huge go-control-plane package 

### ISSUE THREAD

**Issue by hanord** [googleapis/google-cloud-go#11041]
Upgrading cloud.google.com/go/storage from 1.43.0 to 1.44.0 adds about 19MB in total to my build by pulling in a huge package.

I'm assuming this is not intentional. It may be an indirect dependency.

go-size-analyzer when building (on arm64) with go.mod containing "cloud.google.com/go/storage v1.43.0":

4.4 MB  myproject                           
4.1 MB  __rodata __DATA_CONST              
3.9 MB  __zdebug_info __DWARF
other packages not shown             
-----
44 MB total

Just updating go.mod with "cloud.google.com/go/storage v1.44.0":

8.1 MB  github.com/envoyproxy/go-control-plane  
6.0 MB  __rodata __DATA_CONST
5.0 MB  __zdebug_info __DWARF
4.4 MB  myproject
other packages not shown              
-----
63 MB total

$ go mod why -m github.com/envoyproxy/go-control-plane
  # github.com/envoyproxy/go-control-plane
  myproject/pkg/cloudobject
  cloud.google.com/go/storage
  google.golang.org/grpc/stats/opentelemetry
  google.golang.org/grpc/stats/opentelemetry.test
  github.com/envoyproxy/go-control-plane/envoy/config/cluster/v3

**Comment by tritone** [comment]
Hi there, yes this is intentional -- it's necessary for performance features with the new gRPC API.

We anticipated this issue and added a build tag (`disable_grpc_modules`) that allows users to opt out of these dependencies if desired (which won't have any effect on application performance if you're not using gRPC). See https://pkg.go.dev/cloud.google.com/go/storage#hdr-gRPC_API for more info.
