### ISSUE TITLE
pubsub/pstest: panics when provided a bad filter creating a subscription

### ISSUE THREAD

**Issue by tbushnell** [googleapis/google-cloud-go#11076]
## Client

PubSub
pstest

## Environment

Linux

## Code and Dependencies

`CreateSubscription` with an unusuable filter (say `"bad filter"`)

## Expected behavior

Should return an error.

## Actual behavior

Panics.
https://github.com/googleapis/google-cloud-go/blob/7e7c03e23c4dc51310ac8353d9c5137e2d9ff401/pubsub/pstest/fake.go#L911

## Additional context

This makes it annoying to test code which generates filters dynamically. ValidateFilter is nice enough, but
makes it hard to validate production code which does not itself generate the filters which it must then treat well. Such code would normally just hand the filter to CreateSubscription and return an error to its user. But that path is not testable with the package as it is.

There are a number of panics in the package actually, with comments saying that this is fine for testing. It's fine for testing *success* paths, but it's not very good for testing failure paths.

**Comment by hongalex** [comment]
Thanks for the suggestion. I created the above PR to fix the issue for a bad filter since it's a relatively easy fix. However, fixing the other instances of panic is not so easy since the validation steps don't bubble errors back up, which is why it was likely written with panics in the first place.

The other errors are unlikely to occur unless manipulating the `Server` directly.
