### ISSUE TITLE
texttospeech: missing v1beta1

### ISSUE THREAD

**Issue by ghchinoy** [googleapis/google-cloud-go#11133]
## Client

Text-to-Speech

## Environment

N/A

## Code and Dependencies

N/A

## Expected behavior

Expecting to see [texttospeech v1beta1](https://cloud.google.com/text-to-speech/docs/reference/rpc/google.cloud.texttospeech.v1beta1)  available as v1beta1 and v1 are documented and available via API/RPC, but only [apiv1](https://pkg.go.dev/cloud.google.com/go/texttospeech) is present in cloud.google.com/go/texttospeech

## Actual behavior

Only v1 (apiv1) represented in cloud.google.com/go/texttospeech package.

## Screenshots

N/A

## Additional context

N/A

**Comment by codyoss** [comment]
Just because we generate a surface for one version of an API we don't necessarily generate all known versions. In general, service teams opt-in to having their APIs generated. If you would like to see this API generated I recommend filing an issue against the service itself and request the libraries for use.
