### ISSUE TITLE
Error when filtering instances with GCP Go SDK compute instance client

### ISSUE THREAD

**Issue by xqi-aviatrix** [googleapis/google-cloud-go#11318]
https://github.com/googleapis/google-cloud-go/blob/c10a4bd350ba616f4edac56c286bb58c0caec394/compute/apiv1/instances_client.go#L435

My code is using the `c, err := compute.NewInstancesRESTClient(ctx)` compute instance client and calling its `AggregatedList` to filter instances based one network and network tags.

I follow the example on https://cloud.google.com/sdk/gcloud/reference/topic/filters to set the filter string. The filter string I set looks like `networkInterfaces.network:vpc1 AND tags.items=(vm-tag)` but get the following error
`googleapi: Error 400: Invalid value for field 'filter': 'networkInterfaces.network:vpc1 AND tags.items=(vm-tag)'. Invalid list filter expression.`

What should be the right way to set the filter string in the request? I can barely find any document on internet about it.

**Comment by quartzmo** [comment]
@xqi-aviatrix I searched the internet for filter usage with the GCE API as well, and also did not find anything. Unfortunately we can't help you with this question. The Compute client is auto-generated from an interface description published by the product team. We are only able to assist with issues that pertain to the behaviors of this library. Because the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

You can also check the existing [Compute Engine issues](https://issuetracker.google.com/savedsearches/559755) and ask your question there if there is not one already. All Cloud issue trackers can be found at https://cloud.google.com/support/docs/issue-trackers.
