### ISSUE TITLE
pubsub: clarification regarding creating many topic references to publish

### ISSUE THREAD

**Issue by jaeyeom9710** [googleapis/google-cloud-go#11317]
## Question
The docs for the pubsub API mention that we should "Avoid creating many Topic instances if you use them to publish." May I ask what is the reasoning behind this? Is there a lot of overhead (e.g. memory) to create a single Topic reference for publishing versus using a single Topic reference? If it's just a few MB of additional memory for a few dozen topic references, that wouldn't be too concerning for my use case.

## Context/reasoning behind the question
I have a use case to publish to a single topic, but would like to create multiple topic references to the same topic. This is because I have a use case that requires having more control over the publish network requests to pub/sub instead of having pub/sub handle this internally (due to having to write back to disk the messages in a batch request if the request failed with retries).

I would like to know the result of a single bundle/network request (by setting the pub/sub publish settings to max values and instead calling Flush() manually on each "batch"/"request"). With a single topic reference, if I were to create multiple "batches"/bundles and Flush() each concurrently, there could be some race conditions for our use case (please see footnote on race condition below). So I'd like to create separate Topic references and form a worker pool of Topic references/instances, and then assign each topic reference/worker for each batch/request and Flush() so that each request/bundle is fully isolated (within each Topic reference/instance).

## Footnote on possible race condition with single topic reference

Timeline:
t1: Goroutine 1: asynchronously Publish() 100 messages to pub/sub API (ideal case: bundle 1 of 100 messages)
t2: Goroutine 2: asynchronously Publish() 100 messages to pub/sub API (ideal case: bundle 2 of 100 messages)
t3: Goroutine 1: synchronously call Flush(), causing 200 messages to be bundled as one request/bundle (which is not what we wanted)
t4: Goroutine 2: synchronously Flush(), blocks until first Flush() is done due to lock on Bundle.Flush(), and then will be no-op.

We could synchronize and lock the call to Flush(), but then concurrency would suffer as only one bundle/request can be made at once due to a single Flush() being allowed at any given time.

**Comment by hongalex** [comment]
The reason we don't suggest creating a lot of topics is because we see users trying to wrap the entire topic instantiation in a publish call of their own, which is extremely inefficient.

```go
func myPublish(ctx context.Context, msg pubsub.Message) {
    t := pubsub.Topic("my-topic")
    t.Publish(ctx, msg)
    ...
}
```

In general also, it's more efficient to batch more messages into fewer publish requests. By having 5-10 topics you instantiate, but publishing at a low throughput to each, that's more publish requests you're making.

Your scenario seems fine to me and a good example of when our guidance doesn't apply. It's probably the exception rather than the norm though.

Last note: we are planning to release a new major version of the Pub/Sub library early next year. One of the changes we are making is that users will now instantiate `Publisher` clients to publish to Topics, rather than using a `Topic` to publish. This looks something like:

```go
publisher := pubsub.Publisher("my-topic")
publisher.Publish(...)
```

Nothing actionable right now, just a heads up this change is coming in the future.

**Comment by jaeyeom9710** [comment]
That makes a lot of sense, thank you so much @hongalex !  This also makes things much easier and more flexible for our use case as well.

> Last note: we are planning to release a new major version of the Pub/Sub library early next year. One of the changes we are making is that users will now instantiate Publisher clients to publish to Topics, rather than using a Topic to publish.

That sounds great, it makes it more intuitive at first glance as well. Thank you for the heads up!
