### ISSUE TITLE
It is not clear which Monitoring library to use.

### ISSUE THREAD

**Issue by jeffmendoza** [googleapis/google-cloud-go#1155]
https://godoc.org/cloud.google.com/go/monitoring/apiv3 Mentions that is is alpha and unstable.

https://cloud.google.com/monitoring/custom-metrics/reading-metrics#monitoring_read_timeseries_simple-go points to https://godoc.org/google.golang.org/api/monitoring/v3 However that is marked deprecated.

=)

**Comment by jba** [comment]
@tbpg We should be using cloud.google.com/go/monitoring/apiv3 for samples. 

@pongad Can you confirm the alpha status of this API?

**Comment by tbpg** [comment]
Happy to switch to whatever is recommended - let me know.

**Comment by jadekler** [comment]
@tbpg There does not appear to be a stable library, so instead of recommending folks use the deprecated apiary library, let's switch our recommendations to the non-GA veneer cloud.google.com/go/monitoring/apiv3.

@jeffmendoza As a sidenote, https://godoc.org/google.golang.org/api/monitoring/v3 was also non-GA. So, you're going from an alpha to a better, more mature alpha. Slightly better. :)

**Comment by pongad** [comment]
Sorry I missed this. I think monitoring/apiv3 should be good at this point. Java has marked it stable a long time ago. I think we're OK to do the same.

**Comment by tbpg** [comment]
Sounds good! Thanks.

**Comment by jeffmendoza** [comment]
Thanks all, I'll need to update to veneer then, I ended up using apiary here:
https://github.com/istio/istio/blob/0f39c7daa9abf255e069370866da529e9bb2270b/tests/e2e/tests/stackdriver/stackdriver_test.go#L31

**Comment by enocom** [comment]
https://github.com/GoogleCloudPlatform/golang-samples/pull/682 updates the documentation to use `cloud.google.com/go/monitoring/apiv3`.
