### ISSUE TITLE
Local development logging?

### ISSUE THREAD

**Issue by joseph-norman** [googleapis/google-cloud-go#1260]
Hi,

Forgive me if I've missed something in plainsight or equivalent, but is it possible to forward log entries to stdout for say, local development?

I'm considering migrating from using the Docker gcplogs driver to utilising the logging library, but wasn't able to resolve this after looking at the docs. Perhaps I missed something?

Thanks!

**Comment by jadekler** [comment]
I don't believe so, no. 

However, the logging library provides a [log.Logger](https://godoc.org/cloud.google.com/go/logging#hdr-The_Standard_Logger_Interface). You could configure your program to alternate between that or [`log.New`](https://golang.org/pkg/log/#New) per your needs (however you decide dev vs prod, for example). It's not an exact match, since you'll need to limit yourself to a single severity level.

**Comment by joseph-norman** [comment]
Hi @jadekler - thanks for getting back to me on this. Your proposed solution / idea sounds like a great plan. Much appreciated!
