### ISSUE TITLE
Firestore nested transaction check too strict

### ISSUE THREAD

**Issue by mickeyreiss** [googleapis/google-cloud-go#1265]
firestore's RunTransaction does a sanity check for nested transactions:

https://github.com/googleapis/google-cloud-go/blob/3bec1e11d6972bd04fd9a0ecbd4fcff0f5810439/firestore/transaction.go#L100-L103

There are cases where nested transactions may make sense or are more convenient. In my case, it is random non-transactional reads and writes that occur inside of the RunTransaction block.

If this feature is critical to firestore's operation, why require the user to pass around `tx` at all, when `ctx` could be sufficient to pass around the transaction handle?

**Comment by jba** [comment]
IANADBE (I am not a DB expert), but non-transactional operations inside a transaction seem nonsensical to me, or at least unnecessary. 

- Reads: if you want the value at the time the transaction started, run it in the transaction. If you want the "current" value, then you could have inconsistent information: transaction reads (of X, say) give you values at transaction start time, but non-transactional ones (of Y) give you later values. If another transaction commits while yours is running and changes X and Y atomically, you'll observe the inconsistent state (old X, new Y). 

- Writes: If your write is based on information you gathered in the transaction, then it may be based on out-of-date data: another transaction may have changed those values and committed. Doing the write in the transaction ensures that the reads and writes occur atomically (in the previous sentence's situation, the transaction would abort and retry). And if your write is based on information you gathered before the transaction, why is it happening in the RunTransaction function?

**Comment by schmidt-sebastian** [comment]
We don't validate this in any other SDK. I would let the user decide what is best for them in this case (and recommend that they don't do this).

**Comment by mikelehen** [comment]
@mickeyreiss Can you elaborate on the non-transactional reads/writes you're doing inside the transaction?  Per @jba's comments, that does raise a bit of a red flag for me. Doing writes especially, since the transaction may retry.

In general though, I don't have strong feelings.  As Sebastian says, we don't enforce this in any other client, though we also don't have an easy opportunity to (In JavaScript it's impossible, and on Android / iOS we'd have to use thread-local storage I guess).  To be clear, the existing go implementation will allow simultaneous transactions on different threads (or goroutines or whatever), right?

**Comment by mickeyreiss** [comment]
Here's some more background info:

> @mickeyreiss Can you elaborate on the non-transactional reads/writes you're doing inside the transaction? Per @jba's comments, that does raise a bit of a red flag for me. Doing writes especially, since the transaction may retry.

@mikelehen Fair enough. This may represent tech debt, if not an essential complexity. We are using two documents in firestore for different purposes. The first is effectively an Event or action request, and it's important that we process it as written—concurrent writes may lead to incorrect processing (in particular, duplicate external API calls). The other is simply data mirroring. These side-effects are less critical to isolate because they simply mirror data from our SQL DB, so the consistency story is less complicated.

> To be clear, the existing go implementation will allow simultaneous transactions on different threads (or goroutines or whatever), right?

I guess there is a workaround—if I use a new context. But that would not be conventional in go, especially since `transactionInProgressKey` is not exposed.

In the meantime, we are not blocking on this fix. We have addressed some of the tech debt and removed the non-transactional writes in the side-effect code. I do appreciate all of your input on the topic; it was helpful for debugging on our end.

> If this feature is critical to firestore's operation, why require the user to pass around tx at all, when ctx could be sufficient to pass around the transaction handle?

@jba @jadekler I do stand by this original statement. It sounds to me like the SDK should take an opinionated stand and potentially revise the API to prevent confusion about the behavior.

**Comment by mickeyreiss** [comment]
I have found another subtle issue with the current approach.

It is possible to pass the `ctx` into a new goroutine. In this case, the new goroutine may write to firestore outside of the original transaction, but the SDK reports the transaction in progress error. 

This came up due to my application performing side-effects in a non-blocking goroutine to avoid blocking/failing the user-interactive work.

**Comment by jadekler** [comment]
@mickeyreiss We noticed that too. It seemed a bit too subtle, so we just removed the check.

**Comment by mickeyreiss** [comment]
Great! Thanks for your help with this. I'll post back if that commit causes any issues in our setup.

**Comment by jadekler** [comment]
Thank you, please do!

**Comment by neoinmtv** [comment]
@mickeyreiss 
I still cannot use nested transaction. The code didn't change. https://github.com/googleapis/google-cloud-go/blob/v0.39.0/firestore/transaction.go#L98
This led me having to passing around ctx, *tx, *client for a thousand times and lead to weird bugs (see [1]). One example is I want to increment a success_counter along side a normal write transaction but don't want to leave the counter logic in a separate package.

[1] I had to manually pass *firestore.client for the the counter adder method, because if I create a new client there and then write "defer client.Close()"[2], I see such errors, which I guess is because tx.Set() has to use that client later for the actual writing:

> ERROR: 2019/05/26 04:36:43 pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing

[2] Code:
```
func AddCounterInTx(ctx context.Context, tx *firestore.Transaction, name string, cur, toAdd int) error {
	client := creds.GetFirestoreClient(ctx)
	defer client.Close() // This emits log ERROR with tx.Set: "ERROR client closing", but no actual harm (found)

	ct := client.Collection(GlobalCounterCollection).Doc(name)
	err := tx.Set(ct, map[string]interface{}{
		CounterField: cur + toAdd,
	})
	if err != nil {
		log.Errorf(ctx, "Failed to Add Counter In Tx %v: %v", name, err)
		return err
	}
	return nil
}
```

BTW I'm neoliu@, please and feel free to talk to me.

**Comment by jadekler** [comment]
@neoinmtv please create a new issue if you are still experiencing problems.
