### ISSUE TITLE
firestore: support integer map keys

### ISSUE THREAD

**Issue by jba** [googleapis/google-cloud-go#1268]
When a map is part of a Firestore document, it must have string keys. Consider allowing integer keys too (implemented by converting them to and from strings). Rationale: `encoding/json` supports it.

This actually happened to me: I started to migrate an app from using `encoding/json` to this client, and my `map[int]Foo` failed to encode.

Subject to OK by @schmidt-sebastian.

**Comment by schmidt-sebastian** [comment]
My gut feeling says that this might be a step in the wrong direction:

- For the most part, the SDKs can read back the exact same object that was persisted in Firestore. The Firestore encoding is meant to me "lossless", and this would break this invariant. We do already break this invariant in other places (Date <=> Timestamp ) conversion, but I would prefer if we limit these occurrences.

- Supporting integer keys in maps will make it easy to implement array-like data structures that use consecutive keys. These data structures don't work well here, since many client can write to the same array. Common operations  - such appending a new element to the end  - create confusing behavior when backed by Firestore. That's why we went out of our way with `arrayUnion` and `arrayRemove` to support set-like semantics.

That being said, if this is a common enough feature request for Go, I can certainly  live with this. Let's see if @mikelehen has other thoughts.

**Comment by mikelehen** [comment]
I don't think I have strong feelings... Comparing to other platforms:

- JavaScript map (object) keys are always strings, but you can initialize a map using integers and they'll be converted to strings automatically (so `doc.set({1: true})` works fine).
- On Android we only accept `Map<String, Object>` in the API.
- On iOS we only accept `NSDictionary<NSString *, id> *` in the API.

I don't think I've seen any feedback on this on the other platforms, so my default would be to keep Go the same.  But I could be pretty easily won over if we think the encoding/json parity is worthwhile. We have in the past looked at platform-specific JSON libraries as inspiration for how to shape our APIs.

**Comment by jba** [comment]
Probably best to be consistent with the other typed languages' clients, and not do this.
