### ISSUE TITLE
pubsub: Pull Queues hard to wrap my mind around

### ISSUE THREAD

**Issue by TheImpressionist** [googleapis/google-cloud-go#1269]
Since flex doesn't support queues outside of cloudtasks, which in turn don't actually support pull queues (so much frustration with the said fact as well as the fact that the documentation was a nightmare to get through for golang) I feel like Im defeated here...

Let me explain what I'm trying todo. If this is not the right place to ask questions, then by all means please let me know.

I need to do a bulk write to my database every set amount of minutes. Which is not the problem in itself. The problem is that cloudtasks only offer push queues. I need to pull them all or a certain set of them at my own convenience.

You keep stating that **Pub/Sub** can solve this issue. However, since I do cannot know the outstanding message length, at least any method that I've checked, I cannot really know when to cancel the `Receive` method.

Basically, say, if I have 10 000 outstanding messages, I need to process only the first 5000. Which is fine, I'll increase the counter until it reaches 5000 and then do whatever to stop receiving messages and just bulk write them to the DB.

Here's where the issue comes in, if the current outstanding message count is lower than 5000, I'm gonna be waiting for the `Receive` to get to 5000 at some point. Might take a second, might take days.

What I need is to know the total amount of messages in queue, and pull all of them or a certain amount of them. As far as I understand, that's not possible?

I suppose I could check when the last message was received, and if a certain amount of time has passed, then just stop receiving and handle the messages that I've stored internally. But the intervals at which the messages come in can be so irregular.

We have to do batch inserts , since we get a lot of small requests, and our database cannot handle a certain amount of concurrent inserts. Crashes ensued, data got corrupted, things got ugly.

Oh, and by no means we should ever receive duplicate messages. Because that would throw off a lot of things. And I've seen a lot of topics discussing issues with message duplication here.

So I'm guessing I'm gonna have to use a custom solution.

**Comment by jadekler** [comment]
> the documentation was a nightmare to get through for golang

Could you elaborate on which documentation was hard to get through, and what you were trying to accomplish? We'd love to improve where we can.

> What I need is to know the total amount of messages in queue, and pull all of them or a certain amount of them. As far as I understand, that's not possible?

I don't believe the first part of that is possible. The second part is possible, but you'll have to use the underlying admin API. See: https://godoc.org/cloud.google.com/go/pubsub/apiv1#SubscriberClient.Pull.

> Oh, and by no means we should ever receive duplicate messages.

I do not know of any queueing system that offers exactly-once delivery, and I would be skeptical of one that does offer such a thing. :)

**Comment by dwalker-va** [comment]
I have some experience doing this. You can pull messages one at a time, pushing them into a bundler running asynchronously in your app. When the bundler reaches a capacity of 5000 (or after some regular interval), it flushes - you batch writes to your db. This way the number of remaining messages in the subscription is irrelevant, you're pulling 1 by 1 until you get 5000, then composing a batch write. I should note that the receive method is scaling out under the hood unless you've set some configuration options to prevent it from doing so, so it's very natural to write the receive method from the perspective of a single message and let the library do all the concurrency, if a little too magical imo.

Gotchas include making sure your flush timer is less than the time that your client is allowing your application to acknowledge the pubsub message, or redelivery will be attempted. So if you have activity with cardinality < 5000, you need to be ok with writing to the database at a period less than the ackDeadline.

Depending on how exactly you are batching writes, this may not be nice. If the batcher flush fails, you need to not ack or explicitly nack all 5000 messages, which is easy to do in code, but if you aren't writing those 5000 rows in a single transaction, you might have a case where 4999 rows succeeded, 1 failed, and then you're retrying a TON of work that you don't need to do. So hopefully it's a true batch insert.

As for duplicate messages you have to handle that on your side. I didn't have any problems with this because at first we used an external version number on every row that we could just write a clause around into the transaction, and then we started using the spanner timestamp after moving to spanner which (if you trust it) replaced the external version number completely.

**Comment by jadekler** [comment]
Closing since this seems to have been answered. Thanks @dwalker-va for your input. Give a shout if there's more to discuss here, though @TheImpressionist.
