### ISSUE TITLE
logging: add net/http middleware to summarize into *logging.HTTPRequest

### ISSUE THREAD

**Issue by nhooyr** [googleapis/google-cloud-go#1292]
https://godoc.org/cloud.google.com/go/logging#HTTPRequest

Would bench to see some http middlewere to automatically fill in the various values. Not sure how the cache fields would work with the middleware though.

**Comment by jadekler** [comment]
Could you expand on this? I'm having a bit of trouble grokking the feature request, though I haven't had coffee in a while... :) What middleware are you using, and how would you expect this to work?

**Comment by nhooyr** [comment]
I want to be able to automatically generate the `*HTTPRequest` for logging purposes. I was thinking the function to do this could be implemented as HTTP middleware where it wraps around my http.Handler. See https://hackernoon.com/simple-http-middleware-with-go-79a4ad62889b

It could easily fill all the fields except for the caching related fields.

**Comment by odeke-em** [comment]
Hello @nhooyr, thank you for this feature-request!

Adding middleware to this package might be out of the scope because *logging.HTTPRequest is meant just for logging purposes and retrieving those fields would require an entire roundtrip in order to get ResponseBytes, Latency, Status. Also it is debatable whether implementing this for the server won't also warrant implementing it for the client as an `net/http.RoundTripper`. There are also subtleties like: with all that middleware chaining you lose implemented net/http interfaces such as Pusher, CloseNotifier and this becomes a maintenance pain to have to deal with.

I think you can implement this on your end and I helped with a similar solution for OpenCensus-Go as per:
* client stats and tracing https://github.com/census-instrumentation/opencensus-go/blob/f24e56296b3a742d13b8368bbb1e831f9b0d2c7f/plugin/ochttp/client_stats.go#L29-L143
* server stats and tracing https://github.com/census-instrumentation/opencensus-go/blob/f24e56296b3a742d13b8368bbb1e831f9b0d2c7f/plugin/ochttp/server.go#L44-L449

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
