### ISSUE TITLE
pubsub: Default Goroutines Limit Subscriber Throughput

### ISSUE THREAD

**Issue by dpcollins-google** [googleapis/google-cloud-go#1300]
## Client

Pub/Sub

## Describe Your Environment

Ubuntu on Compute Engine 16 core machine

## Expected Behavior

Messages have high throughput and message handler uses full cpu.

## Actual Behavior

Messages arrive slowly with default settings due to NumGoroutines defaulting to 1.  This leads to throughput significantly slower than the maximum in the default case, on the order of 1/4 throughput in tests with 1k message sizes.

## Proposed Change

Increase the NumGoroutines default to some multiple of runtime.NumCPU().  The java client libraries use 5, perhaps use this multiple?  If not, a multiple of 1 or 2.

**Comment by jadekler** [comment]
Thanks for opening this issue. We chose the lower number since it was safe to use in the slowest GCE VM at the time (and may still be). Higher numbers can OOM users, which is a poor experience.

We have plans to re-investigate the default performance this summer. In the meantime, we're counting on a large body of documentation that we've written to help users reach their performance needs. Closing and tracking summer work internally.

**Comment by dpcollins-google** [comment]
Please consider reopening this.  I'd argue having the default at 1 is a poor experience for high-throughput use cases, since it may be unclear why throughput doesn't scale with instance size.  The defaults should be a tolerable option for all use cases.

If you set the default to NumCPUs(), it would be 1 for the smallest GCE instances, while still scaling up to a reasonable number as the instances got larger.
