### ISSUE TITLE
Datastore examples runtime panic

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1307]
https://godoc.org/cloud.google.com/go/datastore#hdr-Key_Field

The following code in that doc:

```
type MyEntity struct {
	A int
	K *datastore.Key `datastore:"__key__"`
}

k := datastore.NameKey("Entity", "stringID", nil)
e := MyEntity{A: 12}
k, err = dsClient.Put(ctx, k, e)
if err != nil {
	// Handle error.
}

var entities []MyEntity
q := datastore.NewQuery("Entity").Filter("A =", 12).Limit(1)
_, err := dsClient.GetAll(ctx, q, &entities)
if err != nil {
	// Handle error
}

log.Println(entities[0])
// Prints {12 /Entity,stringID}
```

Panics on the Put call:

```
$ go run main.go 
panic: datastore: invalid entity type

goroutine 1 [running]:
main.main()
	/usr/local/google/home/deklerk/workspace/go/src/dummy/datastore-panic/main.go:26 +0x563
exit status 2
```

**Comment by jadekler** [comment]
Note: there may be other occurrences. Would be good to do a full sweep.

**Comment by poy** [comment]
I'm going to move this example into a `main` function so that its closer to a real example. As of now, the user would have to fill in several pieces. I'll model it after the very first example in the doc. 

We should also consider moving away from a generic project name to receiving an environment variable. This will better highlight what has to be adjusted for the example to work for a user. I'm assuming there will be some copy-paste from these examples.

**Comment by poy** [comment]
I checked the other examples (in the datastore package) and they look good.
