### ISSUE TITLE
Firestore: How to know when to commit batch writes?

### ISSUE THREAD

**Issue by dbolkensteyn** [googleapis/google-cloud-go#1315]
According to this table: https://firebase.google.com/docs/firestore/quotas#writes_and_transactions, any single batch write can consist of at most 500 writes and the total overall size of the API message cannot exceed 10MiB.

I am using batches only to reduces the number of network round-trips and do not particularly care when they are committed. However, I need to be able to know when to commit in a reliable way, before either of the two limits is reached. Counting writes is easy, the challenge is on the 10MiB limit. A naive ugly-but-simple approach would be to marshal the final protobuf message and check its size each time a new write is added: https://github.com/googleapis/google-cloud-go/blob/master/firestore/client.go#L230, however those fields are not exported. An alernative, more complex way, would be to (recursively) split the array of writes in 2 and issue multiple commits whenever the error `413:Request Entity Too Large` is returned by the server.

Reproducer:
```
b := client.Batch()
col := client.Collection("test")
for _, i := range []int64{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13} { // 13 < 500, OK
  b.Set(col.Doc(strconv.FormatInt(i, 10)), map[string]interface{}{
    "BigData": strings.Repeat("a", 900000), // Slightly less than 1 MiB per doc
  })
}
_, err := b.Commit(context.TODO())
if err != nil {
  // Fails with "413:Request Entity Too Large"
  log.Fatalln("Could not commit:", err)
} else {
  log.Fatalln("Could not reproduce issue #1315")
}
```

Any recommendation? Thank you

**Comment by jadekler** [comment]
I believe grpc's default server receive size is 4MiB https://github.com/grpc/grpc-go/blob/master/server.go#L55. @menghanl is that correct? cc @mikelehen

**Comment by mikelehen** [comment]
I'm not aware of any grpc limits that should come into play.  AFAIK you should be able to send the maximum message size Firestore supports (10MiB).

The question here seems to be about how to determine when you'll hit that limit client-side (other than resorting to byte counting), and I'm afraid I don't have a good answer beyond the two approaches you've considered.

That said, I'm a little curious why you are trying to minimize round-trips. Does that make your code run substantially faster? 

FWIW- Doing a batch write means that the backend needs to update all of the documents as a single atomic batch, which comes at a cost. You are at greater risk of writes failing due to contention, etc.  So if you don't need a batch, it may be better not to use it.

**Comment by dbolkensteyn** [comment]
Sorry for the late reply.

Indeed @mikelehen your comprehension of my question is right : it's about knowing when to commit the batched write, prior to reaching the 10MiB limit.

Removing batched writes by individual ones is the first thing I tried. However the overall processing time increases from a dozen seconds to tens of minutes.

Don't you expect many consumers of the batched write API to be affected by this challenge? As soon as your document is of variable length, document counting alone is no longer reliable.

**Comment by mikelehen** [comment]
When you say it increased to tens of minutes, were you performing multiple writes in parallel?  Or waiting for each one to complete before starting the next?  Ideally you wouldn't need to use batch writes for performance reasons.

**Comment by dbolkensteyn** [comment]
I indeed was issuing the individual writes sequentially - will switch to rely on goroutines to be able to issue them concurrently.

Closing this issue.
