### ISSUE TITLE
Provide built in types cloud-function-firestore data

### ISSUE THREAD

**Issue by ptone** [googleapis/google-cloud-go#1321]
Would be nice to have the boilerplate of 

```
// FirestoreValue holds Firestore fields.
type FirestoreValue struct {
	CreateTime time.Time `json:"createTime"`
	// Fields is the data for this value. The type depends on the format of your
	// database. Log the interface{} value and inspect the result to see a JSON
	// representation of your database fields.
	Fields     interface{} `json:"fields"`
	Name       string      `json:"name"`
	UpdateTime time.Time   `json:"updateTime"`
}

// FirestoreEvent is the payload of a Firestore event.
type FirestoreEvent struct {
	OldValue   FirestoreValue `json:"oldValue"`
	Value      FirestoreValue `json:"value"`
	UpdateMask struct {
		FieldPaths []string `json:"fieldPaths"`
	} `json:"updateMask"`
}
```

From the golang functions samples included directly in this package adjacent to the metadata parser

**Comment by jadekler** [comment]
@tbpg Are [those types](https://github.com/GoogleCloudPlatform/golang-samples/blob/a699cc86997175aa096113486151599df8948a10/functions/console_snippets/firestore/firestore.go#L27-L45) special in any way to functions, or just generic structs to store value?

**Comment by tbpg** [comment]
I like the idea of having a shared package with event definitions. But, I'm not sure they should be in something like cloud.google.com/go/functions/events. I'd prefer if they were generic events not tied to Cloud Functions (so they can be used in other event processing platforms and have it make sense). Not sure where this should live yet.

Firestore is a bit weird in that the `Fields` value is unique to the database structure. You can customize it for your data. A generic type may or may not be useful there.

Know that it's on our mind, but I would close this issue for now.

**Comment by cubuspl42** [comment]
@tbpg In my experience, that's not how issues work... It's a feature request issue, and they are supposed to be closed when functionality is implemented. I can't understand why you closed this issue.

**Comment by jadekler** [comment]
We have before and will continue to close feature requests to that we "reject".

**Comment by cubuspl42** [comment]
Obviously, that's understandable. It wasn't clear at all for me that this is rejected.

If it is, then I'd like to ask you to reconsider it. The reasoning against this feature isn't clear for me. If only `Fields` is dynamic, then it can be declared as `interface{}`, right? (I'm new to Go, please correct me if I'm wrong) I also can't relate to "not sure where" part, from programmer's perspective it's a part of Cloud Functions programming interface, so I can't understand why these sturctures' definition don't fit to `cloud.google.com/go/functions/events`. That's where I'd expect to find them.

I've just spend much time trying to figure out where I can find wildcards values inside the event, and I still haven't succeeded. If the value was properly modelled in Go, that would be as easy as pressing "Tab" key.

**Comment by tbpg** [comment]
Sorry that wasn't clear.

Yes, `Fields` could be defined as `interface{}` -- people could convert it to the type of their choosing. But, it's a nicer experience if you define that particular field yourself, so you don't have to do any conversion. On the other hand, I agree it's not a very nice experience to not have any type defined at all and having to figure it out.

The idea is these event types could be used for a variety of event-processing options, not just Cloud Functions. That's why I'd prefer to not have this tied directly to Cloud Functions. In this case, the guiding idea right now is that a bit more copying is better than another dependency without a clear path forward. I hope that makes sense.

Can you be more specific about wildcards in the event? What field are you looking for? In general, you can print the value from the event by making your function arg `interface{}` and printing it -- you'll see the underlying JSON that is getting unmarshaled.
