### ISSUE TITLE
Enhancement: Out of band end-of-results signal for GCS

### ISSUE THREAD

**Issue by mcandre** [googleapis/google-cloud-go#1330]
The GCS object query API is overall fairly tame. However, the reuse of the `error` value to indicate end of results makes the user error handling flow a bit more cumbersome than necessary.

Some API's use a `done` channel specifically for this purpose. What do we think of adopting this in the next Go API version for GCS?

**Comment by jba** [comment]
Do you mean the behavior of the `ObjectIterator` returned from `storage.BucketHandle.Objects`?

We decided to use a special error value to indicate the end because that's done elsewhere, like the standard library's `io.Reader.Read` method and gRPC's streams. All our iterators follow the [same pattern](https://github.com/googleapis/google-cloud-go/wiki/Iterator-Guidelines).

We considered a more streamlined design where callers have to check for errors at the end of the iteration, like [`bufio.Scanner`](https://godoc.org/bufio#Scanner). We ultimately rejected it because we had evidence that people tended to forget to call the `Err` method.

Using a channel wouldn't be appropriate here because this is a synchronous API.

**Comment by jadekler** [comment]
Hello! We've asked some clarifying questions and haven't heard back from you in a while. Closing this issue but feel free to return to this conversation and reply at a later point.
