### ISSUE TITLE
pub sub: How to reconnect properly?

### ISSUE THREAD

**Issue by bzon** [googleapis/google-cloud-go#1332]
## Problem

In cases of outbound intermittent outbound connection or google pubsub service having a downtime. How would you handle this?

### Client

PubSub

**Comment by jadekler** [comment]
Pub/Sub uses gRPC under the hood. One of the nice things about that is that gRPC will manage connections (and reconnections) for you. That means that you can keep retrying a method until the service is available again, and then the method will work again (under the hood, gRPC had been trying to reconnect the whole time).

Here's an example using https://godoc.org/github.com/googleapis/gax-go/v2#Retryer, whose retry logic is based on https://github.com/grpc/grpc-go/blob/master/codes/codes.go. Note that it's a non-sensical example since client libraries already retry

```
package main

import (
	"cloud.google.com/go/pubsub"
	"context"
	"github.com/googleapis/gax-go/v2"
	"google.golang.org/grpc/codes"
	"time"
)

func main() {
	ctx := context.Background()
	client, err := pubsub.NewClient(ctx, "project-id")
	if err != nil {
		// TODO: Handle error.
	}

	topic, err := createTopicWithRetry(ctx, client, "someTopicName")
	if err != nil {
		// TODO: handle unrecoverable error
	}
	_ = topic // TODO: use topic
}

func createTopicWithRetry(ctx context.Context, client *pubsub.Client, topicName string) (*pubsub.Topic, error) {
	exponentialBackoff := gax.Backoff{Initial: time.Second, Max: 30*time.Second}
	// Non-sensical, since client libraries already retry Unavailable. Just an example.
	retryer := gax.OnCodes([]codes.Code{codes.Unavailable}, exponentialBackoff)

	for {
		topic, err := client.CreateTopic(ctx, topicName)
		if err != nil {
			pauseTime, shouldRetry := retryer.Retry(err)
			if shouldRetry {
				time.Sleep(pauseTime)
				continue 	// Recoverable error - retry
			}
			return nil, err // Unrecoverable error
		}
		return topic, nil
	}
}
```

**Comment by bzon** [comment]
thanks @jadekler 

closing this issue now

**Comment by f0o** [comment]
How to catch and handle PullSubscription disconnection? This just happened to me and no automatic reconnect happened; I had to manually kill and restart the service to reconnect
