### ISSUE TITLE
Firestore [rpc error: code = Unauthenticated desc = transport: oauth2: cannot fetch token...]

### ISSUE THREAD

**Issue by RocksteadyDog** [googleapis/google-cloud-go#1351]
## Client

Firestore

## Describe Your Environment

go version go1.12, 1.11
Environment: windows

## Expected Behavior

no errors)

## Actual Behavior

Step 1: Initialize Cloud Firestore
https://cloud.google.com/firestore/docs/quickstart-servers#initialize
Step 2:  Adding Data to Cloud Firestore
https://cloud.google.com/firestore/docs/manage-data/add-data#set_a_document
Step 3: Sometimes an error occurs  -
rpc error: code = Unauthenticated desc = transport: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Code:

"func main(){
	ctx := context.Background()
	client, err := firestore.NewClient(ctx, "project-xxxxxx")
	if err != nil {
		log.Fatalln("Firestore init error:", err)
	}
	 if _, err := client.Collection("COLL_NAME").Doc("DOC_ID").Set(context.Background(), map[string]interface{}{
		"ping": "pong",
	}, firestore.MergeAll); err != nil {
		log.Fatalln("Set error:", err) // ERROR  (response time ~0-1s)
	} 
}"

Thanks

**Comment by jadekler** [comment]
```
client, err := firestore.NewClient(ctx, "project-xxxxxx")
```

Since you're not providing any [auth options](https://godoc.org/google.golang.org/api/option), it's trying to use application default credentials (as specified [here](https://godoc.org/golang.org/x/oauth2/google#FindDefaultCredentials)).

Either providing an auth option or setting up application default credentials (see https://cloud.google.com/docs/authentication/production) should fix the issue.
