### ISSUE TITLE
Difficult to update a subscription's configured topic

### ISSUE THREAD

**Issue by mcandre** [googleapis/google-cloud-go#1353]
The `Update()` method for subscriptions allows some configurations to be modified, but not the most critical one: the topic!

As a workaround, I am using lower level `Subscription()`, `Config()`, manually checking the configuration details, and then applying `Delete()`, `CreateSubscription()` when necessary.

**Comment by jadekler** [comment]
Please see [Topic.Update](https://godoc.org/cloud.google.com/go/pubsub#Topic.Update).

**Comment by mcandre** [comment]
Are you sure? I don't want to change any Pub/Sub topics. I want to change which topic a subscription points at.

**Comment by jadekler** [comment]
Ah! I see. Subscriptions are tightly scoped to their topics, to my understanding. Is there a reason why creating a new subscription for the new topic would not work?

**Comment by mcandre** [comment]
Basically, I am structuring my Go application to enforce the desired Google resource configuration at launch. I want to effectively upsert the Pub/Sub subscription configuration.

As a workaround, I am checking for an existing subscription, verifying the desired configuration, deleting if necessary, creating if necessary (whew!)

**Comment by jadekler** [comment]
Gotcha. I doubt that we'll ever allow a subscription to change which topic it's configured to, but I'll let the authorities weigh in. cc @kamalaboulhosn @sduskis

**Comment by kamalaboulhosn** [comment]
I'm still not sure I understand what the goal is in changing the topic with which a subscription is associated. What is the expected behavior? Is it trying to be used as a shorthand for delete the old subscription and then create a new subscription on the new topic? I wouldn't expect this to be an API we plan to offer as subscriptions are tightly tied to the topic on which they are initially created.
