### ISSUE TITLE
bigtable emulator: match keys and values as bytes

### ISSUE THREAD

**Issue by evanj** [googleapis/google-cloud-go#1373]
## Client

BigTable

## Describe Your Environment

Mac OS X 10.14.3

## Expected Behavior

If a cell contains the value `[]byte{0x80}` it should be matched by the following row filter:

```go
bigtable.RowFilter(bigtable.ValueFilter("\x80"))
```

## Actual Behavior

This matches no rows on the emulator, but does match on the real Bigtable.

This fix seems to work for me: https://code-review.googlesource.com/c/gocloud/+/39233

**Comment by Naveg** [comment]
Any chance we can pull in the fix for this? We use the bigtable emulator for tests and are prevented from using certain filters due to this bug.

**Comment by jimfulton** [comment]
@evanj @Naveg 

It looks like this was fixed by #3776 .  The test changes here: https://code.googlesource.com/gocloud/+/234a9235f345c7024baf6553b13179325c00cd32%5E%21/#F0 pass for me without the code changes.
(The code changes won't work because toUTF8 no-longer exists.)

Could you please verify that you're still having a problem? 

If so, could you provide a test case?

**Comment by telpirion** [comment]
Please provide a response and reopen this issue if you are still experiencing this. Thank you!
