### ISSUE TITLE
firestore: allow setting listen Target.read_time

### ISSUE THREAD

**Issue by marcin-ptaszynski** [googleapis/google-cloud-go#1428]
Current client `Query.Snapshots()` does not expose ability to set Listen [Target.read_time](https://github.com/googleapis/googleapis/blob/03269e767cff9dd644d7784a4d4350b2ba6daf69/google/firestore/v1/firestore.proto#L654).

While I understand that from high-level perspective of client library design, resume tokens may be treated as internals to handle failures scenarios, there is a good use-case where it's good to have anyway.

Consider "batch Query.GetAll, then resume Listen" scenario, where user needs clear demarcation point between the two (e.g. render full page at once, diffing of caches).

With current iterator `q.Snapshots()`, there is no way to tell that, because client gets initial stream of `DocumentAdded` changes and then hangs until some *actual* change happens. Only after first change, we can detect it by comparing `snapshot.UpdateTime` with previous `snapshot.ReadTime`. Any timing heuristics are out of the question, and getting same data twice seems wasteful as well.

Proposal: add option `ListenResumeTime(time.Time)` and extend method `Query.Snapshots(opts... ListenOpts)`, which passes it to new Target.

What do you think?

**Comment by jadekler** [comment]
cc @schmidt-sebastian @benwhitehead

**Comment by schmidt-sebastian** [comment]
@marcin-ptaszynski Thanks for filing this issue! This is a feature request that comes up from time to time. Our suggested solution has been to use ServerTimestamps and to use the existing Query API and filter based on these timestamps. 

We are still evaluating whether we will eventually provide first-level support to resume Queries at "arbitrary" points in time, but we currently are not actively working on this.

**Comment by marcin-ptaszynski** [comment]
Thanks @schmidt-sebastian for this suggestion, unfortunately this will not work for scenarios when documents are deleted (unless we leave tombstones).

I still have a question unrelated to Go Client itself, but API spec. I'd be grateful, if you could clarify this. When performing `read_time` based `Query + Listen` as described above, does
1. Firestore guarantee [RunQuery](https://github.com/googleapis/googleapis/blob/03269e767cff9dd644d7784a4d4350b2ba6daf69/google/firestore/v1/firestore.proto#L474) establishes consistent snapshot, which can be resumed using last `read_time` and no events will be lost? Or
2. We can only use `read_time/resume_token`, which was previously returned as [TargetChange](https://github.com/googleapis/googleapis/blob/03269e767cff9dd644d7784a4d4350b2ba6daf69/google/firestore/v1/firestore.proto#L725), which means Listen can only be safely (consistency-wise) resumed from another Listen?

Another idea which would work for us: add [reponse_type](https://github.com/googleapis/googleapis/blob/03269e767cff9dd644d7784a4d4350b2ba6daf69/google/firestore/v1/firestore.proto#L581), which marks the points after catching up to the past (all changes where `updateTime < requestTime`) and actual new events. It's not resuming from arbitrary time, but it would still allow us to solve above-mentioned use cases.

**Comment by schmidt-sebastian** [comment]
Hi! Please do note that even the backend itself does not necessarily keep tombstones. If you have no listeners open while you delete a document, the backend will not know about the document's past when you do establish a listen. Unless we change this on the backend, you will have to manually maintain a list of tombstones.

As for your second question, you should be able to use the `readTime` that was returned from a RunQuery. You should keep the time interval short between reading the Query results and establishing the Listen to guarantee that the backed still has all necessary data.  Please note that deletes are not guaranteed to be re-played, instead the backend will return [the expected document count](https://github.com/googleapis/googleapis/blob/d542a0b27b6b8a6d3869c3919e53c61a63cc4cc3/google/firestore/v1/write.proto#L254). If your local count doesn't match, you have to restart the listen.

Due to the complexity of the Watch protocol, we generally do not recommend using it directly. We have spent considerable engineering resources making sure that all edge cases are addressed by our SDKs. If you intend to build your own Watch implementation, please take a close look at ours.

**Comment by marcin-ptaszynski** [comment]
Thanks @schmidt-sebastian , It seems allowed window between RunQuery and following List is <500ms. Which, considering latencies involved should work in most cases.

Thanks a lot for advice. I understand complexities involved and need to maintain indexed in-memory query result view, handling of RESETs, EXISTENCE_FILTERs, but that's the price of flexibility.

As for the other approach to solve this, do you think you could pass first CURRENT marker to library user in this library?

**Comment by schmidt-sebastian** [comment]
The SDK should not raise a snapshot before the target is marked CURRENT.

**Comment by marcin-ptaszynski** [comment]
I understand, thank you so much!
