### ISSUE TITLE
pubsub: wrong value name in documentation about PublishResult.Get(ctx context.Context)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [googleapis/google-cloud-go#1429]
https://github.com/googleapis/google-cloud-go/blob/75150fd6c7fabd65ebdb3ca10878f9f984a6f6e5/pubsub/topic.go#L369

But in return name I see `serverID`:
https://github.com/googleapis/google-cloud-go/blob/75150fd6c7fabd65ebdb3ca10878f9f984a6f6e5/pubsub/topic.go#L371

**Comment by broady** [comment]
I don't understand - what should it be?

**Comment by vitaly-zdanevich** [comment]
I am do not understand also...

**Comment by odeke-em** [comment]
Thank you for filing this issue @vitaly-zdanevich and perhaps I have an idea I know what is causing you confusion @vitaly-zdanevich:

@vitaly-zdanevich Go supports named return results https://golang.org/ref/spec#Function_types so that name "serverID" is just a symbolic name and doesn't change the type nor the meaning. What's important is that the ID is the one returned from the server.

I shall close this issue but please don't hesitate to ask any other questions or file issues. Thank you!

**Comment by vitaly-zdanevich** [comment]
But why different names? In documentation it called `message ID` but named return is `serverID`.
