### ISSUE TITLE
datastore: unflake TestIntegration_Project_TimestampStoreAndRetrieve 

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1479]
Seems to be failing all of CI's builds. Ex:

https://sponge.corp.google.com/target?id=dce6c43e-0487-40c9-84b7-f663f48dd712&target=tests&searchFor=&show=ALL&sortBy=STATUS

However, I was unable to repro locally. What the heck?

**Comment by odeke-em** [comment]
For posterity for those that don't have credentials to get to the first link
https://source.cloud.google.com/results/invocations/62283724-3717-41d6-88a6-e55c956427d5/targets/cloud-go-libraries%2Fgoogle-cloud-go%2Fcontinuous%2Fmaster/log

**Comment by odeke-em** [comment]
So, because we use the same key "foo" at
https://github.com/googleapis/google-cloud-go/blob/33e44727049b47d9454d9fca23d232182d7864dd/datastore/integration_test.go#L1289
and then when cleaning up
https://github.com/googleapis/google-cloud-go/blob/33e44727049b47d9454d9fca23d232182d7864dd/datastore/integration_test.go#L1293-L1297

This flake appears to be a result of concurrent builds/integration-tests going on Kokoro e.g. B1 starting at t1, B2 starting at t2 where
B1 is invoking https://github.com/googleapis/google-cloud-go/blob/33e44727049b47d9454d9fca23d232182d7864dd/datastore/integration_test.go#L1294

right as B2 is invoking  https://github.com/googleapis/google-cloud-go/blob/33e44727049b47d9454d9fca23d232182d7864dd/datastore/integration_test.go#L1301

One can try to simulate this by running with two terminals with the `go test -v -run=TestIntegration_Project_TimestampStoreAndRetrieve -count=250` and start the tests a little short of time after each other and mostly we'll see 
```shell
--- FAIL: TestIntegration_Project_TimestampStoreAndRetrieve (0.46s)
    integration_test.go:1308: expected 1 result, got 2
```
but theoretically that can happen.

A fix here is to auto-generate the test key with valid UTF-8, but time.Now().Unix() won't cut it concurrent build times coincide. CL coming up shortly.

**Comment by jadekler** [comment]
https://sponge.corp.google.com/target?id=294db945-86a6-4cfb-be5f-3e6ce222be6d&target=tests&searchFor=&show=ALL&sortBy=STATUS

![Screenshot from 2019-06-27 11-47-53](https://user-images.githubusercontent.com/3584893/60288472-79c43780-98d1-11e9-9f3e-568da26a7aca.png)

Seems to still be an issue :/

**Comment by IlyaFaer** [comment]
I've reproduced this error locally several times. It's really rare (fails once in a 10000 tests), so I didn't found the cause yet, but here is what I managed to find out (maybe someone will point me in a right direction, and will make things faster):

According to my logs, problem is in `Project()`, 'cause I've tried to log three queries (in this order):
```
q := NewQuery(keyName).Order("Created").Project("Created")
q2 := NewQuery(keyName).Order("Created")
q3 := NewQuery(keyName)
```
And it gave such a result:
```
[]
[{2019-09-12 19:59:47.351684 +0300 MSK}]
[{2019-09-12 19:59:47.351684 +0300 MSK}]
```
That means, that instance was created, but query with projection sometimes can't see it, ha!?

P.S. I've tried to add random hex portion to id (agreed with @odeke-em), but it still fails, and I've even reproduced it several times with just one test process.

![Без названия](https://user-images.githubusercontent.com/26030071/64846640-cc320c00-d615-11e9-9def-bf20e8528b02.png)
