### ISSUE TITLE
Spanner: TestHealthCheckScheduler is flaky

### ISSUE THREAD

**Issue by olavloite** [googleapis/google-cloud-go#1491]
--- FAIL: TestHealthCheckScheduler (17.95s)
	session_test.go:656: after 15s waiting, got got 95 healthchecks on session projects/[PROJECT]/instances/[INSTANCE]/databases/[DATABASE]/sessions/1, want it between (10, 30)

**Comment by odeke-em** [comment]
I just encountered this too during a Kokoro run on Go1.10:
https://source.cloud.google.com/results/invocations/7e0862c8-ceba-4c3a-944a-f7f15738d8dc/targets/tests/tests

```shell
2019/07/11 22:10:55 Failed to create session, error: spanner: code = "Canceled", desc = "context canceled"
session_test.go:656: after 15s waiting, got got 83 healthchecks on session projects/[PROJECT]/instances/[INSTANCE]/databases/[DATABASE]/sessions/1, want it between (10, 30)
```

**Comment by odeke-em** [comment]
@olavloite I think this issue still exists, I just encountered it while building off the latests on Go1.9

https://source.cloud.google.com/results/invocations/8455e0fe-bcd3-4383-b1fb-a2c3fec83dcd/targets/tests/tests for https://code-review.googlesource.com/c/gocloud/+/42550

**Comment by odeke-em** [comment]
False alarm!

**Comment by odeke-em** [comment]
@olavloite this one isn't a false alarm just encountered during a Kokoro run of CL https://code-review.googlesource.com/c/gocloud/+/42771 which contains the fix for this issue
<img width="762" alt="Screen Shot 2019-07-12 at 8 41 23 PM" src="https://user-images.githubusercontent.com/4898263/61166626-6e822600-a4e5-11e9-9552-4b80cb8b3a0f.png">

just produced https://source.cloud.google.com/results/invocations/89f296ab-1130-429e-9f1d-14077fde13cf/targets/tests/tests or inlined below

```shell
session_test.go:654: after 15s waiting, got got 96 healthchecks on session
projects/[PROJECT]/instances/[INSTANCE]/databases/[DATABASE]/sessions/5,
want it between (10, 30)
```

**Comment by olavloite** [comment]
@odeke-em Thanks for the report. I've been able to reproduce it locally and putting in a fix now for another possible scenario where the test could fail.
