### ISSUE TITLE
BucketHandler: Iterator for Objects

### ISSUE THREAD

**Issue by prannayk** [googleapis/google-cloud-go#1518]
The ObjectIterator returned by 

```golang
storage.BucketHandler.Objects(*context.Context, *storage.Query)
```
should be a Golang iterator so that we can the following loop on it:
```golang
for err, blob := bucket.Objects(ctx, nil) {
  // do something here
}
```

**Comment by jadekler** [comment]
The following,

```
for err, blob := bucket.Objects(ctx, nil) {
  // do something here
}
```

is not valid Go code. If you had meant, `for err, blob := range bucket.Objects(ctx, nil)`, that implies returning either a slice or channel. This would not be a good idea because it would involve pre-loading every single item beforehand. If you had 10,000 objects, waiting for the method to fetch all 10,000 objects would take a long time, rather than the current it.Next() behavior of lazy fetching.

All that aside, we can't change the interface because the package is stable. Therefore, closing this issue.

cc @frankyn
