### ISSUE TITLE
bigtable: multiple copies of same rowkey data are being saved

### ISSUE THREAD

**Issue by vasantivmahajan** [googleapis/google-cloud-go#1534]
I am writing to BigTable using the Go library. I use the ApplyBulk method to make multiple inserts. However, when I query BigTable using the ReadRows function I see multiple copies/versions with the same row key.

For instance: In the below-mentioned example, I see multiple copies of the same RowKey with partial data and the last occurrence has all the columns with all the fields.

![image](https://user-images.githubusercontent.com/17990840/63050390-fd99a980-bea8-11e9-8efe-2cf8faa4c4df.png)

How can I ensure that only a single copy of data is stored for each row key? And how can I fetch only the latest version of rows inserted?

Code:
```
row_range := bigtable.PrefixRange("")

err = tbl.ReadRows(ctx,row_range, func(row bigtable.Row) bool {
// logic goes here
}, bigtable.RowFilter(bigtable.LatestNFilter(1)))
```

**Comment by odeke-em** [comment]
Thank you for filing this issue @vasantivmahajan and welcome to the Google Cloud Go project!

It would be great if you could show a minimal reproducer with the code and data that you used for insertion not just the List code. That helps to debug the problem and figure out if/what's going wrong because that would highlight a clear bug, otherwise these libraries have been used for years without phantom duplication being reported.

**Comment by odeke-em** [comment]
Kindly pinging you again @vasantivmahajan, any luck with how to reproduce your scenario and help diagnose what's going wrong?

**Comment by odeke-em** [comment]
@vasantivmahajan please feel free to reopen this issue when you have the actionable code that can reproduce your issue.
