### ISSUE TITLE
Unflake TestAgentIntegration

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1568]
https://sponge.corp.google.com/target?id=86158bc8-c8e6-4949-9367-92a7474eea2f&target=cloud-go-libraries/google-cloud-go/continuous/go111&searchFor=&show=ALL&sortBy=STATUS

```
--- FAIL: TestAgentIntegration (0.01s)
    integration_test.go:146: using Git commit "32fa00377bdcfce7f307ebca24f5916048356e56" for the profiler integration test
    --- PASS: TestAgentIntegration/profiler-test-go11112 (261.10s)
    --- FAIL: TestAgentIntegration/profiler-test-gomaster (465.09s)
        integration_test.go:241: QueryProfilesWithZone(dulcet-port-762, profiler-test-gomaster-2019-09-06-09-14-28-144814-0700, 2019-09-06T15:22:11Z, 2019-09-06T16:22:11Z, CONTENTION, us-west1-b) got error: failed to query API: status: 404 Not Found, response body: {
              "error": {
                "code": 404,
                "message": "Requested entity was not found.",
                "status": "NOT_FOUND"
              }
            }
        integration_test.go:241: QueryProfilesWithZone(dulcet-port-762, profiler-test-gomaster-2019-09-06-09-14-28-144814-0700, 2019-09-06T15:22:11Z, 2019-09-06T16:22:11Z, HEAP_ALLOC, us-west1-b) got error: failed to query API: status: 404 Not Found, response body: {
              "error": {
                "code": 404,
                "message": "Requested entity was not found.",
                "status": "NOT_FOUND"
              }
            }
FAIL
```

**Comment by jqll** [comment]
The bench is set to run 150s, not all profile types get profiled during the time, because the deployment is moved to another bridge task. I'll increase the bench time.

Log:
Fri Sep  6 16:19:30 UTC 2019: + go run busybench.go --service=profiler-test-gomaster-2019-09-06-09-14-28-144814-0700 --mutex_profiling=true
Fri Sep  6 16:19:31 UTC 2019: 2019/09/06 16:19:31 busybench using devel +b1a20253fe Fri Sep 6 12:16:32 2019 +0000.
Fri Sep  6 16:19:31 UTC 2019: 2019/09/06 16:19:31 Stackdriver Profiler Go Agent version: 20190802
Fri Sep  6 16:19:31 UTC 2019: 2019/09/06 16:19:31 profiler has started
Fri Sep  6 16:20:35 UTC 2019: 2019/09/06 16:20:35 successfully created profile CPU
Fri Sep  6 16:20:45 UTC 2019: 2019/09/06 16:20:45 start uploading profile
Fri Sep  6 16:20:52 UTC 2019: 2019/09/06 16:20:52 failed to upload profile: rpc error: code = InvalidArgument desc = Request contains an invalid argument.
Fri Sep  6 16:21:29 UTC 2019: 2019/09/06 16:21:29 successfully created profile THREADS
Fri Sep  6 16:21:29 UTC 2019: 2019/09/06 16:21:29 start uploading profile
Fri Sep  6 16:21:30 UTC 2019: 2019/09/06 16:21:30 successfully created profile CPU
Fri Sep  6 16:21:40 UTC 2019: 2019/09/06 16:21:40 start uploading profile
Fri Sep  6 16:21:49 UTC 2019: 2019/09/06 16:21:49 successfully created profile HEAP
Fri Sep  6 16:21:49 UTC 2019: 2019/09/06 16:21:49 start uploading profile
Fri Sep  6 16:22:01 UTC 2019: 2019/09/06 16:22:01 busybench finished profiling.

**Comment by jqll** [comment]
Should be fixed by https://github.com/googleapis/google-cloud-go/commit/f8deca375cd9d09ceb90b71ed939bdd18df1b2a3
