### ISSUE TITLE
Spanner: unflake TestIntegration_DbRemovalRecovery

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1571]
https://source.cloud.google.com/results/invocations/d2cad416-31ba-41da-8cb1-2eac5a708b48/targets

https://sponge.corp.google.com/invocation?tab=Build+Log&id=d2cad416-31ba-41da-8cb1-2eac5a708b48&searchFor=

```
Failed
integration_test.go:893: failed to send query to database projects/dulcet-port-762/instances/go-integration-test/databases/gotest_1568136232283291228_09: spanner: code = "DeadlineExceeded", desc = "context deadline exceeded, lastErr is <rpc error: code = DeadlineExceeded desc = context deadline exceeded>"
integration_test.go:2317: failed to drop database projects/dulcet-port-762/instances/go-integration-test/databases/gotest_1568136232283291228_09 (error context deadline exceeded), might need a manual removal
```

**Comment by olavloite** [comment]
This specific issue is no longer relevant, as we now create a new instance for each test run, and at the end of the test run delete the entire instance instead of individual databases. A test instance that fails to be deleted at the end of a test run, will be cleaned up automatically by subsequent test runs once they are more than 24 hours old (see https://github.com/googleapis/google-cloud-go/blob/20091f47d3c522ea545f358dd9ac1cdb326bba6f/spanner/integration_test.go#L2481).
