### ISSUE TITLE
firestore: does not work well with protobuf generated files

### ISSUE THREAD

**Issue by pauldemarco** [googleapis/google-cloud-go#1601]
The protobuf generator has no ability to add the custom `firestore` struct tags needed by the lib to properly convert toValue:

```go
// City represents a city.
type City struct {
        Name       string   `firestore:"name,omitempty"`
        State      string   `firestore:"state,omitempty"`
}
```

It does although generate `json` struct tags, and as a quick hack I changed to_value.go to look for these tags instead: https://github.com/pauldemarco/google-cloud-go/commit/fd0708b92864f7914e15e47945659ac729c5e1b4

It works great but very much just a band-aid fix.

Would it be possible to expose this configuration, perhaps during initialization of the client?

**Comment by jadekler** [comment]
Could you describe what you mean by `The protobuf generator`? Are you describing `protoc`?

**Comment by pauldemarco** [comment]
Yes, sorry. I’m referring to ‘protoc’ with the ‘go_our’ argument

**Comment by jadekler** [comment]
Gotcha! I don't think that's a feature we can support, since it's a `protoc` feature request, and I don't think it's something they can support, since it's a GCP-specific thing (and protoc is not GCP specific).

It is pretty annoying, though. We should have docs or some helper to work with .pb.gos. Classifying this as feature request and we'll noodle on this.

cc @schmidt-sebastian, any thoughts here?

**Comment by schmidt-sebastian** [comment]
Sorry - I don't have any relevant input here.

**Comment by pauldemarco** [comment]
I ended up creating a post-generation script that added in the needed `firestore` struct tags based on the already existing `protobuf` struct tag.
