### ISSUE TITLE
pubsub: anonymous request gets stuck

### ISSUE THREAD

**Issue by yolocs** [googleapis/google-cloud-go#1626]
## Client

PubSub

## Describe Your Environment

I created a pubsub client and trying to check if a topic exists anonymously.

```
package main

import (
	"context"
	"log"

	"cloud.google.com/go/pubsub"
	"google.golang.org/api/option"
	"google.golang.org/grpc"
)

func main() {
	ctx := context.Background()
	client, err := pubsub.NewClient(ctx, "my-example-project", option.WithoutAuthentication(), option.WithGRPCDialOption(grpc.WithInsecure()))
	if err != nil {
		log.Fatal(err)
	}

	topic := client.Topic("my-example-topic")
	exists, err := topic.Exists(ctx) // this call never returns, it just stuck here.
	if err != nil {
		log.Fatal(err)
	}
	if !exists {
		log.Print("Topic doesn't exist")
		return
	}
}

```

## Expected Behavior

If I have `allUsers` as `Pub/Sub Admin`, it should return `exists = true` as my topic does exist.
If my topic is private, it should return error saying permission denied.

## Actual Behavior

`topic.Exists` never return and just stuck there.

**Comment by hongalex** [comment]
Hi,

Thanks for reporting this issue. Cloud Pub/Sub does not support unauthenticated requests. The error code that the request returns is continuously retried, which is why the request is hanging.

The method you actually want to call looks like `client.TopicInProject("my-example-topic", "my-example-project")`, while authenticating with a Google Cloud project ID that you own.
