### ISSUE TITLE
bigquery: retry `timeout` errors?

### ISSUE THREAD

**Issue by yields** [googleapis/google-cloud-go#1627]
## Client

BigQuery

## Describe Your Environment

Alpine, K8S

## Expected Behavior

`(*Inserter).Put()` retries temporary errors indefinitely.

## Actual Behavior

Put() returns a multi error that contains `Reason: Timeout`:

```
bigquery: insertion of row [insertID: "<masked>"; insertIndex: 0] failed with error: {Location: ""; Message: ""; Reason: "timeout"},insertion of row [insertID: "<masked>"; insertIndex: 2] failed with error: {Location: ""; Message: ""; Reason: "timeout"},insertion of row [insertID: "<masked>"; insertIndex: 3] failed with error: {Location: ""; Message: ""; Reason: "timeout"},insertion of row [insertID: "<masked>"; insertIndex: 4] failed with error: {Location: ""; Message: ""; Reason: "timeout"}
```

**Comment by shollyman** [comment]
Put leverages an incremental backoff and a retry strategy with a finite number of retries.   Unbounded retries is a generally bad idea.

**Comment by yields** [comment]
Agreed they're a bad idea in general, but the docs for [`(*Inserter).Put()`](https://github.com/googleapis/google-cloud-go/blob/master/bigquery/inserter.go#L92-L94) seem to suggest that `Put()` will run indefinitely if the error is temporary.

You're suggesting they're retried but not indefinitely?

**Comment by shollyman** [comment]
Went back and reviewed this retry strategy in more detail.  In go, we use the context for bounding the retries, and evaluate a combination of http responses and fields in the structured error responses to determine whether or not to retry.  Currently the "timeout" structured error reason isn't in the list of errors upon which we retry.

Just to confirm, what's the batch size you're sending when you perform a put?  The response indicates this a batch size of 5, but it's unclear if the response is truncated in this situation.  I ask because a very large batch size may never successfully retry, which is partly the reason this isn't the retry list by default.  It may make sense to define an alternative retry policy for this method.

**Comment by yields** [comment]
> Just to confirm, what's the batch size you're sending when you perform a put?

We have various workers writing to bigquery with different batch sizes:

```
50 // => small rows
1  // => large rows, this is still in development
10 // => most writers use this batch size
```

> Currently the "timeout" structured error reason isn't in the list of errors upon which we retry.

Gotcha, this makes sense, in our writers we added those helper functions to check if an error is temporary and in need of a retry:

```go
// IsTemporary returns true if the given error is temporary.
func isTemporary(err error) bool {
	t, ok := err.(interface{ Temporary() bool })
	return (ok && t.Temporary()) || isTimeout(err)
}

// IsTimeout returns true if the given error is a timeout.
func isTimeout(err error) bool {
	t, ok := err.(interface{ Timeout() bool })
	return ok && t.Timeout()
}
```

Maybe the docs should be updated?

**Comment by IlyaFaer** [comment]
@yields, I suspect you can use these functions to be in touch with true BigQuery retry policies:
https://github.com/googleapis/google-cloud-go/blob/94f5c300024dc51e3bca2d75e41e79311fe3684f/bigquery/bigquery.go#L122-L156
