### ISSUE TITLE
unflake TestIntegration_UpdateRetentionPolicy

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1632]
https://sponge.corp.google.com/target?id=a8d868bf-56bf-4ede-972f-48bbf660a9ba&target=cloud-go-libraries/google-cloud-go/continuous/go112&searchFor=&show=ALL&sortBy=STATUS

```
=== RUN   TestIntegration_UpdateRetentionPolicy
--- FAIL: TestIntegration_UpdateRetentionPolicy (19.96s)
    integration_test.go:2974: integration_test.go:2508: update: googleapi: Error 429: The project exceeded the rate limit for creating and deleting buckets., rateLimitExceeded
```

**Comment by odeke-em** [comment]
I believe the error exorcises the problem in 
`Error 429: The project exceeded the rate limit for creating and deleting buckets., rateLimitExceeded`
because in that test we are creating and deleting a bucket on every single sub-test yet all we are doing is just updating the retention policy.
The quota for creating and deleting buckets is very low aka 1 operation every 2 seconds, as per
https://cloud.google.com/storage/quotas#buckets
![Screen Shot 2020-04-17 at 5 09 29 PM](https://user-images.githubusercontent.com/4898263/79622915-4526a400-80ce-11ea-942e-f708f7d40791.png)
and if those subtests run for say 300 milliseconds, we'll hit the limit ASAP.

I think what we can do is:
a) Create a single bucket, on exiting the test delete it
b) On deferring each subTest, reset the retention policy to initial

That'll ensure that the retention policy conditions are set to the same level playing field for each test and then also sleep for a bit after each subTest runs since the quota for bucket updates is 1 per second.

**Comment by odeke-em** [comment]
I've mailed https://code-review.googlesource.com/c/gocloud/+/55031 to deflake this test.

**Comment by tritone** [comment]
Fix didn't work correctly in Kokoro:
```
=== RUN   TestIntegration_UpdateRetentionPolicy
    TestIntegration_UpdateRetentionPolicy: integration_test.go:2641: input: <nil>
        got=-, want=+:
          (*storage.RetentionPolicy)(
        - 	nil,
        + 	&{RetentionPeriod: s"1m0s"},
          )
--- FAIL: TestIntegration_UpdateRetentionPolicy (7.98s)
```

Reverted and re-opening this issue.
