### ISSUE TITLE
fix TestIndefineRetries

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1641]
Seems to fail 100% of the time.

https://sponge.corp.google.com/target?id=e2310717-c236-45d3-918a-180fe6bf5d94&target=cloud-go-libraries/google-cloud-go/continuous/go113&searchFor=&show=ALL&sortBy=STATUS

```
=== RUN   TestIndefiniteRetries
panic: test timed out after 30m0s

goroutine 992 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1377 +0x11c
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x52

goroutine 1 [chan receive, 28 minutes]:
testing.(*T).Run(0xc00026e400, 0xed5a4a, 0x15, 0xefd1c0, 0x1)
	/usr/local/go/src/testing/testing.go:961 +0x68a
testing.runTests.func1(0xc00026e400)
[...]
```

**Comment by tritone** [comment]
Started failing yesterday; I will take a look.

**Comment by IlyaFaer** [comment]
Looks like the main problem is the endless loop in here:
https://github.com/googleapis/google-cloud-go/blob/9f47821ebd7e01e6ff3fa65f57dcd8afe59e2e57/storage/retry_test.go#L150-L154
Returned `n` is always 0, so `i` keeps it's value and never getting equal or bigger than `maxFileSize`. Thus, after test timeout reached, it fails. Seems to me the root of the problem lies in this sentense:
https://github.com/googleapis/google-cloud-go/blob/9f47821ebd7e01e6ff3fa65f57dcd8afe59e2e57/storage/retry_test.go#L65
In fact, there are two variants of the string prefix, which are designated here:
https://github.com/googleapis/google-api-go-client/blob/4d1651bea54a431b282016982e1fa6717db1ba12/storage/v1/storage-gen.go#L10020-L10024

If prefix is `/upload/storage/v1/b/` not just `/b/`, requests are always failing with `404 Unimplemented`, which is the default:
https://github.com/googleapis/google-cloud-go/blob/9f47821ebd7e01e6ff3fa65f57dcd8afe59e2e57/storage/retry_test.go#L118-L120
(by the way, write error is never checked).

I'm going to push Cl with fix (and small refactor) shortly.

**Comment by tritone** [comment]
This had a flake last week: https://sponge.corp.google.com/target?id=03a58bd1-b87c-4a7f-a4fc-8d8448d9c502&target=cloud-devrel/client-libraries/go/google-cloud-go/continuous/go111&searchFor=&show=ALL&sortBy=STATUS

`=== RUN   TestIndefiniteRetries
--- FAIL: TestIndefiniteRetries (0.67s)
    retry_test.go:168: Got error (EOF) of type *errors.errorString, expected *googleapi.Error`

@IlyaFaer could you take a look?

**Comment by IlyaFaer** [comment]
@tritone, sure

**Comment by IlyaFaer** [comment]
Looks like sometimes test server is getting request with a content range like `*/bytes_len`. Because of this lines:
https://github.com/googleapis/google-cloud-go/blob/ad7cd32b39df6e142b24ab86b2cda03f21e1d708/storage/retry_test.go#L188-L195
server decides that uploading is successfully complete. I suppose primordially it was planned that such a requests will be causing server to return `TooManyRequests` here:
https://github.com/googleapis/google-cloud-go/blob/ad7cd32b39df6e142b24ab86b2cda03f21e1d708/storage/retry_test.go#L200-L204
And here:
https://github.com/googleapis/google-cloud-go/blob/ad7cd32b39df6e142b24ab86b2cda03f21e1d708/storage/retry_test.go#L95-L100
But because of `prelude == "*"` sentence server never comes to `spamThem = True`. I've tried to move this statements before the `prelude == "*"`, and seems it works fine: test didn't failed during 10 hours of testing, while previously it was failing at least once every 20 min (locally). Pushing now a Cl.
