### ISSUE TITLE
spanner: broken tests

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-go#1738]
https://code-review.googlesource.com/c/gocloud/+/50511 was submitted today, and it appears to have declared the same test method twice, causing presubmit breakages elsewhere.

Failed ./client_test.go:664:6: TestClient_ReadOnlyTransaction_SessionNotFoundOnExecuteStreamingSql redeclared in this block 	previous declaration at ./client_test.go:588:77

**Comment by shollyman** [comment]
Submitted https://code-review.googlesource.com/c/gocloud/+/50690 as a quick fix.

**Comment by olavloite** [comment]
The problem occurred because two different CL's that were developed in parallel both added the same test case. The test was added in both https://code-review.googlesource.com/c/gocloud/+/50510 and https://code-review.googlesource.com/c/gocloud/+/50511. 50510 was merged first, and 50511 was merged somewhat later, but without first rebasing it on master, which would have caught this.

The test in both CL's do the same, so picking any of them was the right choice.
