### ISSUE TITLE
pubsub: add support for dead letter topics

### ISSUE THREAD

**Issue by hongalex** [googleapis/google-cloud-go#1762]
Add fields necessary to create/update subscriptions with a dead letter policy. This allows messages to be redelivered to a separate dead letter topic after a configured number of
delivery attempts have failed (nack/ack_deadline expired).

In addition, change Message.DeliveryAttempt to be `nil` when the subscription does not have dead lettering enabled.

**Comment by Rossiar** [comment]
@hongalex if I implement this feature and submit a PR following https://github.com/googleapis/google-cloud-go/blob/master/CONTRIBUTING.md would you accept it?

**Comment by hongalex** [comment]
Hiya, this is actually available since `cloud.google.com/go/pubsub v1.4.0`. Did you mean another feature? In any case, thanks!

**Comment by Rossiar** [comment]
Sorry on first glance I thought that this issue was directly against `pstest` - I am using pstest to mock pubsub and trying to test adding/updating a dead letter policy on a subscription. I was receiving the error ["unknown field dead_letter_policy"](https://github.com/googleapis/google-cloud-go/blob/master/pubsub/pstest/fake.go#L462) - so I was offering to implement this in `pstest`.

**Comment by hongalex** [comment]
Ah yeah, if you would be willing to help support this in `pstest`, I'd be happy to review it and help you get it merged in.
