### ISSUE TITLE
storage: resumable upload backoff doesn't follow documentation

### ISSUE THREAD

**Issue by xaurx** [googleapis/google-cloud-go#1797]
**Client**

Object Storage Client (1.5.0)

**Environment**

Alpine Docker on GKE

**Code**

```go
package main

func main() {
wc := gs.bucket.Object(path).NewWriter(ctx)
wc.ContentType = contentType
wc.ChunkSize = chunkSize // 128MB
 _, err  = io.Copy(wc, data)
// check err
err = wc.Close()
}
```

**Expected behavior**

According to documentation:
> Retrying continues indefinitely unless the controlling context is canceled or the client is closed.

**Actual behavior**

Only 32 seconds are given to single chunk upload in resumable mode. As a result we see errors like:
"googleapi: got HTTP response code 503 with body: "
Note, 503 error is retried according to ResumableUpload.Upload() code.

**Additional context**

Resumable upload is done via this call chain:

google.golang.org/api@v0.15.0/storage/v1/storage-gen.go: 
     ObjectsInsertCall.Do()
google.golang.org/api@v0.15.0/internal/gensupport/resumable.go:
     ResumableUpload.Upload()

Last function has:
        quitAfter := time.After(retryDeadline)
where 
        retryDeadline = 32 * time.Second

Ideally we need a Retry callback function which would decide whether error is retriable and Backup function to control backoff parameters.

**Comment by odeke-em** [comment]
@xaurx thank you for filing this bug and welcome to the google-cloud-go project!

Indeed, we changed this behavior in release v0.45.0 of cloud.google.com/go/storage and particularly in issue https://github.com/googleapis/google-cloud-go/issues/1507 because 503s were getting retried indefinitely and causing timeouts. Perhaps we can update the documentation otherwise your code can get stuck in limbo and there is a very grey area on where 503s are retryable or not.

Here is a repro with a mock GCS server  (but running on Go1.14 and above),that can you can use to verify that the change happened
```go
package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"net/url"
	"time"

	"cloud.google.com/go/storage"
	"google.golang.org/api/option"
)

type alwaysToTargetURL struct {
	targetHost string
	base       http.RoundTripper
}

func (au *alwaysToTargetURL) RoundTrip(req *http.Request) (*http.Response, error) {
	req.URL.Host = au.targetHost
	return au.base.RoundTrip(req)
}

func main() {
	mockGCS := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/b/bucket/o/object":
			fmt.Fprintf(w, `{
                            "bucket": "bucket", "name": "name","contentLength": 100,
                            "contentType": "text/plain","timeCreated": "2020-04-10T16:08:58-07:00"
                        }`)
			return
		default:
			http.Error(w, "Failing purposefully", 503)
			return

			blob, err := ioutil.ReadAll(r.Body)
			if err != nil {
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}
			fmt.Fprintf(w, `{
                            "bucket": "bucket", "name": "name","contentLength": 100,
                            "contentLength": %d,"contentType": "text/plain",
                            "timeCreated": "2020-04-10T16:08:58-07:00"
                        }`, len(blob))
		}
	}))
	mockGCS.EnableHTTP2 = true
	mockGCS.StartTLS()
	defer mockGCS.Close()

	targetURL, _ := url.Parse(mockGCS.URL)

	ctx := context.Background()
	hc := mockGCS.Client()
	hc.Transport.(*http.Transport).TLSClientConfig.InsecureSkipVerify = true
	hc.Transport = &alwaysToTargetURL{
		targetHost: targetURL.Host,
		base:       hc.Transport,
	}

	client, err := storage.NewClient(ctx, option.WithoutAuthentication(),
		option.WithHTTPClient(hc))
	if err != nil {
		panic(err)
	}
	defer client.Close()

	startTime := time.Now()
	defer func() {
		if r := recover(); r != nil {
			fmt.Printf("\033[32mRecovered from a panic after: %v\033[00m\n", time.Since(startTime))
			panic(r)
		}
	}()

	ctx, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()

	wc := client.Bucket("bucket").Object("object").NewWriter(ctx)
	wc.ContentType = "text/plain"
	if _, err := wc.Write([]byte("Whatever will be")); err != nil {
		panic(err)
	}
	if err := wc.Close(); err != nil {
		panic(err)
	}
}
```

### Results
For each of those tags, please go to $GOPATH/src/cloud.google.com/go/storage and then run `git checkout <tag>`

#### v0.45.0 and above aka current at v0.56.0: times out fast
```shell
$ GO111MODULE=off go run main.go 
Recovered from a panic after: 3.066518ms
panic: googleapi: got HTTP response code 503 with body: Failing purposefully
 [recovered]
	panic: googleapi: got HTTP response code 503 with body: Failing purposefully


goroutine 1 [running]:
main.main.func2(0xbf9e5b474caf9ab8, 0x43a7c5, 0x1bf0240)
	/Users/emmanuelodeke/Desktop/openSrc/bugs/google-cloud-go/1797/main.go:76 +0x111
panic(0x15e8a40, 0xc000094910)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:969 +0x166
main.main()
	/Users/emmanuelodeke/Desktop/openSrc/bugs/google-cloud-go/1797/main.go:89 +0x821
exit status 2
```

#### v0.44.0 and below: retries indefinitely
```shell
$ GO111MODULE=off go run main.go 
Sleeping for 947.779411ms
Sleeping for 1.082153552s
Sleeping for 3.666145822s
Sleeping for 2.235010052s
Sleeping for 287.113938ms
Sleeping for 4.549167321s
Sleeping for 17.632969759s
Sleeping for 7.331776149s
Sleeping for 29.183117217s
Sleeping for 480.27945ms
Sleeping for 760.398085ms
Sleeping for 14.263669288s
Sleeping for 20.884491575s
Sleeping for 5.414458837s
Sleeping for 1.211445516s
Sleeping for 23.838182874s
Recovered from a panic after: 2m0.003023143s
panic: context deadline exceeded [recovered]
	panic: context deadline exceeded

goroutine 1 [running]:
main.main.func2(0xbf9e5bae081bfd20, 0x3fbcf3, 0x1bee240)
	/Users/emmanuelodeke/Desktop/openSrc/bugs/google-cloud-go/1797/main.go:76 +0x111
panic(0x1624ac0, 0x1c18d20)
	/Users/emmanuelodeke/go/src/go.googlesource.com/go/src/runtime/panic.go:969 +0x166
main.main()
	/Users/emmanuelodeke/Desktop/openSrc/bugs/google-cloud-go/1797/main.go:89 +0x821
exit status 2
```

### Remedy
Given that with a 503, the upload could be stuck forever as seen in the linked issue that was escalated and that we handled by removing retries in the client itself but leaving those in the underlying uploader. 
I think indeed as you recommended, we should have a way for the caller to decide what's retryable given an error as well as the current backoff.

What do y'all think @tritone @tbpg @frankyn @broady?

**Comment by odeke-em** [comment]
But firstly I'd say let's update the documentation to reflect the removal of the 503 indefinite retries.

**Comment by dsymonds** [comment]
I managed to come across this issue trying to figure out why we've been getting more GCS write failures in our project, and I am a little baffled why the change was made. The big appeal of having a client library is that the library takes care of a bunch of the nuisance work, and one of those is retrying retryable failures, but it sounds like you've deliberately removed that and are forcing users of this library to do that themselves. Is that right?

I can very easily add timeouts and the like to my own code (and already do for other reasons), but adding retries in all the relevant places is a giant pain. I'd much rather see the change that was made in aid of #1507, or at least have a storage.Client option to get the prior behaviour.

**Comment by tritone** [comment]
To clarify, the change that was made for #1507 fixed a case where incorrect retry behavior might cause an infinite loop, but left an edge case under which certain 503s on writes might not be retried.

I definitely agree that this is not good behavior and making a change to the docs is not really helping matters. I actually received another complaint about this recently and just started working on a fix. It's a little complex because it is going to require a change in the generated layer (see googleapis/google-api-go-client#392 ) but we hope to get this done soon.

**Comment by tritone** [comment]
As of the most recent release (storage/v1.10.0) I've made changes to fix googleapis/google-api-go-client#392 , which means the initial request to set up a resumable upload (as well as the overall request for multipart uploads, assuming buffering is available) will now be retried until the context deadline for retryable errors.  For the subsequent chunk uploads, the 32s per chunk limit still applies (to avoid the situation @odeke-em referenced in #1507).

I think this could potentially go a long way toward mitigating these sorts of issues-- in another workflow I looked at, many failures for writes were due to this rather than the per-chunk limit.

@dsymonds @xaurx could you let me know how things look for your workflow with the new release?

**Comment by dsymonds** [comment]
We updated to storage/v1.10.0 on 19 June, and haven't seen a 503 backendError since then. It's hard to tell, since they were fairly sporadic anyway, but I'm cautiously optimistic. Thanks!

**Comment by tritone** [comment]
@dsymonds thanks for following up, much appreciated!

I'm going to close this issue for now, but feel free to re-open if you see a recurrence of this problem (same to you @xaurx ).
