### ISSUE TITLE
profiler: unable to specify rhythm

### ISSUE THREAD

**Issue by noamhurwitz** [googleapis/google-cloud-go#1803]
**Is your feature request related to a problem? Please describe.**
I wish to be able to decrease the sampling rate of the profiler to reduce overhead.

**Describe the solution you'd like**
An option in the API via this config [1] to allow the client to specify the profiling rhythm.

[1] https://godoc.org/cloud.google.com/go/profiler#Config

**Describe alternatives you've considered**
None

**Additional context**
Per the docs here [2], "[c]alling Start will start a goroutine to collect profiles and upload to the profiler server, at the rhythm specified by the server". At first I was under the impression that "the server" is the application server, but it seems upon further inspection that it is the profiling server. The wording is a bit easy to misinterpret, and I think it would be a great value add to be able to configure profiling rhythm for debugging and performance reasons.

[2] https://godoc.org/cloud.google.com/go/profiler

**Comment by tbpg** [comment]
@jqll, any thoughts on this?

**Comment by jqll** [comment]
+ @kalyanac.
I don't think we plan to support customized profiling rhythm. The profiling shouldn't add any noticeable performance overhead. Please let us know if you notice such a case. Do you have a specific debugging scenario where a customized profiling rhythm can help?

**Comment by noamhurwitz** [comment]
It's showing up as intensive in some of our profiles but we also don't have much live traffic yet. That said - particularly for heap allocations - it seems non-negligible. We have one service where it's using >30% of heap space and that's with some traffic. 

I can also see situations in which we'd want to push a staged binary and sample 100% of profiles to get a clearer image of resource usage when A/B testing or trying to identify regressions. I think similar to stackdriver tracing, the client should be able to control the frequency of polling both to toggle up and toggle down depending on the need.

**Comment by noamhurwitz** [comment]
@jqll to provide more concrete data: 
we have a service serving 80QPS, and the profiler is actually accounting for 42% of allocated heap space (6.2MB/14MB) and 10% of used heap space (800KB/7.7MB) both of which seems high. We plan on ramping up past 80QPS but the heap alloc in particular seems high enough for us to want to tone down profiles collected.

**Comment by kalyanac** [comment]
@noamhurwitz 

Yes, the Profiler backend controls the collection interval. See here for [details](https://cloud.google.com/profiler/docs/concepts-profiling#collection). Users cannot change the profiling rhythm. The backend maintains it to achieve a certain sampling rate. 

As you go live, do you expect the service memory consumption to go up as well? In that case, the relative numbers for the agent would be much lower. On an idle service or low traffic service, its not unexpected to see the agent have a higher relative value. The agent is performing work in the background and not idle. 

I would suggest that you check the heap usage with service under a realistic load. We don't expect the agent to consume memory relative to the load on the system.

How many instances of your app is profiler agent enabled on? If its only one, then the backend is collecting profiles from only that instance of the app at the intervals as detailed in the documentation above, which is roughly once per minute. If you have enabled it on multiple instances with realistic load, the aggregate overhead will be much lower because a different instance will be used for profile collection at each attempt.

**Comment by noamhurwitz** [comment]
I see, thanks for the explanation. I'll close this for now.
