### ISSUE TITLE
Spanner: Expose methods via interfaces

### ISSUE THREAD

**Issue by pgmitche** [googleapis/google-cloud-go#1818]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I'm frustrated when trying to write effective unit tests for code that interacts with spanner. I expect to be able to mock the interaction, interfaces would enable this easily. Spannertest (https://github.com/googleapis/google-cloud-go/tree/master/spanner/spannertest) is missing many features/is incomplete, as such it is not a viable alternative

**Describe the solution you'd like**
_A clear and concise description of what you want to happen. What should the API be? How would you use it?_

The API operations should be exposed with the use of interfaces rather than with concrete structs, for example:

An interface for a spanner row iterator
```go
type RowIterator interface {
	Stop()
	Next() (*spanner.Row, error)
	Do(func(*spanner.Row) error) error
}
```

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

I've made use of both 'Handy Spanner' and spanner test, both are larger solutions to a different problem and aren't as simple as providing an interface as a solution

**Additional context**
Using Spanner in an enterprise solution, wish it's testability was better, would provide us more confidence in our tooling

**Comment by skuruppu** [comment]
Assigning to @hengfengli for further follow-up.

I am wondering whether some of the [testutils](https://github.com/googleapis/google-cloud-go/tree/master/spanner/internal/testutil) provided are useful or not.

Also, it would be good if you can elaborate on why spannertest is not sufficient so that we can improve it.

**Comment by codyoss** [comment]
In general in Go, the sentiment is to accept interfaces and return structs. Here are some reasons for why:

1. This allows us, the maintainers of the api, to make backwards compatible changes to the things our apis return. You can add a method to a struct without breaking backwards compatibility, but you can't do the same for an interface.
2. In general it is better for callers to define the interfaces in Go. This is possible because unlike other programming languages that make interface declaration explicit, Go has implicit interfaces. This makes it easy for callers to declare an interface and wrap an api, exposing just the methods they need for their code.

Not saying this should always be the case, but it is a good guideline to follow for the most part.

**Comment by pgmitche** [comment]
@skuruppu 

When initially attempting to write unit tests for the code integrating with spanner, on face value spannertest was not going to be sufficient. For one, we are using `JOIN`s in our queries, and this is explicitly not supported.

Later, I made use of my own interfaces and wrapper structs, along with gomock, to override the iterator returned in some queries with a canned iterator generated from spannertest.

An example:

A dodgy setup for getting by RowIterator with prepared data
```go
func loadAndReadTestData(ctx context.Context, expectedTable string, t *testing.T, cols []string, data [][]interface{}, client *spanner.Client) RowIterator {
	table := strings.ReplaceAll(expectedTable, "/", "_")
	mtns := make([]*spanner.Mutation, len(data))
	for i, row := range data {
		mtns[i] = spanner.InsertOrUpdate(table, cols, row)
	}
	_, err := client.Apply(ctx, mtns)
	require.NoError(t, err)
	//nolint:gosec
	return client.Single().Query(ctx, spanner.NewStatement(`SELECT `+strings.Join(cols, ",")+` FROM `+table))
}
```

And a snippet of it's usage where I've circumvented the issue of the {example statement} containing JOIN keywords (not supported by spannertest) by using gomock.
```go
cannedIterator := loadAndReadTestData(ctx, {tablename}, t, test.columns, test.data, testClient)

mockClient := NewMockClient(ctrl)
gomock.InOrder(
	mockClient.EXPECT().Read(ctx, {example statement}).Return(cannedIterator),
)
```

The issue is less that "spannertest isn't ready" and more that none of that would be required at all if interfaces were provided

**Comment by dsymonds** [comment]
The general design of the library is to provide concrete types, which allow for expansion over time. This is what @codyoss's first point is getting at. See also https://github.com/golang/go/wiki/CodeReviewComments#interfaces.

It is quite straightforward to define an interface in calling code, with a little wrapper implementation that invokes the real spanner client library, and then your test can mock out your own interface. That won't get broken if the client library is changed (e.g. if RowIterator gets some new methods).

**Comment by pgmitche** [comment]
>It is quite straightforward to define an interface in calling code, with a little wrapper implementation that invokes the real spanner client library, and then your test can mock out your own interface.
@codyoss This is currently how I'm handling this, if this is the suggested solution, I'm happy to close off the issues

> https://github.com/golang/go/wiki/CodeReviewComments#interfaces.
This is a good resource, thankyou.
