### ISSUE TITLE
pubsub: Synchronous batches limited to max parallel receive of 1

### ISSUE THREAD

**Issue by fastest963** [googleapis/google-cloud-go#1871]
**Client**

PubSub (latest)

**Environment**

CentOS 7 on GCE 

**Code**

```go
sub.ReceiveSettings.Synchronous = true
```

**Expected behavior**

A single batch of received messages can be processed in parallel.

**Actual behavior**

If `Synchronous` is true then the `ReceiveScheduler` gets created with `workers = 1` which then causes a single receive batch to process a single message at a time:
```
if key == "" {
	// Spawn a worker.
	s.workers <- struct{}{}
	go func() {
		// Unordered keys can be handled immediately.
		handle(item)
		<-s.workers
	}()
	return nil
}
```
whereas the old code would do:
```
for i, msg := range msgs {
...
wg.Add(1)
go func() {
	defer wg.Done()
	f(ctx2, msg)
}()
}
```

I'm not sure the best way to fix this since the previous behavior wasn't explicitly defined. Before `NumGoroutines` didn't alter the number of goroutines that call the callback to `Receive` it just adjusted the internal number of receiving goroutines. Now it adjusts both. I think there are a few solutions:
1. A new knob should be added to control the max parallel messages
2. The old behavior should be restored and ReceiveScheduler shouldn't limit the number of goroutines
3. `Synchronous = true`  shouldn't trigger `ReceiveScheduler(workers = 1)`

**Additional context**

Started after 09ba3f8614bab8557260ba47b7bd3a7ec711991a

This is important to us because we bundle messages in order to reduce the number of insertions we make into Bigtable but this change negates that bundling because we can never receive more than 1 message at a time.

We were previously instructed to set `Synchronous = true` to workaround expired issues https://github.com/googleapis/google-cloud-go/issues/1485#issuecomment-534313378.

@jadekler @hongalex

**Comment by hongalex** [comment]
Thank you very much for bringing this to our attention!

Indeed, the number of Receive callbacks should _not_ be directly dependent on `NumGoroutines`, and this was added in error. Previously, flow control was the limiting factor for how many simultaneous callbacks can exist, so I'll be sending out a change to revert to that behavior.
Specifically, you will be able to control how many callback goroutines you want with `MaxOutstandingMessages`. This is not a complete solution, since you might eventually want to limit callback threads to fewer than `MaxOutstandingMessages`, but we are looking into that 
separately.

**Comment by fastest963** [comment]
@hongalex thanks for the quick reply! What you said makes complete sense and we actually already use `MaxOutstandingMessages`, but I somehow forgot to mention that in my issue as an option.

**Comment by hongalex** [comment]
Fixed in https://code-review.googlesource.com/c/gocloud/+/53514. Let me know if that works!

**Comment by fastest963** [comment]
@hongalex works great! Thanks for the speedy fix!
