### ISSUE TITLE
spanner: PDML and BatchReadOnlyTransaction create new sessions instead of using one from the session pool

### ISSUE THREAD

**Issue by hengfengli** [googleapis/google-cloud-go#1951]
**Client**

spanner/v1.5.1

@larkee found that PDML creates a new session instead of using one from the session pool. Is there any particular reason for this? 

https://github.com/googleapis/google-cloud-go/blob/715ffd582b3d47aafe3358859f84071823b42420/spanner/pdml.go#L55-L56

I also found that in BatchReadOnlyTransaction, we also create a new session: 

https://github.com/googleapis/google-cloud-go/blob/715ffd582b3d47aafe3358859f84071823b42420/spanner/client.go#L391

There might be a bug in BatchReadOnlyTransaction: how do we clean up the new created session? Do I miss anything here?

**Comment by hengfengli** [comment]
@larkee Please feel free to add any comments.

**Comment by olavloite** [comment]
> found that PDML creates a new session instead of using one from the session pool. Is there any particular reason for this?

I don't know the exact reason that this choice was made for the Go client. I've been digging in the commit history and review comments, but it has been like this since the initial commit, and there has been no discussion or comments regarding this. The only reason I can think of, is that PDML is designed to accept statements that can take a very long time, and checking out a session from the pool for a long time might have been seen as something that was not preferable.

The same applies to BatchReadOnlyTransactions. The session that is created, is deleted by the `BatchReadOnlyTransaction` itself when the `Cleanup()` method is called:
https://github.com/googleapis/google-cloud-go/blob/53898305c6f21b3c3eef34fcff6c61a2cb36f602/spanner/batch.go#L236

I don't feel very strongly either way; taking a session from the pool or creating one specifically for these transactions. Both types are intended for long-running transactions and the added execution time of a `CreateSession` and `DeleteSession` RPC should normally be negligible compared to the main transaction.

**Comment by hengfengli** [comment]
Thanks for your explanation. I see, the session of BatchReadOnlyTransaction needs to be manually deleted by calling `Cleanup()`.

**Comment by hengfengli** [comment]
@larkee proposed a question: "It makes sense but it raises the question of whether the Java implementation should be changed to matched it. Is there a reason the same explanation wouldn't apply to the Java session pool?"

**Comment by olavloite** [comment]
> @larkee proposed a question: "It makes sense but it raises the question of whether the Java implementation should be changed to matched it. Is there a reason the same explanation wouldn't apply to the Java session pool?"

No, the same explanation would also apply to the Java session pool.

I had a look at the NodeJS client library to see what that does, but that did not really help in making a choice:
1. Partitioned DML: Node takes a session from the pool.
1. Batch read-only transactions: Node creates a new session.

And the C# client:
1. Partitioned DML: (Doesn't seem to support Partitioned DML, other than by using the gapic client directly. Could be that I'm missing something here, though.)
1. Batch read-only transactions: Uses a session from the pool.

So if we want to make this consistent across all client languages, we would have to make multiple changes.

@larkee @hengfengli Do you know what the behavior is in the Python client lib?

**Comment by larkee** [comment]
1. Partitioned DML: Python takes a session from the pool
2. Batch read-only transactions: Python takes a session from the pool.

**Comment by skuruppu** [comment]
@olavloite pinging back on this issue. I personally think it makes sense to take a session from the pool rather than create a new one but we do need to understand why it was implemented this way in the first place. Do you have the background?

**Comment by olavloite** [comment]
@skuruppu Sorry, this was before my time as well. As I wrote above, I did dig into the commit history for the Go client, and it has been like this since it was first released, but there is nothing in the commit log that explains why this choice was made. I also don't know of any other design documents or other documentation where this choice was explained.

**Comment by hengfengli** [comment]
Then, it should always to take a session from the pool. Changes are needed: 

Go: 

1. Partitioned DML: Update to take a session from the pool. 
2. Batch read-only transactions: Update to take a session from the pool. 

Nodejs: 

1. Batch read-only transactions: Update to take a session from the pool. 

C#: 

1. Partitioned DML: Check the current behaviour again. 

@skuruppu Can you make the Nodejs update and take a look at C#? I will do it for Go.

**Comment by skuruppu** [comment]
For C#, PDML queries use an [EphemeralTransaction](https://github.com/googleapis/google-cloud-dotnet/blob/48cef0e8b040645415095f0740cfb222315c2e56/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerCommand.ExecutableCommand.cs#L189). This transaction [(internally) uses a session](https://github.com/googleapis/google-cloud-dotnet/blob/b912eb622efae4c4c3f3120d0a279bca5d4f8b53/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/EphemeralTransaction.cs#L45) from the pool maintained by the [SpannerConnection](https://github.com/googleapis/google-cloud-dotnet/blob/b912eb622efae4c4c3f3120d0a279bca5d4f8b53/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerConnection.cs#L667).

**Comment by skuruppu** [comment]
https://github.com/googleapis/nodejs-spanner/pull/1207 will fix this for Node.js.
