### ISSUE TITLE
BQClientAPI: Query job missing destination table for Stored Procedure call

### ISSUE THREAD

**Issue by harsh364** [googleapis/google-cloud-go#1960]
**Client**
BQClientAPI
Following code gives `query job missing destination table` error while it works fine for SELECT query.
**Code**
```go
package main
import (
	"context"
	"fmt"
	"cloud.google.com/go/bigquery"
)

func main() {
 ctx := context.Background()
 client, err := bigquery.NewClient(ctx, projectID)
 if err != nil {
    fmt.Println(err.Error())
 }
 q := client.Query(`CALL dataset.stored_procedure(input_par);`)
 job, err := q.Run(ctx)
	if err != nil {
		fmt.Println("Job Error : ", err)
	}
	status, err := job.Wait(ctx)
	if err != nil {
		fmt.Println("Status error : ", err)
	}
	if err := status.Err(); err != nil {
		fmt.Println("Status error : ", err)
	}
	it, err := job.Read(ctx)
	if err != nil {
		fmt.Println("Error in reading: ", err)
	}
        
}
```

**Expected behavior**
Query result from stored procedure
**Actual behavior**
Got `query job missing destination table` error, while the code works fine for Select queries. I also tried adding destination table but got following error
`googleapi: Error 400: configuration.query.destinationTable cannot be set for scripts, invalid`.
Also, I have been using stored procedure calls in scala BQ API and it works fine.

**Comment by codyoss** [comment]
cc @shollyman

**Comment by codyoss** [comment]
@harsh364 Could you please confirm what version of cloud.google.com/go/bigquery you are using?

**Comment by harsh364** [comment]
> cloud.google.com/go/bigquery

Hi @codyoss I am using cloud.google.com/go/bigquery v1.4.0

**Comment by shollyman** [comment]
This was a case where we didn't have a great example exercising something like this.  I've created https://code-review.googlesource.com/c/gocloud/+/55550 to add a simple integration test in the meantime, but the critical aspect is that invoking a stored procedure is a SCRIPT statement type rather than a SELECT directly.

For SCRIPT jobs, they may have a 1:many relationship with other jobs (child jobs).  You need to interact with the child jobs in order to access things like the results from SELECT statements.

**Comment by shollyman** [comment]
I'm not familiar with the scala interface, it may do something like pick the first or last select statement from a script's children by default if you ask for row results from a script.
