### ISSUE TITLE
spanner: error using numeric parameter name

### ISSUE THREAD

**Issue by diegocsandrim** [googleapis/google-cloud-go#2561]
**Client**

cloud.google.com/go/spanner v1.7.0

**Environment**

ubuntu 20.04

**Go Environment**

go version go1.14.3 linux/amd64

**Code**

The value of db variable at line 12 should be changed to a valid database before executing the code.

```go
package main

import (
	"context"
	"log"

	"cloud.google.com/go/spanner"
)

func main() {
	ctx := context.Background()
	db := "projects/PROJECT/instances/INSTANCE/databases/DATABASE" //TODO: this must be changed to the test database
	client, err := spanner.NewClient(ctx, db)
	if err != nil {
		log.Fatal(err)
	}

	rot := client.ReadOnlyTransaction()
	defer rot.Close()

	stmt := spanner.Statement{
		SQL: "select 42=@1",
		Params: map[string]interface{}{
			"1": 42,
		},
	}
	it := rot.Query(ctx, stmt)
	err = it.Do(func(r *spanner.Row) error {
		var v bool
		err := r.Column(0, &v)
		if err != nil {
			return err
		}

		log.Printf("response: %v", v)
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}
	log.Print("success")
}
```

**Expected behavior**

The code above should print:

```
response: true
success
```

The `spanner.Statement` documentation says `"Names may be entirely numeric (e.g., "WHERE m.id = @5")"`.

https://github.com/googleapis/google-cloud-go/blob/31f37390b985225ebeda68c20b7363c070ada1b8/spanner/statement.go#L29-L44

**Actual behavior**

The iterator returns an error:

```
Syntax error: Unexpected "@" [at 1:11]
select 42=@1
          ^
```

**Comment by skuruppu** [comment]
Thanks for the report @diegocsandrim. I'm looking into it.

So far, I've converted the [test](https://github.com/googleapis/google-cloud-go/blob/31f37390b985225ebeda68c20b7363c070ada1b8/spanner/statement_test.go#L30) in statement_test.go to use a numeric parameter name and the tests pass.

Next I will try your example.

I'm suspecting the issue has something to do with the combination of a numeric parameter name and the "42=" but I will verify it locally and get back to you.

**Comment by skuruppu** [comment]
It turns out the syntax error is coming from the backend. I tried the following parameter names to see what happens.

```
stmt := spanner.Statement{
        SQL: "SELECT * FROM Albums WHERE SingerId=@1",
        Params: map[string]interface{}{
                "1": 42,
        },
}
```
```
2020/07/09 11:05:37 spanner: code = "InvalidArgument", desc = "Syntax error: Unexpected \\\"@\\\" [at 1:37]\\nSELECT * FROM Albums WHERE SingerId=@1\\n                                    ^"
exit status 1
```

```
stmt := spanner.Statement{
        SQL: "SELECT * FROM Albums WHERE SingerId=@id1",
        Params: map[string]interface{}{
                "id1": 42,
        },
}
```
```
2020/07/09 11:06:16 success
```

```
stmt := spanner.Statement{
        SQL: "SELECT * FROM Albums WHERE SingerId=@1id",
        Params: map[string]interface{}{
                "1id": 42,
        },
}
```
```
2020/07/09 11:07:17 spanner: code = "InvalidArgument", desc = "Syntax error: Unexpected \\\"@\\\" [at 1:37]\\nSELECT * FROM Albums WHERE SingerId=@1id\\n                                    ^"
exit status 1
```

Essentially, if a parameter name starts with a number, it fails.

The [`ExecuteSqlRequest`](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#google.spanner.v1.ExecuteSqlRequest) documentation says "Parameter names can contain letters, numbers, and underscores.". I guess that means that it can contain numbers but can't start with a number.

I will verify this with the Spanner team to see if it's a bug or if we should update the documentation.

**Comment by skuruppu** [comment]
I confirmed with the Spanner team that this is not a backend bug. They explained that named parameters are [Identifiers](https://cloud.google.com/spanner/docs/lexical#identifiers) so the naming restrictions for identifiers apply.

We'll do several things to make the documentation clear on this.

1. We'll update https://github.com/googleapis/google-cloud-go/blob/31f37390b985225ebeda68c20b7363c070ada1b8/spanner/statement.go#L29-L44 to reflect this.
2. We'll update the [`ExecuteSqlRequest`](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#google.spanner.v1.ExecuteSqlRequest) documentation.
3. We'll update the [Named Query Parameters](https://cloud.google.com/spanner/docs/lexical#named_query_parameters) section to link to the identifiers documentation so that there is a reference.

**Comment by skuruppu** [comment]
Our docs team updated the documentation to link to naming requirements for identifiers in a bunch of places. One of them is [Named Query Parameters](https://cloud.google.com/spanner/docs/lexical#named_query_parameters).

The update to `ExecuteSqlRequest` documentation will take a little while to appear in the public documentation since a bunch of syncing steps need to happen before it appears on GitHub and docs.
