### ISSUE TITLE
storage: Missing objects are no longer returning ErrObjectNotExist

### ISSUE THREAD

**Issue by rmistry** [googleapis/google-cloud-go#2635]
My code uses the `cloud.google.com/go/storage` library (@v1.10.0) and does:
`store.Bucket(TestBucket).Object(TestFile).NewReader(ctx)`

For fileNames that do not exist I would expect to get a `storage.ErrObjectNotExist` (because of [this documentation](https://godoc.org/cloud.google.com/go/storage#ObjectHandle.NewReader)). Instead I am getting an `*url.Error`. Example error:
`Get https://storage.googleapis.com/storage/v1/b/TestBucket/o/TestFile?alt=json&prettyPrint=false&projection=full: Got error response status code 404 from the HTTP GET request to https://storage.googleapis.com/storage/v1/b/TestBucket/o/TestFile?alt=json&prettyPrint=false&projection=full
Response: "{\"error\":{\"code\":404,\"message\":\"No such object: TestBucket/TestFile\",\"errors\":[{\"message\":\"No such object: TestBucket/TestFile\",\"domain\":\"global\",\"reason\":\"notFound\"}]}}"
`

Did something change recently?

**Comment by tritone** [comment]
Thanks for your report. I did a little initial investigation and can confirm that the code in our library that checks the response status for a 404 has not changed in 2 years-- see annotations on https://github.com/googleapis/google-cloud-go/blame/bb1907d786f2318b87b0d9d7ef65740b93b62237/storage/reader.go#L157

I'm wondering if there was a change in net/http, such that the call to client.Do on L151 returns an error when there is a 404 when it didn't used to? Need to look into this further.

Could you provide the output of `go version` wherever you're running this so I can investigate further?

**Comment by rmistry** [comment]
Thank you for investigating!
```
$ go version
go version go1.13.3 linux/amd64
```

**Comment by tritone** [comment]
Debugged this offline with @rmistry . It turns out he is using the WithHTTPClient option to pass in a custom client which may return different errors from HTTP calls, and this causes problems with the storage library's error checking logic. Solution to modify the custom client to avoid causing the client to return non-standard errors from HTTP calls.

I thought about adding a caveat about this to the client docs, but it would be hard to predict all the ways that client behavior might change if a custom HTTP client has been passed in.
