### ISSUE TITLE
pubsub: clear subscription messages

### ISSUE THREAD

**Issue by iamolegga** [googleapis/google-cloud-go#2651]
**Is your feature request related to a problem? Please describe.**
when testing application that depends on pubsub topics and subscriptions one have to either delete and create subscription or clear it from gcp console

**Describe the solution you'd like**
create method `Clear` for subscriptions

**Describe alternatives you've considered**
🤷‍♂️

**Additional context**
🤷‍♂️

**Comment by hongalex** [comment]
Hiya,

Just to be clear, this is for the live service, not for `pstest` right? If so, you can implement the [purge message functionality by seeking to a future date](https://cloud.google.com/pubsub/docs/replay-overview#seek_to_a_time). Here's an example:

```go
sub := client.Subscription("subName")
if err := sub.SeekToTime(ctx, time.Now().Add(time.Hour)); err != nil {
    return err;
}
```

We currently don't have plans to add this to the client library since we want to keep the API surface small. However, if we get enough requests for this going forward, we might reevaluate at that time.
