### ISSUE TITLE
firestore: CollectionGroup cursors don't work with field values

### ISSUE THREAD

**Issue by ribrdb** [googleapis/google-cloud-go#2705]
Support for cursors with CollectionGroup queries was added in https://code-review.googlesource.com/c/gocloud/+/49150 as long as you pass in a DocumentSnaphot. However, the function `fieldValuesToCursorValues` needs a similar change to work with collection groups.

I don't know what format the IDs should be in this case, relative to the database root? Or maybe a DocumentRef should be supported?

**Comment by tritone** [comment]
@benwhitehead wanted to confirm with you, should this be permitted? Any other thoughts?

**Comment by ribrdb** [comment]
It seems it has to be permitted. Since DocumentSnapshots aren't serializable, how else can you persist a cursor?

**Comment by BenWhitehead** [comment]
I believe this is expected to work since a Cursor in the [protos}(https://github.com/googleapis/googleapis/blob/master/google/firestore/v1/query.proto#L257-L267) is really just a set of values. The cursor effectively functions as a demarcation point when evaluating the index, so as long as there is an index it should be fine.

I'm not totally sure how all of the translation takes place in the go code. But I believe the structure of a DocumentRef is of the form `projects/{gcp-project-id}/databases/(default)/documents/{documentPath}`

**Comment by crwilcox** [comment]
@ribrdb @BenWhitehead it has been a while since this was opened but was looking to see about adding this.

The linked PR appears to mostly be a softening of requirements to support collection group cursors.

Without a document reference, field values are assumed to be rooted in the same place as the query.

I don't quite follow what the goal is here though, do you have a code fragment that exhibits the undesired behavior as well as the behavior you would expect?

**Comment by crwilcox** [comment]
As part of adding PartitionQueries I am using CollectionGroups for Querying with cursors (startat, endbefore). This works as far as I can tel. One thing I did notice is with collection group queries start and end cursors should not be a complete rooted path.

Bad => `projects/project-name/databases/(default)/documents/collection/doc121`
Good => `documents/collection/doc121`
