### ISSUE TITLE
bigquery: High memory consumption when reading results

### ISSUE THREAD

**Issue by vicpinm** [googleapis/google-cloud-go#3424]
I'm using last bigquery library version for go: `cloud.google.com/go/bigquery v1.14.0`

When I execute a query to read the table where firebase events are copied with this simple code:

![](https://p-261de4.f1.n0.cdn.getcloudapp.com/items/xQuYA95y/Captura%20de%20pantalla%202020-12-08%20a%20las%2016.13.33.png?v=586619ed63e219bb3915cba37538fbcb)

I get a very high memory consumption, which I find really weird as the result set is limited to 5000 rows. This is the memory footprint I get after executing a single query on my service using pprof: 

[Full SVG memory graph](https://p-261de4.f1.n0.cdn.getcloudapp.com/items/BluQ1pPb/after.svg?v=efb1ef4d9a1fc5d1c2396bcd1a0dcc60)

 ![](https://p-261de4.f1.n0.cdn.getcloudapp.com/items/RBu9W01L/Captura%20de%20pantalla%202020-12-08%20a%20las%2016.22.00.png?v=cdb5ddb356edba57b50a0f9e30617be6)

Is thit kind of consumption expected?

**Comment by shollyman** [comment]
This is somewhat expected given that the underlying interactions are all based on a JSON representation of query and row data, and we do additional serialization/transformation upon it.  Number of rows is part of this inflation, but schema complexity is also relevant.

One thing you may try is directly requesting the iterator from the query via [`q.Read()`(https://pkg.go.dev/cloud.google.com/go/bigquery#Query.Read) rather than the `query.Run() -> job.Wait() -> job.Read()` path.  It may yield improvements, though it does potentially cache some of this data to improve overall latency.

**Comment by shollyman** [comment]
Closing this as there's been no additional commentary.  Feel free to reopen if there's more to discuss.
