### ISSUE TITLE
bigtable: SampleRowKeys should also return estimate sizes 

### ISSUE THREAD

**Issue by fsaintjacques** [googleapis/google-cloud-go#3452]
**Is your feature request related to a problem? Please describe.**

1. The SampleRowKeys function documentation does not clearly explain how to use the returned keys, see this [SO](https://stackoverflow.com/questions/65252521/bigtable-samplerowkeys-return-a-single-key/65254498#65254498) post.
2. The size of the chunks are not passed back to the caller.

**Describe the solution you'd like**
1. Better documentation.
2. Add a second method to Table, e.g. `SampleRowKeysWithOffsets` that also returns the offsets.
3. Add a helper that converts the previous method's response in actual `[]bigtable.RowRange` which should be of size n+1 of the previous array. It would also contains an approximation of each range in terms of bytes.

**Describe alternatives you've considered**
Since this is directly in the protobuf payload via hidden properties, I'd have to copy/fork.

**Comment by tritone** [comment]
I think we definitely could improve the documentation. @kolea2 @igorbernstein2 thoughts about the plausibility of doing (2) or (3)?

**Comment by fsaintjacques** [comment]
IMHO 2) is somewhat required as it allows to estimate the size of each ranges, indicating whether you may need to spill to disk or deal with any resource restriction.

**Comment by telpirion** [comment]
This is a [limitation in the service itself](https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#google.bigtable.v2.SampleRowKeysResponse), rather than the Go client. As such, I'm closing this issue.

I encourage you to raise this on the [Bigtable public issue tracker](https://issuetracker.google.com/issues/new?component=187206&template=0).
