### ISSUE TITLE
storage: method to get upload URL

### ISSUE THREAD

**Issue by ORESoftware** [googleapis/google-cloud-go#3481]
**Is your feature request related to a problem? Please describe.**
Yeah cannot easily get url for upload files to GCS

**Describe the solution you'd like**
Looking for a method on storage to retrieve url

**Describe alternatives you've considered**
Generating the url by hand?

```golang

bucket := "bnk-photos"
filename := "mypic3.json"
method := "PUT"
expires := time.Now().Add(time.Minute * 10)

var url = storage.GetUploadURL(bucket, filename)  // this method "GetUploadURL" doesn't exist
```

but this one does:

```golang
		url, err := storage.SignedURL(bucket, filename, &storage.SignedURLOptions{
				GoogleAccessID: cfg.Email,
				PrivateKey:     cfg.PrivateKey,
				Method:         method,
				Expires:        expires,
				ContentType:    "binary/octet-stream",
			})
```

so there is a helper to generate a signed url but no helper method to generate a url?

**Comment by tritone** [comment]
If you want to upload an object using the client, I recommend using a Writer. An example for how to do so is here: https://cloud.google.com/storage/docs/uploading-objects#storage-upload-object-go

If you just want the upload URL for some reason, you can construct it yourself pretty easily following the API reference here: https://cloud.google.com/storage/docs/json_api/v1/objects/insert

We provide methods in the client for generating Signed URLs because there is a lot of tricky client-side logic to get correct there in order to generate the correct signature, but this doesn't apply to a regular upload URL.
