### ISSUE TITLE
logging: Propagate better errors

### ISSUE THREAD

**Issue by loburm** [googleapis/google-cloud-go#3629]
**Is your feature request related to a problem? Please describe.**
It seems that we have an internal loop inside of client library, that retries to execute request. Recently we had a problem that we tried to send log lines with invalid utf8 characters. Instead of returning this error, it was retried multiple times and as a result we received "context deadline exceeded". It has ended up in very long debugging in completely wrong direction (we expected network problem). Then after putting a lot of debug statements into library code we have managed to discover a problem with utf8.

**Describe the solution you'd like**
1. We shouldn't retry errors, related to proto marshalling. I see that we specify retryable [errors](https://github.com/googleapis/google-cloud-go/blob/master/logging/apiv2/logging_client.go#L78), but something went wrong here.
2. Return correct error description.

**Comment by nicoleczhu** [comment]
Hi @loburm I can look into this shortly. Can you provide a snippet, or the exact payload causing the loop?

**Comment by loburm** [comment]
Sure:

```go
        projectID, err := gce.ProjectID()
	if err != nil {
		glog.Fatalf("Failed to fetch projectID: %v", err)
	}
	client, err := logging.NewClient(context.Background(), projectID)
	if err != nil {
		glog.Fatalf("Failed to created client: %v", err)
	}
	client.OnError = func(err error) {
		glog.Errorf("On error: %v", err)
	}
	lg := client.Logger("incorrect")
	lg.Log(logging.Entry{
		Payload: fmt.Sprintf("\x6c\x6f\x67\xe5"),
		Timestamp: time.Now(),
		Resource: &mrpb.MonitoredResource{Type: "global"},
	})
	glog.Info("Before push")
	err = lg.Flush()
	if err != nil {
		glog.Errorf("Failed to write log entry: %v", err)
	} else {
		glog.Info("No errors during logging")
	}
```

At the end I'm getting:

> E0222 10:34:48.880338       1 main.go:37] Failed to write log entry: saw 1 errors; last: context deadline exceeded

Few other notes. I have added a debug statement after the [line](https://github.com/googleapis/google-cloud-go/blob/0bd21d793f75924e5a2d033c58e8aaef89cf8113/logging/apiv2/logging_client.go#L262) to print an error, that's what I got:

> Failed with error: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8 at 2021-02-22T10:24:48.922562225Z

So we have a correct error message, but at the end it's overwritten due to timeout. And here were important things:

1. Default timeout is **10 minutes** (see timestamps in log messages)
2. This request was retried **41 time**.

**Comment by nicoleczhu** [comment]
This is terrible error propagation indeed. I’m thinking: 

1. **Hammer approach**: We could specify `gax.OnCodes` to exclude `codes.Internal` in the handwritten layer [here](https://github.com/googleapis/google-cloud-go/blob/66046da2a4be5971ce2655dc6a5e1fadb08c3d1f/logging/logging.go#L852) to override the undesired gapic defaults [here](https://github.com/googleapis/google-cloud-go/blob/66046da2a4be5971ce2655dc6a5e1fadb08c3d1f/logging/apiv2/logging_client.go#L82) (which we can’t & shouldn't edit). This should avoid retrying `internal` type errors. However, there are many errors under `internal` coding that we’re unable to specify. Some `internal` errors may be intended to be retried?

1. **Knife approach**: Just handle invalid UTF8s in handwritten layer, and write the error to the client error channel. I prefer this atm. 

@loburm @codyoss Open to suggestions. There’s probably a better way. 

`This request was retried 41 time`
Unfortunately, 41 times is plausible (though terrible), since the calculation using these numbers and this formula is`(100ms * (1.3) ^ 33 ) to minutes < 10min max`. Where it will retry for a minimum of 33 times. It’s likely more times since the actual retry period “is a random value between 0 and the retry period”.

**Comment by loburm** [comment]
My concern related to the second approach is that only one known issue was discovered, and we don't have any guarantees that something else is not going to happen in the future with different error type (or maybe it's already happening, but we don't know about it).

Also I have a question about current retry logic. AFAIU 10 min is a max time that will be spent on writing single batch of logs with all retry. Is there any deadline for a single gRPC call? I'm asking it because we have set a lower deadline (10 seconds) by using ContextFunc. Unfortunately it has a big drawback, that once we are unlucky and requests hit some problematic machine, then request fails and is not retried. Ideally I would like to limit single grpc call to 10 seconds, but in case of deadline retry 3-4 times before giving up.

**Comment by loburm** [comment]
@nicoleczhu 
Is there any suggestion how to organize retries in better way, I mean with more meaningful deadline?

**Comment by tomo241** [comment]
I'm not sure how feasible it is, but it'd be great if the Cloud Logging API server returns a different grpc error such as FAILED_PRECONDITION, or INVALID_ARGUMENT.

Speaking of the improvement areas on the client side:

- Some of the internal errors could be retriable.
- However, the current client library doesn't distinguish the retriable errors among internal errors.
- This is an example approach on the client side.
https://github.com/googleapis/google-cloud-go/blob/spanner/v1.44.0/spanner/retry.go#L62-L70
