### ISSUE TITLE
bigtable: emulator column qualifier filter do not work with german umlauts

### ISSUE THREAD

**Issue by oemergenc** [googleapis/google-cloud-go#3704]
I am using the Bigtable emulator in combination with the bigtable java client.
I am facing an issue, where i cannot retrieve columns by column qualifiers with a qualifier containing german umlauts using a Filter when querying against the Bigtable emulator. Querying against a real bigtable instance with the same query works as expected. 

I have made a sample project demonstrating the problem, here:
https://github.com/oemergenc/bigtable-filter-bug/

Find the failing test here:
https://github.com/oemergenc/bigtable-filter-bug/blob/main/src/test/java/bigtable/filter/bug/BigtableFilterBug.java#L69

and the ci results here:
https://github.com/oemergenc/bigtable-filter-bug/runs/1897223718?check_suite_focus=true

Am i doing something wrong or is this a bug?
Kind regars,

**Comment by philpearl** [comment]
It doesn't look like any of the regexp matching works with data with non-ascii or latin-1 characters. We've got a similar problem with § in patterns. It seems to be a problem with https://github.com/rsc/binaryregexp? If I substitute the standard library regexp everything works OK. And none of the unit tests fail. 

It's not clear to me why the emulator uses binaryregexp - there's no explanation in that repo what problems with regexp it's trying to solve.

Is this really a feature request? Because of this code that works with the real bigtable doesn't work with the emulator. Seems like broken function to me.

**Comment by oemergenc** [comment]
I am also wondering about the `feature-request` flag. Looks pretty much like a bug.

**Comment by philpearl** [comment]
I think the solution is to escape any UTF-8 characters in the pattern. So that `^a§b$` becomes `^a\xC2\xA7b$`. I might try that next week (Celebrating #InternationalLizRiceDay tomorrow)
