### ISSUE TITLE
bigquery: Entity Tag

### ISSUE THREAD

**Issue by rayabanid** [googleapis/google-cloud-go#3771]
When I loaded my data from Cloud Storage into Bigquery, the `click_url` field turned into `Record` type when get created even though it's a string (maybe because of the `noindex` not sure tho). When I try to insert the data into BigQuery using `Inserter`. I got this error message:
> Cannot convert std::string to a record field:optional .Msg_0_CLOUD_QUERY_TABLE.Msg_1_CLOUD_QUERY_TABLE_click_url click_url = 1

Table in bigquery:

[![enter image description here][1]][1]

Schema:

[![enter image description here][2]][2]

Here's the code:
```
type Product struct {
        Name     string `datastore:"name" bigquery:"name"`
        ClickUrl string `datastore:"click_url,noindex" bigquery:"click_url"`
        DateAdded time.Time `datastore:"date_added" bigquery:"date_added"`
}

func insertRows(data interface{}) error {
        projectID := "my-project-id"
        datasetID := "mydataset"
        tableID := "mytable"
        ctx := context.Background()
        client, err := bigquery.NewClient(ctx, projectID)
        if err != nil {
                return fmt.Errorf("bigquery.NewClient: %v", err)
        }
        defer client.Close()

        inserter := client.Dataset(datasetID).Table(tableID).Inserter()
        if err := inserter.Put(ctx, data); err != nil {
                return err
        }
        return nil
}

func main() {
        product := Product{"product_name", "click_url", "date_added_value"} // Example data from datastore
        if err := insertRows(product); err != nil {
              fmt.Println(err)
        }
}
```

What should put on the entity tag `"bigquery:click_url"` to make this work?

  [1]: https://i.stack.imgur.com/HItdM.png
  [2]: https://i.stack.imgur.com/AsbUd.png

**Comment by shollyman** [comment]
Currently, it seems like your representations are incompatible.  Base on the datastore struct tags, you have effectively a schema with three string fields.  However, the table you're inserting into has a different schema that has an embedded struct/record field.

Your current inserter would work for a table with a schema like this:

```
tableSchema := bigquery.Schema{
		{Name: "name", Type: bigquery.StringFieldType},
		{Name: "click_url", Type: bigquery.StringFieldType},
		{Name: "date_added", Type: bigquery.TimestampFieldType},
	}
```

However, the table schema you're actually working with has a struct type for **click_url** and three subfields, and looks more like this:

```
tableSchema := bigquery.Schema{
		{Name: "name", Type: bigquery.StringFieldType},
		{Name: "click_url",
			Type: bigquery.RecordFieldType,
			Schema: bigquery.Schema{
				{Name: "name", Type: bigquery.StringFieldType},
				{Name: "text", Type: bigquery.StringFieldType},
				{Name: "provided", Type: bigquery.StringFieldType},
			},
		},
		{Name: "date_added", Type: bigquery.TimestampFieldType},
	}
```

Your options are:

1) Correct the table schema of the table you're inserting into, so that it matches the datastore representation and the two are in sync.

2) Pass a different datastructure into the inserter (e.g. ProductRow or something) that matches the schema and has the appropriate struct tags, and have a mechanism for converting a Product into a ProductRow.

3) Implement a custom [ValueSaver](https://pkg.go.dev/cloud.google.com/go/bigquery#ValueSaver) `Save()` method on your Product struct so that it will produce a data row that adheres to the BigQuery schema you are currently using.

**Comment by rayabanid** [comment]
@shollyman Thank you for the suggestion. But I'm still wondering why the `click_url` turned out to be a struct type(even though it's a string) when I loaded the data from cloud storage to bigquery.

**Comment by rayabanid** [comment]
@shollyman I've followed your suggestion and successfully run the `insert` but when I checked the data in the table I can't seem to find it. Will it reflect realtime once data is inserted?

**Comment by shollyman** [comment]
The rows aren't immediately visible to something like tabledata.list, but they should be present if you query.

It's not clear how you're ingesting from cloud storage, but either the schema of the file (in the case of self describing formats like avro or parquet), or the autodetection of the schema (in the case of something like JSON) is yielding the more complex struct schema.

**Comment by shollyman** [comment]
Closing this as there's been no further activity.  Please follow up if there's more to address here.
