### ISSUE TITLE
pubsub: simple subscribers require permission pubsub.subscriptions.get since v1.10.2

### ISSUE THREAD

**Issue by p-jahn** [googleapis/google-cloud-go#3947]
**Client**

PubSub

**Environment**

- Alpine Docker on GKE
- Service using a service account that has `roles/pubsub.subscriber` IAM membership for my subscription

**Go Environment**

```
go version go1.16.2
```

**Code**

```go
package main

import (
	"context"
	"log"
	"os/signal"

	"cloud.google.com/go/pubsub"
)

func main() {
	ctx := context.Background()
	client, err := pubsub.NewClient(ctx, "my-project")	
	if err != nil {
		log.Fatal("failed to create client:", err)
	}

	rxCtx, stop := signal.NotifyContext(ctx, os.Interrupt)
	defer stop()

	sub := client.Subscription("my-subscription")
	err = sub.Receive(rxCtx, func(_ context.Context, msg *pubsub.Message) {
		log.Println("received a message:", msg.ID)
		msg.Ack()
	})

	if err != nil {
		log.Fatal("failed to receive:", err)
	}
}
```

**Expected behavior**

I can receive messages

**Actual behavior**

`failed to receive: sub.Config err: rpc error: code = PermissionDenied desc = User not authorized to perform this action.`

**Additional context**

Started after upgrading to v1.10.2.

Looks to be introduced by the [Subscription.Config(context.Context) call](https://github.com/googleapis/google-cloud-go/pull/3886/files#diff-820c00bfb025d27cd84a23cb38671b023d41f92431bea486d7d66a3c6eb9ccebR779) in [fix](https://github.com/googleapis/google-cloud-go/pull/3886) for #3884.

[Subscription.Config()](https://github.com/googleapis/google-cloud-go/blob/d864346067f8bff9dd7c9b094628548f648cbee5/pubsub/subscription.go#L549) requires `pubsub.subscriptions.get` permission for

```go
// Config fetches the current configuration for the subscription.
func (s *Subscription) Config(ctx context.Context) (SubscriptionConfig, error) {
	pbSub, err := s.c.subc.GetSubscription(ctx, &pb.GetSubscriptionRequest{Subscription: s.name})
...
```

**Comment by hongalex** [comment]
Apologies for the delay in addressing this. As you pointed out, this was caused by #3886, so that when subscribing from subscriptions *without* ordering keys enabled, your messages will not be delivered in order. This might be useful for performance reasons.

I'll open a PR to check for permissions first and if this call fails, just default to checking the ordering keys field of the received message. In the meantime, please add `roles/pubsub.viewer` or `roles/viewer` permissions to the service account. For more info, see [access control](https://cloud.google.com/pubsub/docs/access-control).

**Comment by p-jahn** [comment]
Thanks for the fix @hongalex 💯

**Comment by hongalex** [comment]
This has been released in [cloud.google.com/go/pubsub v1.10.3](https://github.com/googleapis/google-cloud-go/releases/tag/pubsub%2Fv1.10.3).
