### ISSUE TITLE
spanner: embed transaction into a context

### ISSUE THREAD

**Issue by hengfengli** [googleapis/google-cloud-go#4048]
It may look neat if we can embed txn into ctx. The chromium team has made a lib wrapper for datastore: https://pkg.go.dev/go.chromium.org/luci/gae/service/datastore. 

The code got a bit nicer after removing "txn" parameter from each function: https://chromium-review.googlesource.com/c/infra/luci/luci-go/+/2322028

**Comment by hengfengli** [comment]
This is just as records for a feedback. I think this looks nice to read-only txn, however, for read-write txn, it may get confused due to lack of txn context: Update(ctx) and Commit(ctx). It also needs to remember to update txn in the context when working with multiple txns. Txn becomes an implicit parameter in this way.

**Comment by dsymonds** [comment]
FWIW, it is a tempting idea to jam things in context values, but it does tend to obscure the flow of those things throughout codebases, and having something "official" for passing around transactions in contexts only makes that more likely. There's nothing stopping particular codebases from using their own context key, but transactions are the sort of thing that explicit and visible operations (starting and rolling back or committing) are more valuable than a bit of convenience.

Also, it is risky for something like a transaction to be passed in a context, since a single request (which a context is meant to represent) may do multiple transactions, and the risk of mixing them up seems non-trivial.
