### ISSUE TITLE
bigquery: Better support for read-only queries via bigquery.readonly auth-scope

### ISSUE THREAD

**Issue by ankitsultana** [googleapis/google-cloud-go#4412]
**Is your feature request related to a problem? Please describe.**

At present, if we have a [auth/bigquery.readonly](https://developers.google.com/identity/protocols/oauth2/scopes#bigquery) scope, the only way to run a query is via [Query.Read](https://pkg.go.dev/cloud.google.com/go/bigquery#Query.Read) and even that works only when the fast-path is picked.

[Query.Run](https://pkg.go.dev/cloud.google.com/go/bigquery#Query.Run) uses the [jobs.insert](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/insert) API which requires the [auth/bigquery](https://developers.google.com/identity/protocols/oauth2/scopes#bigquery) scope.

*Ideally*, I think the following two methods should be supported by the Go BigQuery Client for the read-only case:

1. Method to run a read-only Query synchronously. Query.Read does work but in only those limited cases where the fast-path is applicable: https://github.com/googleapis/google-cloud-go/blob/master/bigquery/query.go#L391
2. Method to run a read-only Query and get a Job/Query handle back. This handle may be used by the client to enquire about the job-id or any other metadata, and the handle may later be used to fetch the results (perhaps leveraging the [jobs.getQueryResults](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults) API)

**Describe the solution you'd like**
NA. AFAIU the existing APIs should support the two flavours for running read queries mentioned above.

**Describe alternatives you've considered**
I was earlier using [Query.Read](https://pkg.go.dev/cloud.google.com/go/bigquery#Query.Read) but I ran into a use-case where I needed to get a Query/Job handle first to retrieve the job-id and return it to the user.

I can also help and work on a solution for this if needed.

Thanks

**Comment by shollyman** [comment]
The readonly scope is a bit...flawed.  This is meant to be an internal-only scope, but is exposed publicly.  We have an internal issue related to resolving that problem (183102808) but the long and short of it is that queries end up creating resources of some form.  TL;DR its due to unusual corner cases that this works at all.

If you want to run queries, don't use the readonly scope.  The backend team will not be making an effort to ensure that the bigquery readonly scope works.  That said, if you've got a specific use case related to limiting query execution, consider following up via [support or the public issue tracker](https://cloud.google.com/bigquery/docs/getting-support).

**Comment by shollyman** [comment]
I'm going to close this issue, but feel free to comment if you have further followup.
