### ISSUE TITLE
ads: google ads client support

### ISSUE THREAD

**Issue by rassakhatsky** [googleapis/google-cloud-go#4590]
**Is your feature request related to a problem? Please describe.**
There is no client library for the Google Ads service, and it causes some issues while trying to use Ads API from Golang.  `go-genproto` project used to have structs for Ads service, but they were removed due absence of the client. 

**Describe the solution you'd like**
I would like to have a client for Ads service.

**Describe alternatives you've considered**
The current solution that I have is a wrapper for a standart grpc client that adds additional headers (developer token and client ID) and fork of [`go-genproto`](https://github.com/RedVentures/go-genproto) project with generated ads package.

**Comment by codyoss** [comment]
Hey thank you for your request. Ads made the decision a while back to not have their synthesized protos published in genproto. It looks like [this thread](https://groups.google.com/g/adwords-api/c/pZJyu8Ih3GI/m/LHauRjpUAQAJ) may have some more information related to this request. Closing as this issue is being tracked elsewhere. Hope that helps.
