### ISSUE TITLE
storage: Objects doesn't return all objects matched.

### ISSUE THREAD

**Issue by ukai** [googleapis/google-cloud-go#4676]
**Client**

storage

**Environment**

Ubuntu 18.10 Docker on GKE

**Go Environment**

```
$ go version
go version go1.17 linux/amd64

$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/gopath/.cache/go-build"
GOENV="/home/goma/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""                        
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspace/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2199506818=/tmp/go-build -gno-record-gcc-switches"
```

**Code**

e.g.
```go
package main

func main() {
	// ...
        bkt := client.Bucket(bucket)
        if bkt == nil { .. }
       iter := bkt.Objects(ctx, &storage.Query{
                Prefix: obj,
        })
       for {
                attrs, err := iter.Next()
                if err == iterator.Done {
                        break
                }
                if err != nil {
                        return nil, err
                }
                ...
      }
      ...

}
```

**Expected behavior**

Got all objects matched.
In our case it has 2724 objects.

**Actual behavior**

In a few cases, some server only got 1000 objects or 2000 objects.

**Screenshots**

**Additional context**

We got this error recently, but not sure what version.
between v1.12.0 and v1.15.0 ?

**Comment by tritone** [comment]
Thanks for the bug report.

The default page size for calls to list objects in GCS is 1000, so it makes sense that you would only end up with 1000 or 2000 objects if one of the calls fails. Have you confirmed that the error returned in this case is `iterator.Done` and not something else? Just want to double check.

The logic for the iterator is mostly within google.golang.org/api/iterator. It looks like we return `iterator.Done` only when `nextPageToken` in the [response](https://cloud.google.com/storage/docs/json_api/v1/objects/list) from GCS is not present (See [here](https://github.com/googleapis/google-api-go-client/blob/v0.54.0/iterator/iterator.go#L47)). If GCS is actually returning an empty token when there are objects remaining to be listed, I'll have to file a bug with the GCS backend team to investigate.

@ukai could you do the following?

* Let me know how often you are seeing this bug approximately.
* Verify that err is always `iterator.Done` when you see this issue.

If I can repro the issue myself, I can look into whether the empty page token is actually being returned from the service; if not I can give you some instructions on how to log the response from the service in order to diagnose.

**Comment by ukai** [comment]
I observed ~10 replicas out of >750 replicas.

I think it was always iterator.Done. otherwise, it should log the error and doesn't process found objects further.

**Comment by Breathtender** [comment]
@ukai could you confirm if this issue continued on for you or if it was resolved?

**Comment by ukai** [comment]
I couldn't find any logs that indicate this issue recently.
Is it fixed in backend side?

**Comment by tritone** [comment]
I haven't heard anything about a fix from the backend team. Since I wasn't able to reproduce the issue or find a root cause in the client library, I'm going to have to assume it was a transient issue with the service or with networking.

I'm going to close this issue for now, but feel free to re-open (or open a new one) if you encounter it again.
