### ISSUE TITLE
spannertest: add support for row deletion policy

### ISSUE THREAD

**Issue by alethenorio** [googleapis/google-cloud-go#4782]
**Is your feature request related to a problem? Please describe.**
We use spannertest to build an inmemory database based on a set of DDLs however as spannertest does not have any support for row deletion policy, it will fail calls to `UpdateDDL` with `unhandled DDL table alteration type spansql.AddRowDeletionPolicy`.

**Describe the solution you'd like**
The simplest solution would be to allow row deletion policy DDLs to not fail `UpdateDDL` calls (just ignore the row deletion policy) which would allow for performing basic functionality such as querying and other update

**Describe alternatives you've considered**
Alternative solutions could be to add actual support for row deletion policy (although given that the minimum is 1 day I am not sure how useful it is given the scope of spannertest). A configurable option allowing the user to choose to ignore row deletion policy and not fail `UpdateDDL` calls could also be an option.

**Additional context**

**Comment by hengfengli** [comment]
@olavloite Can you please triage this issue? Thanks.

**Comment by olavloite** [comment]
@alethenorio Do you have an example of a DDL statement with a row deletion policy that does not work for you? I had a second look into this today, and it turns out that it is implemented:
1. Parsing: https://github.com/googleapis/google-cloud-go/blob/2c22a1673947f3b9773ca9d192b3760da6c590b9/spanner/spansql/parser.go#L1087-L1093
2. Tests for both creating and dropping: https://github.com/googleapis/google-cloud-go/blob/2c22a1673947f3b9773ca9d192b3760da6c590b9/spanner/spansql/parser_test.go#L492-L501

**Comment by alethenorio** [comment]
@olavloite Thanks for the ping. Missed the first time around.

The issue is when calling this API

https://github.com/googleapis/google-cloud-go/blob/25cd7a16065d35e4d7cb7f2df0db63fd3a19e289/spanner/spannertest/inmem.go#L270

Which eventually ends up in this switch statement

https://github.com/googleapis/google-cloud-go/blob/25cd7a16065d35e4d7cb7f2df0db63fd3a19e289/spanner/spannertest/db.go#L257

Which has a separate logic from spansql and does not support row deletion policies and instead return the default case of the switch.
