### ISSUE TITLE
GO : High vulnerability in golang.org/x/text 

### ISSUE THREAD

**Issue by niting3c** [googleapis/google-cloud-go#4907]
Golang Sub-libraries use golang.org/x/text which has a here vulnerability as reported here:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14040

Short-term and Long-term upgrade fix is available in v0.3.7

**Comment by codyoss** [comment]
According to that CVE the fix was released in v0.3.3. We only have one library that depends on x/text in this repo and it does so at v0.3.6. So if I am reading everything correctly this is a non-issue.

Also, in the future please follow our advice in [SECURITY.md](https://github.com/googleapis/google-cloud-go/blob/master/SECURITY.md) when reporting security related issues. Thanks.
