### ISSUE TITLE
dataflow: Impossible to set region on template. - Get invalid region endpoint error.

### ISSUE THREAD

**Issue by yugaraxy** [googleapis/google-cloud-go#4960]
**Client**

Dataflow

**Environment**

CloudFunctions

**Go Environment**
go.mod
```golang
go 1.13

require (
	cloud.google.com/go v0.97.0 // indirect
	cloud.google.com/go/dataflow v0.1.0
	cloud.google.com/go/functions v1.0.0
	cloud.google.com/go/storage v1.17.0
	github.com/Yamashou/gqlgenc v0.0.2
	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
	github.com/vektah/gqlparser/v2 v2.2.0
	golang.org/x/net v0.0.0-20210929193557-e81a3d93ecf6 // indirect
	golang.org/x/sys v0.0.0-20211002104244-808efd93c36d // indirect
	golang.org/x/text v0.3.7 // indirect
	google.golang.org/api v0.58.0 // indirect
	google.golang.org/genproto v0.0.0-20211001223012-bfb93cce50d9
	google.golang.org/grpc v1.41.0 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
)
```

**Code**

e.g.
```go
package xxxx

import (
	dataflow "cloud.google.com/go/dataflow/apiv1beta3"
	"cloud.google.com/go/functions/metadata"
	"context"
	"fmt"
	dataflowpb "google.golang.org/genproto/googleapis/dataflow/v1beta3"
	"log"
	"os"
)
const gcsPath = "xxxxxxxxx"
const tempLocation = "xxxxxxxxxxx"

// some codes

// KickDataFlow is called by a PubSub event handler.
func KickDataflow(ctx context.Context, start, end string) error {
	client, err := dataflow.NewTemplatesClient(ctx)
	if err != nil {
		return err
	}
	defer client.Close()

	req := &dataflowpb.CreateJobFromTemplateRequest{
		ProjectId: "xxxxx",
		JobName:   "transform-orders",
		Template: &dataflowpb.CreateJobFromTemplateRequest_GcsPath{
			GcsPath: gcsPath,
		},
		Parameters: map[string]string{
			"input": "gs://xxxxx/order_updates/xxxxxx.jsonl",
		},
		Environment: &dataflowpb.RuntimeEnvironment{
			NumWorkers:          int32(1),
			MaxWorkers:          int32(3),
			WorkerZone:          "asia-northeast1-b",
			TempLocation:        tempLocation,
			ServiceAccountEmail: os.Getenv("SERVICE_ACCOUNT"),
		},
		Location: "asia-northeast1",
	}
	_, err = client.CreateJobFromTemplate(ctx, req)
	if err != nil {
		return err
	}
	return nil
}
```

**Expected behavior**

CloudFunction call succees.

**Actual behavior**

return the error like below

> error in kicking dataflow job: rpc error: code = FailedPrecondition desc = (9abc46254fa5372d): The workflow could not be created, since it was sent to an invalid regional endpoint (asia-northeast1). Please resubmit to a valid Cloud Dataflow regional endpoint. The list of Cloud Dataflow regional endpoints is at https://cloud.google.com/dataflow/docs/concepts/regional-endpoints.

**Screenshots**

![スクリーンショット 2021-10-07 16 31 47](https://user-images.githubusercontent.com/39375351/136339654-13b12209-4530-4cd0-987d-da1eda8d7d14.png)

**Additional context**

There seems to be the same issue in Node.js client.

https://stackoverflow.com/questions/49053048/google-dataflow-invalid-regional-endpoint-impossible-set-region-on-template?rq=1

**Comment by meredithslota** [comment]
Thank you for reporting this! We've identified similar issues in other repos and have escalated this to the API service team since it's not a language-specific library issue. Here are the related issues:

- ListJobsRequest is not using the 'location' filter python-dataflow-client#31: ListJobsRequest is not using the 'location' filter #31
- Support for locations in the launch_template method python-dataflow-client#25: Support for locations in the launch_template method docs(samples): add auto-generated Node samples #25
- The location option of launchFlexTemplate is not working #19: The location option of launchFlexTemplate is not working The location option of launchFlexTemplate is not working #19
- Dataflow: The location field of LaunchFlexTemplateRequest builder is not working java-dataflow#64: Dataflow: The location field of LaunchFlexTemplateRequest building is not working #64
- ListJobsAsync() returns only us-central1 jobs google-cloud-dotnet#7038: ListJobsAsync() returns only us-central1 jobs #7038 (context from issue is that the location parameter isn't working)

Marking this as a P1 bug w/ external label.

**Comment by bbhoss** [comment]
I couldn't find an existing issue in the Google Issue Tracker so I created one [here](https://issuetracker.google.com/issues/208105329). I suggest starring this issue to anyone else that runs across this problem, hopefully it will get some attention from Google soon.

**Comment by davidcavazos** [comment]
Hearing back from the product team, this issue should now be fixed on the latest version of the library.

I'm closing this, but feel free to re-open if the problem still persists.
