### ISSUE TITLE
storage: files with a metadata field with / in its key returns error when reading

### ISSUE THREAD

**Issue by frekw** [googleapis/google-cloud-go#5098]
**Client**

GCS Client

**Environment**

Debian Buster Slim on GKE

**Code**

e.g.
```go
package main

func main() {
  // ...
  obj := bkt.Object(strings.TrimPrefix(req.URL.Path, "/"))
  reader, err := obj.NewReader(context.Background())

  if err != nil {
    return nil, err
  }
}
```

Seems to fail with the following error:

```
Get "https://storage.googleapis.com/gcs-bucket/file.jpg": stream error: stream ID 5; PROTOCOL_ERROR; invalid header field name "x-goog-meta-v1.namespace/width"
```

for a file with the following metadata entry: `v1.namespace/width: 1260`.

**Expected behavior**

To properly read the file.

**Actual behavior**

The error above.

**Additional context**

`gsutil` and other clients seem to read it fine, not sure what's going on. The code itself comes from [imgproxy](https://github.com/imgproxy/imgproxy/blob/78111b22730a1dd4c43bd8398561820de081e694/gcs_transport.go).

**Comment by JesseLovelace** [comment]
Can locally reproduce this, the newReader call does fail with this error when that metadata entry is present. Looking into it and seeing if other languages have the same issue

**Comment by frekw** [comment]
Great! I've only tried the Java client and it seemed to handle it fine.

**Comment by tritone** [comment]
@JesseLovelace @frekw looking at the error I suspect that this may be because the Go client uses http/2, while other languages and gsutil do not.

If you disable http/2 (run with `GODEBUG=http2client=0`), is the issue still reproducible?

In either case, I'm not actually sure whether header names with `.` are allowed in the http spec. If they are, we probably have to file an issue with the go language to address this (since we are just using the net/http client under the hood).

**Comment by JesseLovelace** [comment]
Looks like it still happens with `GODEBUG=http2client=0`

**Comment by frekw** [comment]
From https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata

> All fields and their values must consist only of ASCII characters, with the exception of values for x-goog-meta- fields, which may contain arbitrary Unicode values. Note that when setting metadata using the XML API, which sends custom metadata as HTTP headers, Unicode characters are encoded using UTF-8, then url-encoded to ASCII. 

So I think this is a usecase that should be supported. 

I'm not sure how the metadata is encoded under the hood, but if I remember correctly at least HTTP/1.1 doesn't allow the full ASCII range as a key in an HTTP header. But my understanding is that x-goog- prefix shouldn't be treated as headers?

**Comment by tritone** [comment]
Ah okay, so another difference between Go and other clients is that the Go client uses the GCS XML API for downloads (it uses JSON for all other operations, and most of our other clients are entirely JSON based). In a GET using the XML API, metadata is indeed sent as headers. So you would have this response header: `X-goog-meta-v1.namespace/width: 1260`.

Per RFC 7230, it seems like `/` is not officially supported in header names. (see https://stackoverflow.com/questions/19028068/illegal-characters-in-http-headers ). So I don't think we have a case to ask Go to accept this.

In the JSON API, metadata is sent in the response body rather than the headers, so we don't run into this issue. (I suspect if you did `Object.Attrs()` for this object it would work fine).

I think we'll have to follow up internally to see if there is some way to resolve this inconsistency.

**Comment by tritone** [comment]
Okay, so I followed up and the bottom line is that non-ASCII keys should not be supported for metadata via the XML API. I believe that this is consistent with the gsutil docs you linked above, which indicates that non-ASCII characters are supported only for metadata _values_, not for metadata keys. The XML API is supposed to mostly conform to the AWS S3 API which has [similar limitations](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html).

The best workaround for you would be to eliminate non-ASCII characters from metadata keys from your objects, perhaps by doing url encoding on the keys containing `/` for example.

I'm going to continue to follow up internally to figure out if we should be adding some validation when users upload objects with non-ASCII metadata keys, or do URL encoding on our side if we do have to send keys containing these characters. In addition, we should clarify these limitations in the GCS docs.

Hope this helps, let me know if you have further questions!

**Comment by frekw** [comment]
@tritone understood. But `/` is part of the ASCII range (character 47), so if ASCII characters should be supported for keys then `/` should be supported.

**Comment by tritone** [comment]
@frekw you're correct, I was confused on that point-- the RFC 7230 limitations are more restrictive than just ASCII for header keys. I guess we should probably be doing URL encoding on our end for such cases, or document this restriction. Will continue to update on what I hear internally on this.

**Comment by frekw** [comment]
@tritone great, thank you 🙏 

I don't mind changing it at all, but before I do I'd like to know if it's the documentation or the Go client that's in the wrong regards to the full ASCII-range being allowed in keys.

When I read that the full ASCII-range was supported I was positively surprised, even more so when it also worked with (some) of the GCS clients. :)

**Comment by tritone** [comment]
Yeah, the tricky part is that we have two separate APIs for GCS. In the JSON API (which most clients use), metadata is sent in the request body; therefore there are essentially no restrictions on what can be sent (at least from HTTP protocols). In contrast, the Go client uses the XML API for downloads, which sends metadata as `x-goog-meta-*` headers.  The Go client itself seems to be following the protocol in rejecting these keys.

**Comment by tritone** [comment]
Followed up internally, it seems that the conclusion is just that we should update the devsite docs to indicate that the set of acceptable characters for XML is more limited. The line [here](https://cloud.google.com/storage/docs/metadata#editable) about "avoid non-ascii characters" is incorrect; @frekw correctly pointed out that the acceptable character set for headers is more limited than ascii. I'm working on an internal change to clarify these docs, as well as a change to clarify this package's docs for metadata.
