### ISSUE TITLE
spanner/spannertest: delay during UpdateDatabaseDdl calls

### ISSUE THREAD

**Issue by Jahaja** [googleapis/google-cloud-go#5406]
I've been looking into why some of our tests have a suspiciously long setup time for being all in-memory by using the `spannertest.Server`, and I've found a few things, or a flow rather, that I suspect might not be intended behavior.

Looking at this code here it suggests that there's been some work into not delaying a waiting caller for too long during simulated long-running operations:

https://github.com/googleapis/google-cloud-go/blob/0ea8993ee2e0d56fd77a3a57226cca3124382a1c/spanner/spannertest/inmem.go#L304-L327

However since `UpdateDatabaseDdl` runs that code async and returns immediately here:

https://github.com/googleapis/google-cloud-go/blob/0ea8993ee2e0d56fd77a3a57226cca3124382a1c/spanner/spannertest/inmem.go#L295-L301

It will cause a waiting admin client's first `longrunning.Operation.Poll` to see if the DDL update operation is done to be false. Triggering an initial backoff of 1 sec sleep by `longrunning.Operation.WaitWithInterval`:

https://github.com/googleapis/google-cloud-go/blob/0ea8993ee2e0d56fd77a3a57226cca3124382a1c/longrunning/longrunning.go#L134-L138

Our current workaround is to just call `spannertest.Server.UpdateDDL` instead, which is fine, but since the `spannertest`s own integration tests also have these delays I guess other people than us may be using the admin client to setup DDL for their tests as well.

**Comment by rahul2393** [comment]
Hello @Jahaja , thanks for opening the issue here, can you share your brief usecase for using spanner/spannertest, spansql/spannertest packages lag behind compared to the actualy cloud spanner feature wise and functionality wise, We are thinking of freezing the development of spansql/spannertest packages and recommend to use officially supported https://cloud.google.com/spanner/docs/emulator for in-memory usage.

**Comment by dsymonds** [comment]
Hey @Jahaja, the purpose of the delay is to trip up assumptions in client code about how fast DDL changes can happen. The intention is that if the client code waits, we short-circuit the delay since they've proven they are doing the right thing.

As you point out, `WaitWithInterval` is unfortunately enforcing a minimum pause there. The first `Poll` invokes the `(*server).GetOperation` method in `inmem.go`, which does the short-circuit, but immediately returns the current state, which will be not-done.

One easy way to fix this would be for `noWait` to indicate whether the short-circuit has fired, then have `GetOperation` do a short pause (e.g. 20ms) to permit the operation(s) to run. That should maintain the property of catching out non-waiters, but make a proper client be quick too.
