### ISSUE TITLE
spanner/spansql: Support conditional expressions

### ISSUE THREAD

**Issue by tyamagu2** [googleapis/google-cloud-go#5837]
spansql fails to parse statements that contain [conditional expressions](https://cloud.google.com/spanner/docs/reference/standard-sql/conditional_expressions) like `SELECT CASE 1 WHEN 1 THEN "X" WHEN 2 THEN "Y" ELSE NULL END`.

**Comment by rahul2393** [comment]
Hello @tyamagu2, thanks for opening the issue here, can you share your brief usecase for using spanner/spansql, spansql/* packages lag behind compared to the actualy cloud spanner feature wise and functionality wise, We are thinking of freezing the development of spansql/* packages and recommend to use officially supported https://cloud.google.com/spanner/docs/emulator for in-memory usage.

**Comment by tyamagu2** [comment]
Hi @rahul2393 . I actually don't use spansql/spannertest. I use [cloudspannerecosystem/yo](https://github.com/cloudspannerecosystem/yo) to generate go code from spanner DDL file, and yo v2 uses spansql to parse DDL statements. I'm trying to generate code from the DDL statement that contains a column definition like the following, so I need spansql to support parsing either CASE or IF expression.

```
InProgress BOOL AS (CASE WHEN Status = "in_progress" THEN TRUE ELSE NULL END) STORED
```

**Comment by rahul2393** [comment]
ok in the Readme of [cloudspannerecosystem/yo](https://github.com/cloudspannerecosystem/yo) its mentioned that `application is not officially supported as part of the Cloud Spanner product` but since the change is small it's ok for now.

**Comment by tyamagu2** [comment]
Thank you!
Do you plan to freeze spansql development as well?
