### ISSUE TITLE
datastore: in not-in documents

### ISSUE THREAD

**Issue by sonatard** [googleapis/google-cloud-go#6285]
**Is your feature request related to a problem? Please describe.**
https://pkg.go.dev/cloud.google.com/go/datastore#Query.FilterField

If `FilterField` function operation argument is `in` or `not-in` , I don't know what to pass to the value argument. Is it one of the following? Or is it different?
1. `FilterField("UserID", "in", "1,2,3,4")`
2. `FilterField("UserID", "in", "1 2 3 4")`
3. `FilterField("UserID", "in", []string{"1", "2", "3", "4"})`

https://pkg.go.dev/cloud.google.com/go/datastore#Iterator.Next
If `FilterField` function operation argument is "in" or "not-in", I don't know what to pass to the `Next` function argument. 

```go
func ExampleIterator_InNext() {
	ctx := context.Background()
	client, err := datastore.NewClient(ctx, "project-id")
	if err != nil {
		// TODO: Handle error.
	}
	it := client.Run(ctx, datastore.NewQuery("Post").FilterField("UserID", "in", "1,2,3,4"))
	for {
		// var p Post or var p []Post
		key, err := it.Next(&p) 
		if err == iterator.Done {
			break
		}
		if err != nil {
			// TODO: Handle error.
		}
		fmt.Println(key, p)
	}
```

**Describe the solution you'd like**
Please update GoDoc, Unit Test or Example.

**Comment by howkey666** [comment]
It works only when you use `[]interface{}` but I am not sure if it's an intention.

The problem is in this line https://github.com/googleapis/google-cloud-go/blob/main/datastore/query.go#L403 or the function `interfaceToProto` itself.

 I played with it little bit: https://go.dev/play/p/EPcuMU9bzEU

**Comment by telpirion** [comment]
Hi @sonatard , thank you for logging this question!

Your third example is correct: if you wanted to filter for values 1, 2, 3, or 4 in field "Foo," you would write the following:

```
myQuery.FilterField("Foo", "in", []interface{1, 2, 3, 4})
```
See [integration test for other examples](https://github.com/googleapis/google-cloud-go/blob/main/datastore/integration_test.go#L496).

`Filter()` and `FilterField()` have the same behavior (and have the same behavior as before `FilterField()` was introduced). They both also return the same type of object: a `Query` pointer. You would still pass in the `struct` that defines how the data in the column should be deserialized (if you call `Run()`). Thus, in your example, you would still pass in a pointer to a `Post` struct, assuming that `Post` is declared or imported into your code.

With regards to how to update the GoDoc, what would you like to see added?

@howkey666 Thank you for answering @sonatard 's question!

Yes, the intention is that you must pass a slice of `interface` objects into the `FilterField()`. In order to send data over the wire, we need to cast a filter value to its protobuf equivalent (hence the `interfaceToProto()` function). [See the gRPC docs for more information](https://grpc.io/docs/what-is-grpc/core-concepts/#using-the-api).

**Comment by howkey666** [comment]
Hi @telpirion,
to be honest I missed that integration test :facepalm: I found the solution by going trough the code and playing with it on Go Playground and in my local test. I would update documentation here https://pkg.go.dev/cloud.google.com/go/datastore#Query.FilterField and point out that `in` and `not-in` operators requires value type `[]interface{}`. 

What do you think?

**Comment by marwansalem** [comment]
+1 , because I got lost

This worked for me
```golang
	myValues := []interface{}{1, 2, 3, 4}

```
