### ISSUE TITLE
storage: Provide the ability to access the contents of a bucket using HMAC keys.

### ISSUE THREAD

**Issue by mgiannakopoulos** [googleapis/google-cloud-go#6489]
**Is your feature request related to a problem? Please describe.**
The `storage` GCP Go SDK does not provide any option to authenticate via HMAC keys so as to access the contents of a bucket.

**Describe the solution you'd like**
Extend the `storage.NewClient(context, ClientOption)` is such a way that `ClientOption` can receive an Access Key ID and a Secret.

**Describe alternatives you've considered**
Use s3 GO sdk, but I am afraid that this approach won't take advantage on any of the internal features of the GCP GO sdk that might include optimization enhancements. Not to mention that I would need to bring two different Go SDKs in my application although I am using Google Cloud Storage.

**Additional context**
Why not use JSON credentials? Because I would like to have a generic way of accessing buckets between S3 and GCS.

**Comment by tritone** [comment]
@mgiannakopoulos thanks for the issue. Unfortunately, this will not be possible for us to implement because most requests made by this library use the JSON API to call GCS. However, HMAC keys are only usable with the XML API (which is provided for S3 compatibility). So HMAC auth is just not compatible with how this library works. See https://cloud.google.com/storage/docs/authentication/hmackeys#restrictions

I'd recommend using the S3 SDK to call GCS, or passing JSON credentials as you mention.
