### ISSUE TITLE
storage: Writer does not seem to be retrying server errors.

### ISSUE THREAD

**Issue by miroslavLalev** [googleapis/google-cloud-go#6547]
**Client**

Storage v1.25.0

**Environment**

Google Compute Engine

**Issue**

I've been experiencing sporadic errors when closing storage writers for the last couple of days. The backend returns errors like these after around 10 seconds of writing and they don't seem to be retried at all.
```
error closing bucket writer: blob (key "...") (code=Unknown): googleapi: Error 503: We encountered an internal error. Please try again., backendError
```

After poking around the code for a little bit, I saw that the default retry function has the following check, which makes me wonder why writes are not getting retried:
```
case *googleapi.Error:
  // Retry on 408, 429, and 5xx, according to
  // https://cloud.google.com/storage/docs/exponential-backoff.
  return e.Code == 408 || e.Code == 429 || (e.Code >= 500 && e.Code < 600)
```

Running the same code again after such an error works fine, so I think that a retry should fix the problem immediately.

**Expectation**

Backend errors (5xx) should be retried properly when closing storage writers.

**Comment by tritone** [comment]
Hi @miroslavLalev , thanks for the issue.

Uploads in GCS are not idempotent operations unless an ifGenerationMatch precondition is provided with the request (see [here](https://cloud.google.com/storage/docs/retry-strategy#idempotency-operations)). Therefore, the client library does not retry failures by default unless this precondition is provided by setting Conditions.GenerationMatch or Conditions.DoesNotExist.

If you'd like to retry failures regardless, we provide an option for that as well -- using a [RetryAlways](https://pkg.go.dev/cloud.google.com/go/storage#RetryAlways) policy. See https://pkg.go.dev/cloud.google.com/go/storage#hdr-Retrying_failed_requests for info on how to configure.

Hope this helps!

**Comment by miroslavLalev** [comment]
@tritone Thanks for your quick reply! These options explain a lot.

However, I have a bit of difficulty understanding the exact purpose of `RetryAlways`. Let's say that my GCS use case does not allow for an object to be rewritten with difficult content, however, it is completely possible for an object to be written (with the same media content) by multiple clients at the same time. Does this mean I can safely use `RetryAlways`, or are there situations where the object could end up corrupted? Essentially my question is whether `RetryAlways` is unsafe if and only if an object could be rewritten (with different media content) by multiple clients at the same time.

Thanks again!

**Comment by tritone** [comment]
Good question. In this case, I don't see how your data could be corrupted; there is no risk of data being overlaid from multiple sessions for example. So there wouldn't be a possibility for data corruption from using RetryAlways.

For uploads in the case you describe, non-idempotency will have more minor impacts if the upload ends up succeeding multiple times:
* Writer.Generation after completing the upload may not match the actual generation of the live object.
* You will be charged for both operations.

As long as these downsides are acceptable, it's fine to use RetryAlways. But it may also be reasonable to use Conditions.DoesNotExist so that additional attempts to upload the same file will fail with 412. See for more details: https://cloud.google.com/storage/docs/request-preconditions

**Comment by tritone** [comment]
Going to close this out for now, but feel free to re-open or file a new issue if you have further questions.
