### ISSUE TITLE
bigquery: query's temporary table

### ISSUE THREAD

**Issue by bai-ming** [googleapis/google-cloud-go#6640]
After I run a query. I can't get the query's temporary table If I dosen't set it.
![image](https://user-images.githubusercontent.com/85221235/189288622-52b8af22-3529-43ef-b5a5-9817a68ba227.png)
the qc.Dst is nil. And I can't find other fields to show me where the query's temporary table is 

But In PHP
![image](https://user-images.githubusercontent.com/85221235/189288942-da50cf61-70ae-4865-8c04-62a165b97407.png)
I can use this to get it.

So if the job is completed , can it be filled by the real temporary table?

**Comment by shollyman** [comment]
The issue is essentially that the config is stale, and from when you invoke `JobFromID()`.  We don't invoke a job metadata rpc to refresh this currently.  We do provide a reference to the job on the row iterator, so you can invoke a JobFrom* request if you want to get at the config metadata after completion (which will populate the destination).

Consider this alternative (all error checking elided):
```
	it, _ := client.Query("SELECT CURRENT_TIMESTAMP() as ts").Read(ctx)
	job, _ := client.JobFromID(ctx, it.SourceJob().ID())
	cfg, _ := job.Config()
	qCfg, _ := cfg.(*QueryConfig)
	fmt.Printf("Table: %s", qCfg.Dst.FullyQualifiedName())
}
```

I'd love to understand the use case here a bit more.  Are you trying to spin up a storage API read session, or is there another use case you have in mind?

**Comment by bai-ming** [comment]
I get the temporary table, thanks.
