### ISSUE TITLE
storage: strange behavior with Query.StartOffset and Query.EndOffset when Query.Prefix is set

### ISSUE THREAD

**Issue by ecezalp** [googleapis/google-cloud-go#6953]
Using Go 1.18

In my bucket I have objects like `${uuid}/${unixmilli}` such as 

`22ffb07d-303b-4816-a746-baaa3aa82584/1666790565522`
`22ffb07d-303b-4816-a746-baaa3aa82584/1666790565532`
`22ffb07d-303b-4816-a746-baaa3aa82584/1666790568532`

Created a super simple endpoint to recreate the problem, you can find the server code for that attached below. 

When I do the following query it works as expected
`curl -X GET localhost:1323/gcloud/read -H 'Content-Type: application/json' -d '{"prefix":"", "startOffset":"22ffb07d-303b-4816-a746-baaa3aa82584/1666732794176", "endOffset":"22ffb07d-303b-4816-a746-baaa3aa82584/1666732794277"}'`

When I use the prefix I get no results even though there are items that should be matching
`curl -X GET localhost:1323/gcloud/read -H 'Content-Type: application/json' -d '{"prefix":"22ffb07d-303b-4816-a746-baaa3aa82584/", "startOffset":"1666732794176", "endOffset":"1666732794277"}'`

If I change the first digit of the endOffset to 2, I get everything within the `uuid`, even the values smaller than the startOffset
`curl -X GET localhost:1323/gcloud/read -H 'Content-Type: application/json' -d '{"prefix":"22ffb07d-303b-4816-a746-baaa3aa82584/", "startOffset":"1666732794176", "endOffset":"2666732794277"}'`

endpoint implementation below, where `prefix`, `startOffset`, and `endOffset` are strings extracted from the request

```
ctx := context.Background()
client, err := gcloud.NewClient(ctx)
if err != nil { panic(err) }
defer client.Close()

ctx, cancel := context.WithTimeout(ctx, time.Second*50)
defer cancel()

var response []pkg.ReadLogResponse

it := client.Bucket(bucket).Objects(ctx, &gcloud.Query{
    Prefix:      prefix,
    StartOffset: startOffset,
    EndOffset:   endOffset,
})

for {
    attrs, err := it.Next()
    if err == iterator.Done {
        break
    }
    if err != nil {
        return response, fmt.Errorf("Bucket(%q).Objects(): %v", bucket, err)
    }
    response = append(response, pkg.ReadLogResponse{
        Log: attrs.Name,
    })
}

return response, nil
```

I also played around with Query.Delimiter (made it `/` and removed the `/` from other params), moved the numbers around (such as making the prefix `"22ffb07d-303b-4816-a746-baaa3aa82584/1666732794", "startOffset":"176", "endOffset":"277"` those also didn't work.

But everything works without the prefix.

Please let me know if I am missing something or if there is something that needs to be fixed here. Thanks :)

**Comment by BrennaEpp** [comment]
Hi @ecezalp, thanks for opening this issue!

`Query.Prefix` is independent from `Query.StartOffset` and `Query.EndOffset`. That means that it will filter from `StartOffset` to `EndOffset`, not from `Prefix + StartOffset` to `Prefix + EndOffset`, even if `Prefix` is set.  So if you want to filter from `Prefix + StartOffset` to `Prefix + EndOffset`, you need to do as in your first example. 

Your second example does not return any results because your uuids (`"22ffb07d ...")` are [lexicographically](https://en.wikipedia.org/wiki/Lexicographic_order) larger than your end offset `"1666732794277"`. Once you change that offset to start with "26", all your uuids fall within the range ("16..." < "22..." < "26...") and you get all of them in the results. 

Hopefully this clarifies things a bit.
