### ISSUE TITLE
storage: EOF errors during calls

### ISSUE THREAD

**Issue by miroslavLalev** [googleapis/google-cloud-go#7090]
Recently, I've encountered the following error during an `Attrs` request for a given object:
```
Get "https://storage.googleapis.com/storage/v1/b/<bucket>/o/<object>?alt=json&prettyPrint=false&projection=full": EOF
```

I've checked the default `ShouldRetry` function and it seems that it only retries `unexpected EOF` errors. Can the normal `EOF` errors be retried safely?

**Comment by tritone** [comment]
Thanks for the issue. So, the difference between `EOF` and `io.ErrUnexpectedEOF` is that the latter occurs only when we expected to receive a certain number of bytes, but got an EOF before hitting that number. I believe the `net/http` client determines this using the `Content-length` header; e.g. if the response from the server has `Content-length: 852`, then we expect the JSON response body to have 852 bytes. Therefore if we get `ErrUnexpectedEOF` we know that the payload was not complete (perhaps due to connection issues) and we should retry the request.

I'm not totally sure how you could get a normal EOF error from a call to `ObjectHandle.Attrs` and don't think I've encountered this before myself. I would be curious to see the `Content-length` header as well as the actual length of the payload to try and debug.

In the meantime, I think it's safe for you to add `EOF` as a retryable error using `WithErrorFunc` specifically for calls to `Attrs`; however there are other library methods where it wouldn't be safe as this is used as a sentinal error internally (in the case of `Reader` or externally (in the case of iterator methods).

**Comment by miroslavLalev** [comment]
I was very puzzled as to why would the HTTP client return such an error. It seems to be a _very_ rare occurrence, considering we are doing in the order of a couple of billions of requests to GCS every single day. So far it has only happened once, around the following timestamp: 2022-11-12 02:41:24 UTC. Could it be somehow related to changes or deployments in GFE around that time?

Since we are also doing reading and writing with the same client, I might have to add external retry logic wrapping only `Attrs` requests.

Regarding your question, is there something of interest that I can log, which can help debug the issue further if it happens again? I'm not sure if there is any way to obtain HTTP headers from the returned error, but if you can think of something, I will add it.

**Comment by miroslavLalev** [comment]
After some poking around reported issues for `net/http`, I stumbled into this one: https://github.com/golang/go/issues/53472
Could be related to what I've experienced.

**Comment by tritone** [comment]
You can customize retry settings on a BucketHandle or ObjectHandle or customize them per call; it would look something like this:

```
func myErrorFunc(err error) bool {
  ...
}
client.Bucket("my-bucket").Object("my-object").Retryer(WithErrorFunc(myErrorFunc)).Attrs()
```

See https://pkg.go.dev/cloud.google.com/go/storage#ObjectHandle.Retryer for details.

I don't think it's safe to add retries for EOF to the library for the reasons I mentioned above and because it's just generally not intended to be a retryable error. The issue that you linked is interesting though; I can flag it with the Go team. It sounds like EOF is really not the appropriate error for net/http to be raising in this case.

**Comment by miroslavLalev** [comment]
Thanks for your help, I will do that on my side.

I would be interested in any updates on the `net/http` side, so shall I leave this issue open for tracking upstream progress?

**Comment by tritone** [comment]
Sure that's fine. I flagged the linked case with @neild on the Go team, so it's in his queue, but might take some time to address (and obviously any fix at that level will not be available until the next Go language release).

**Comment by tritone** [comment]
Actually, I'm going to close this issue because 1. we have a workaround and 2. further work is being tracked in golang/go#53472 (and, this issue is tripping our internal SLO metrics). If you run into additional issues that are related to code in the storage library feel free to file a new one
