### ISSUE TITLE
bigquery: configure write disposition for Inserter

### ISSUE THREAD

**Issue by wilfreddesert** [googleapis/google-cloud-go#7094]
**Is your feature request related to a problem? Please describe.**
For some reason, currently, it's possible to set write disposition for the `LoadFrom` method but not for `Inserter.Put`. What I want to achieve is to truncate the partition first and then write rows created in the code to it. 

**Describe the solution you'd like**
I would like to be able to set write disposition like:

`myInserter.WriteDisposition = bigquery.WriteTruncate`

**Additional context**
Probably, there is a way to achieve this behavior but I haven't found it yet. Based on the documentation, it's now only possible for the method with a GCS bucket under the hood

**Comment by shollyman** [comment]
The Inserter is for continuous ingestion, and is used for streaming row data into a BigQuery table.  It has no affordances for managing the state of the table.  We clearly wouldn't want to truncate the table every time you stream a row, for example.

If you want to alter a table prior to streaming, it's likely easiest to do something like execute a DML query (since you mention rewriting a partition rather than a table), and upon successful completion start streaming rows through the inserter.

I've marked this as a question since it's not a feature request we'd consider (assuming I'm understanding your request correctly).  Let me know if there's more clarification needed.

**Comment by wilfreddesert** [comment]
@shollyman , thank you. But do I understand correctly, deleting this partition first would make it impossible to create it again during the next several minutes as it often happens. Or probably you could show a minimalistic example? Thanks

**Comment by shollyman** [comment]
If the partition isn't actively receiving streaming inserts, then you should not have issues.

If however you're actively streaming to a given partition, then wish to drop it and resume streaming then yes you are more likely to encounter issues.  It's likely the DML to delete the partition will be rejected due to [streaming limitations on DML](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-manipulation-language) for example.

**Comment by wilfreddesert** [comment]
It seems that in my case I could even do without BQ partitioning. For example, before any inserts I could just execute something like `DELETE ... FROM my_table where batch_id = <some_value>` AND job_id  = <some_value>`. and after that stream data. 

This way, I unfortunately lose the automated partition handling in BQ but can guarantee there won't be any duplicated data. 

What do you think about this approach?

**Comment by shollyman** [comment]
I'm not sure what you mean by automated partition handling.  If a `DELETE` statement has a WHERE clause that removes all data from a given partition, that partition is empty.  You can stream afterwards regardless of whether the partition has data or not.
