### ISSUE TITLE
pubsub: Detect offline network in Receive

### ISSUE THREAD

**Issue by flibustenet** [googleapis/google-cloud-go#7338]
**Is your feature request related to a problem? Please describe.**
When calling `sub.Receive(ctx context.Context, f func(context.Context, *Message)) ` i see no way to detect if network is going offline. No error, no return. Then i don't know if i don't receive message because there are not or if it's because i'm offline and that i should restart my subscription.

**Describe the solution you'd like**
Is there an option to handle this or what is the best practice to do it ?

**Describe alternatives you've considered**
I wonder if i should make some sort of ping to detect regularly if i'm still online.

**Additional context**
I've no problem using a TimeOut when i call `pubsub.NewClient` or `client.Subscription`

**Comment by flibustenet** [comment]
After many trying, it seems that `Receive` automatically stay up when the network become again online. So it's probably not an issue.  
I still let the issue open if you maybe like to document this ?

**Comment by hongalex** [comment]
So this seems to be working as intended. The reason why you're not seeing any errors is because we silently streaming pull errors, including [`DEADLINE_EXCEEDED`](https://github.com/googleapis/google-cloud-go/blob/5bedddf149dc1689ad7071a6b62705d5b5a837f7/pubsub/service.go#L57) with exponential backoff. As you noticed, after the network is available again, these requests will eventually succeed.

We have plans to do logging such that these kinds of scenarios are more transparent but at the moment, this is working as intended.
