### ISSUE TITLE
Need to generate cloud.google.com/go/orgpolicy/apiv1 for asset client

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloud-go#7352]

**Comment by codyoss** [comment]
@quartzmo assigning this one to you. We need to get this library generated so asset can depend on the protos. We can generate it the old way for now.

**Comment by quartzmo** [comment]
Typically, the package short name that we use is taken from the last token after `;` in `go_package`. In [this case](https://github.com/googleapis/googleapis/blob/master/google/cloud/orgpolicy/v1/orgpolicy.proto#L23), it is `orgpolicypb`. I will use `orgpolicy` instead, in order to generate the library name provided above, `cloud.google.com/go/orgpolicy/apiv1`.

**Comment by quartzmo** [comment]
Hmmm, without a gRPC service config, I don't think generation will succeed.

**Comment by quartzmo** [comment]
```

--go_gapic_out: error reading service config: read google/cloud/orgpolicy/v1: is a directory
```

**Comment by codyoss** [comment]
The Go package for the protos here is correct and does follow our new patterns: `cloud.google.com/go/orgpolicy/apiv1/orgpolicypb;orgpolicypb`. This corresponds to a gapic of `cloud.google.com/go/orgpolicy/apiv1`.

We may need to add a config to get it to generate in that case

**Comment by quartzmo** [comment]
https://github.com/googleapis/googleapis/tree/master/google/cloud/orgpolicy/v1

**Comment by codyoss** [comment]
Asset client will need updates now to close this issue otu.
