### ISSUE TITLE
bigquery/managedwriter: Is pending stream a batch api

### ISSUE THREAD

**Issue by stgleb** [googleapis/google-cloud-go#7618]
**Is your feature request related to a problem? Please describe.**
I have a question regarding batching definition. 
According to:

https://cloud.google.com/bigquery/docs/write-api

It clearly states that if I need batching I need to go with pending stream.
But I am wondering how is this aligned with batch load from pricing

https://cloud.google.com/bigquery/pricing

Which is promised to be free. Is this two different batching?

I want to figure out how those batching methods https://cloud.google.com/bigquery/docs/loading-data#batch_loading
are mapped to  Batch Loading on pricing page.

**Comment by shollyman** [comment]
Batch ingestion from the perspective of the bigquerystorage write API (and the managedwriter package) is largely about when the rows become visible in the destination table.  Pending streams allow for rows from one or more pending stream to become visible together in an atomic fashion.  Contrast this with streaming ingestion such as default or committed streams, where rows may be arriving continuously.

It appears that "Batch loading" in the pricing page refers to the BigQuery file-based loading mechanism.  That functionality is exposed in the [main bigquery package](https://pkg.go.dev/cloud.google.com/go/bigquery).  It's called batch because it has similar visibility behavior: rows from a given load job become visible transactionally after the ingestion finishes , not incrementally/continuously as the data is processed.

Hope this helps.

**Comment by shollyman** [comment]
Pending stream enables more ways to achieve exactly-once write semantics, but those patterns typically have some sort of central coordinator process that can reason about the completeness of a set (batch) of writes.

If you just have a bunch of independent writers without central coordination, then yes default streams are simpler and easier solution.  you can achieve at-least-once write semantics, which is generally sufficient.
