### ISSUE TITLE
pubsub: Message.Ack documentation does not match with its behaviour

### ISSUE THREAD

**Issue by malisetti** [googleapis/google-cloud-go#7694]
the documentation of Ack is this

// Ack indicates successful processing of a Message passed to the Subscriber.Receive callback.
// It should not be called on any other Message value.
// If message acknowledgement fails, the Message will be redelivered.
// Client code must call Ack or Nack when finished for each received Message.
// Calls to Ack or Nack have no effect after the first call.
func (m *Message) Ack()

**Expected behavior**

e.g. According the documentation Ack may fail.

**Actual behavior**

e.g. Ack does not return anything.

**Comment by hongalex** [comment]
This actual behavior (ack not returning anything) is intentional. Acks are best effort, and fire and forget by default. While they can fail, it will not be returned to the user. Instead, the message will be redelivered. This is inline with Pub/Sub's default expectation of at-least-once delivery. If you need exactly once delivery, consider enabling that on the subscription and calling `AckWithResult()`. For more information, see https://cloud.google.com/pubsub/docs/exactly-once-delivery
