### ISSUE TITLE
bigquery: set `PreferredMinStreamCount`while creating `CreateReadSessionRequest`

### ISSUE THREAD

**Issue by k-anshul** [googleapis/google-cloud-go#8432]
**Is your feature request related to a problem? Please describe.**
While creating `CreateReadSessionRequest` we are setting `MaxStreamCount` as 0 which as I understand will leave the decision on server to choose the correct stream count. 
On my testing on various public and private data sources I always found the number of stream to be 1.
I would like to set `PreferredMinStreamCount` as `readClientSettings.maxWorkerCount` as hint to the server for desired minimum streams. 

**Describe the solution you'd like**
I would like to set `PreferredMinStreamCount` as `readClientSettings.maxWorkerCount` as hint to the server for desired minimum streams. 

**Describe alternatives you've considered**
Since there is no option in sdk that allow user to configure this there are no other alternatives.

**Additional context**
https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1#createreadsessionrequest

**Comment by alvarowolfx** [comment]
@k-anshul I think the configuration that you want to tweak here is the `maxStreamCount` instead of `maxWorkerCount`, because that's what we send to the Storage Read API as [can be checked here](https://github.com/googleapis/google-cloud-go/blob/fb1a8ccfa81b8b36658207e333ee83666c87be75/bigquery/storage_client.go#L144). And the default value for it [is already 0](https://github.com/googleapis/google-cloud-go/blob/fb1a8ccfa81b8b36658207e333ee83666c87be75/bigquery/storage_client.go#L48), which will signal the backend to produce as many streams to generate some reasonable throughput. But in some scenario, like ordered queries, [our client](https://github.com/googleapis/google-cloud-go/blob/fb1a8ccfa81b8b36658207e333ee83666c87be75/bigquery/storage_client.go#L107) and the backend can produce only one stream, so ordering can be guaranteed.

In the light of that, can you give more details on your use case ? I'm assuming that you're using the Storage API through the `EnableStorageReadClient` method. Maybe what is happening on your case is that your queries are ordered, which will cause only one stream to be generated.

**Comment by k-anshul** [comment]
@alvarowolfx Thanks for your reply. 
I am running a `select * from table limit <num>` query on both public and private sources so ordering is not required in my case. Also I confirmed that `maxStreamCount` being set is zero. I also confirmed that I am never getting more than 1 stream  (on similar queries). 
I was referring to additionally setting [PreferredMinStreamCount](https://github.com/googleapis/google-cloud-go/blob/a9fff181e4ea8281ad907e7b2e0d90e70013a4de/bigquery/storage/apiv1/storagepb/storage.pb.go#L289) equal to `readClientSettings.maxWorkerCount` or some multiple to provide a hint to server to give more than 1 stream. I tested with setting this and could verify that server is returning more than 1 streams now. I can also raise a PR for this change.
Sample public datasets on which I ran query : 
```
SELECT * FROM `bigquery-public-data.covid19_open_data.compatibility_view` LIMIT 10000000
```
