### ISSUE TITLE
pubsub: TopicConfig.RetentionDuration cannot be set 31 days (30 days also didn't work)

### ISSUE THREAD

**Issue by kokizzu** [googleapis/google-cloud-go#8557]
**Client**

e.g. PubSub

**Environment**

any

**Go Environment**

$ go version
1.20.1
$ go env
irrelevant

**Code**

https://stackoverflow.com/questions/77091705/google-pub-sub-set-enable-message-retention-on-topic-programatically
e.g.
```go
const DefaultRetentionDuration = 31*24*time.Hour - time.Second
var DefaultTopicConfig = pubsub.TopicConfig{
	MessageStoragePolicy: pubsub.MessageStoragePolicy{
		AllowedPersistenceRegions: []string{"us-east4"},
	},
	RetentionDuration: DefaultRetentionDuration,
}

...

	_, err = pubSubClient.CreateTopicWithConfig(ctx, topicId, &DefaultTopicConfig)
	if err != nil {
		var apiError *apierror.APIError
		if errors.As(err, &apiError) {
			switch apiError.GRPCStatus().Code() {
			case codes.AlreadyExists: // topic already exists
				err = nil
			}
		}
	}
```

**Expected behavior**

no error

**Actual behavior**

failed to create topic: rpc error: code = InvalidArgument desc = message_retention_duration out of bounds

**Screenshots**

on UI it's ok to set 31 days:
![image](https://github.com/googleapis/google-cloud-go/assets/1061610/1fe5c978-85e4-44b6-ba08-11393f05a9d0)

**Additional context**

`cloud.google.com/go/pubsub v1.33.0`

**Comment by hongalex** [comment]
This is not reproducible for me. When I try to set a value that is actually out of bounds, I get the following error

```
failed to create topic: rpc error: code = InvalidArgument desc = The value for message retention duration is out of bounds. You passed 744h1s in the request, but the value must be between 10m and 744h.
        error details: name = DebugInfo detail = Invalid MessageRetentionDuration (requested=744h1s min=10m max=744h
```

Could you point to the specific line that is doing the logging? Also, are you connecting to the live service, or using an emulator?

**Comment by hongalex** [comment]
I think you might be using the emulator since your error message matches what I got from testing with the emulator:

`integration_test.go:1983: failed to create topic: rpc error: code = InvalidArgument desc = message_retention_duration out of bounds`

The increase of message retention was increased to 31 days earlier this year and the emulator hasn't been updated to reflect that. Please [file a ticket here](https://issuetracker.google.com/issues/new?component=187173&template=1162763) since this isn't an issue with the Go client library.

**Comment by hongalex** [comment]
Update for this, the emulator was updated to support topic message retention of 31 days in v0.8.8
