### ISSUE TITLE
cloud.google.com/go/iam/apiv1: IamPolicyClient.GetIamPolicy results in a `404` error

### ISSUE THREAD

**Issue by BadAsstronaut** [googleapis/google-cloud-go#8671]
**Client**

 iam

**Environment**

 MacBook Pro M1

**Go Environment**

$ go version

`1.19.6 darwin/arm64`

$ go env

```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.6/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user/Projects/gcp-service-account/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5x/yyf4ck4957z49vw7z8y50m8m0000gq/T/go-build2269310238=/tmp/go-build -gno-record-gcc-switches -fno-common"

```

**Code**

```go
package main

import (
	"context"
	"log"
	iam "cloud.google.com/go/iam/apiv1"
	"cloud.google.com/go/iam/apiv1/iampb"
)
func main() {
	ctx := context.Background()
	c, e := iam.NewIamPolicyClient(ctx)
	require.NoError(t, e)
	defer c.Close()
	req := &iampb.GetIamPolicyRequest{
		Resource: "project-a2c4", // project ID; works for other calls
	}

	res, err := c.GetIamPolicy(ctx, req)
	if err != nil {
		log.Fatalf("GetIamPolicy: %v", err)
	}

	log.Printf("res: %v", res)
}
```

**Expected behavior**

Either a successful policy result or an error indicating that the service encountered unexpected inputs. 
For example, a similar failing (different policy client) call would output:
```
                Error:          Received unexpected error:
                                rpc error: code = InvalidArgument desc = The name should be in the form "projects/{project_id}/serviceAccounts/{account}".
```

**Actual behavior**

`GetIamPolicy: rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "text/html; charset=UTF-8"`

**Comment by quartzmo** [comment]
@BadAsstronaut 

Thanks for reporting this. I'll try to reproduce it myself today.

**Comment by BadAsstronaut** [comment]
Thanks @quartzmo ; note that this result occurs with an empty string for `Resource` as well.

**Comment by quartzmo** [comment]
@BadAsstronaut I think the error code is correct. Typically in Google Cloud, in a GET request, when the resource name is incorrect or even if is correct but the caller doesn't have access to resource, the response will 404.

It could be that your `Resource` argument is incorrectly formatted. I tried to verify the expected format but because of the extremely general nature of this particular resource, it wasn't easy.

I looked at https://pkg.go.dev/cloud.google.com/go/iam/apiv1/iampb#GetIamPolicyRequest, which says:

> See the operation documentation for the appropriate value for this field.

So then I looked at https://cloud.google.com/iam/docs/reference/rpc/google.iam.v1#google.iam.v1.GetIamPolicyRequest, which says:

> See [Resource names](https://cloud.google.com/apis/design/resource_names) for the appropriate value for this field.

I followed that link to https://cloud.google.com/apis/design/resource_names, which is very general and does not provide an example for a project.

Looking further in the IAM docs, I found https://cloud.google.com/iam/docs/full-resource-names, which contains this example of a format for a resource manager project:

> `//cloudresourcemanager.googleapis.com/projects/PROJECT_ID`

**Comment by Carestab** [comment]
I am getting the same error despite indicating the resource field as above.

In my case I use Asset Inventory to bring certain projects which I then indicate in the resource field.

```
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	// "strings"

	asset "cloud.google.com/go/asset/apiv1"
	"cloud.google.com/go/asset/apiv1/assetpb"
	iam "cloud.google.com/go/iam/apiv1"
	"cloud.google.com/go/iam/apiv1/iampb"
	"google.golang.org/api/iterator"
)

func main() {
	scope := flag.String("scope", "organizations/ORG_ID", "Scope of the search.")
	query := flag.String("query", "", "Query statement.")
	flag.Parse()
	ctx := context.Background()
	client, err := asset.NewClient(ctx)

	if err != nil {
		log.Fatalf("asset.NewClient: %v", err)
	}
	defer client.Close()

	req := &assetpb.SearchAllResourcesRequest{
		Scope:      *scope,
		Query:      *query,
		AssetTypes: []string{"cloudresourcemanager.googleapis.com/Project"},
	}
	it := client.SearchAllResources(ctx, req)

	iamClient, err := iam.NewIamPolicyClient(ctx)

	if err != nil {
		log.Fatalf("iam.NewIamPolicyRESTClient: %v", err)
	}

	for {
		resource, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
		// fmt.Println(resource)
		// Gets the project's policy
		iamReq := &iampb.GetIamPolicyRequest{
			Resource: resource.GetName(),
			// Resource: fmt.Sprintf("//iam.googleapis.com/projects/%s/serviceAccounts/%s-compute@developer.gserviceaccount.com",resource.GetAdditionalAttributes().GetFields()["projectId"].GetStringValue(),strings.Split(resource.GetProject(),"/")[1]),
			Options: &iampb.GetPolicyOptions{
				RequestedPolicyVersion: 3,
			},
		}
		fmt.Println(iamReq.GetResource())
		iamPolicy, err := iamClient.GetIamPolicy(ctx, iamReq)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println(iamPolicy)
	}

}
```
To reproduce the error you only need to give value to ORG_ID

I'm using go version 1.22.7.

**Comment by quartzmo** [comment]
@Carestab The client libraries in this repo are generated from interface descriptions published by product teams. We are only able to assist with issues that pertain to the behavior of the libraries themselves. Because the issue you're experiencing is due to the behavior of the product, please visit the [support page](https://cloud.google.com/support) to reach product engineers. To see if this issue has already been reported, you can check the Cloud issue trackers at https://cloud.google.com/support/docs/issue-trackers.
