### ISSUE TITLE
generativelanguage: needs updating to v1beta3 

### ISSUE THREAD

**Issue by rcleveng** [googleapis/google-cloud-go#9051]
**Client**

e.g. [generativelanguage]

**Environment**

Mac OS (although not env specific)

**Additional context**

See https://developers.generativeai.google/api/rest/generativelanguage - v1beta3 is available.  This adds the batchEmbedText endpoint

**Comment by noahdietz** [comment]
@rcleveng if a new API version is available, its protos/API artifacts need to be published to googleapis. The team would've already done this for `v1beta2`. Since you are a googler, the (internal) documentation is [here](http://go/client-user-guide). Please follow up with the team to publish the version, and thus, the new clients. New bugs will be created automatically after publishing is done, which you can track. We can't really do anything from this repo so I will close this. Thanks for pointing it out though.

**Comment by rcleveng** [comment]
These are published already at https://github.com/googleapis/googleapis/tree/fce431c83ad15007ffbfe0b0b1c36b7d6af68ab8/google/ai/generativelanguage/v1beta3

**Comment by noahdietz** [comment]
> These are published already at https://github.com/googleapis/googleapis/tree/fce431c83ad15007ffbfe0b0b1c36b7d6af68ab8/google/ai/generativelanguage/v1beta3

Looks like they did not configure a publishing section for the `v1beta3` version of the service, as [described in the user guide](http://go/client-user-guide#3-request-client-libraries-in-your-service-config-yaml). As a result, client library automation did not open bugs requesting client libraries. They need to populate that in their service config (which they've already done for `v1beta2`) and publish that so our automation can trigger generation requests.
