### ISSUE TITLE
maps/places: no way to set required field mask header

### ISSUE THREAD

**Issue by nfiacco** [googleapis/google-cloud-go#9303]
There is no way to set the required FieldMask header for the Places API requests.

**Comment by quartzmo** [comment]
@nfiacco Can you please provide an end-to-end code example (including imports) that demonstrates the issue?

**Comment by nfiacco** [comment]
```
import (
	"context"
	"log"

	places "cloud.google.com/go/maps/places/apiv1"
	"cloud.google.com/go/maps/places/apiv1/placespb"
	"google.golang.org/genproto/googleapis/type/latlng"
)

func Demo() error {
	ctx := context.Background()

	c, err := places.NewClient(ctx)
	if err != nil {
		log.Fatal(err)
	}

	// How do you set the FieldMask? SearchNearbyRequest does not have a FieldMask field
	_, err = c.SearchNearby(ctx, &placespb.SearchNearbyRequest{
		LocationRestriction: &placespb.SearchNearbyRequest_LocationRestriction{
			Type: &placespb.SearchNearbyRequest_LocationRestriction_Circle{
				Circle: &placespb.Circle{
					Radius: 1000,
					Center: &latlng.LatLng{
						Latitude:  0,
						Longitude: 0,
					},
				},
			},
		},
	})

	if err != nil {
		log.Fatal(err)
	}

	return nil
}
```

**Comment by nfiacco** [comment]
Here's the error code if you need more information:

```
Nearby place request: rpc error: code = InvalidArgument desc = FieldMask is a required parameter.
See https://cloud.google.com/apis/docs/system-parameters on how to provide it.
As an example, you can set the header 'X-Goog-FieldMask' to value 'places.displayName', 'places.id'
to ask for the display name and the place id of a place.
You can also set the value to '*' in manual testing to get all the available response fields.
```

**Comment by nfiacco** [comment]
Any updates?

**Comment by quartzmo** [comment]
@nfiacco Typically, an RPC that accepts a FieldMask also starts with `Update`. (See AIP-134: "The RPC's name must begin with the word `Update`.") The code generator that produced this library will then ensure that the `Request` type has an `UpdateMask` field, as in [UpdateAccessPolicyRequest](https://github.com/googleapis/google-cloud-go/blob/accesscontextmanager/v1.8.5/accesscontextmanager/apiv1/accesscontextmanagerpb/access_context_manager.pb.go#L292). I'll see if I can find out what the backstory is with this particular RPC, and how we might be able to address this.

**Comment by quartzmo** [comment]
I believe you can set the required header using https://pkg.go.dev/github.com/googleapis/gax-go/v2/callctx#SetHeaders. See the example on the function docs.

**Comment by nfiacco** [comment]
I tried setting the header via `SetHeaders` and still received the same error message. It's possible I did something wrong, but is there a chance the header isn't being passed in this case?

**Comment by noahdietz** [comment]
@nfiacco can you please include the `SetHeaders` call you tried in your snippet (update above or include in a new comment)?

It is possible something isn't getting piped through properly. To check that let's [enable debug logs](https://github.com/googleapis/google-cloud-go/blob/main/debug.md) and see what is/isn't being sent. You could also try to make an interceptor to log the metadata in the outgoing context. I will be poking around myself, but since you have the API set up it is a tad faster to ask you to check (if you don't mind).

**Comment by noahdietz** [comment]
@nfiacco to your example i just added the following and it **did not** return an error:

```go
ctx = callctx.SetHeaders(ctx, "x-goog-fieldmask", "places.displayName")
```

**Comment by noahdietz** [comment]
Sending the header with the casing that the suggests produces `rpc error: code = Internal desc = header key "X-Goog-FieldMask" contains illegal characters not in [0-9a-z-_.]`

**Comment by noahdietz** [comment]
We have a lot to do to make this experience better for you @nfiacco . We will take some time to discuss our options, but ideally this a no-op for you and it "just works"

**Comment by nfiacco** [comment]
Thanks for the deep dive @noahdietz — for now I can just make the API calls directly so I'm not blocked. Just wanted to give the heads up!

**Comment by noahdietz** [comment]
@nfiacco thanks for filing this/bringing it to our attention. Since there is a solution to the issue, I will close this, but I am opening another bug or two to improve the experience that will reference this one, so keep an eye out for those. 

I found in the `Places API (New)` documentation where it [states FieldMask is required](https://developers.google.com/maps/documentation/places/web-service/nearby-search#fieldmask) in case you hadn't seen it (new to me!), and there are some examples (but not with the client libraries to be fair!).

Solution:
```go
ctx = callctx.SetHeaders(ctx, "x-goog-fieldmask", "*")
```
