### ISSUE TITLE
pubsub: possibility to reuse same subscriptions by pods after scaling down or crashing or rollout

### ISSUE THREAD

**Issue by acim** [googleapis/google-cloud-go#9596]
**Is your feature request related to a problem? Please describe.**
I want to make many to many pubsub topic and I figured out that for each pod I need a separate subscription. I create subscriptions with random names at the init of each pod. However, this may create multiple unused subscriptions which will be removed after minimum of 24 hours. This may happen on scale down or on new release or pod crash.

**Describe alternatives you've considered**
Is it possible to somehow create permanent subscriptions and reuse them? Of course, pods still wouldn't know which shall use which subscription since they have no order (I am using Deployment, not StatefulSet).
Or could you provide a method on subscription to find out how many subscribers there are? And also a method to delete subscription. This probably can be achieved by some kind of distributed locking but that requires quite some work as well.
Or maybe have an option on subscription like deliverToAll instead of delivering to one of the subscribers (load balancing).

**Comment by hongalex** [comment]
Before answering these questions, I want to clarify that the Go client library currently refers to "subscription" and "subscriber client" as the same thing. I notice that your answer also does the same. Officially, subscriptions are resources that are instantiated and saved in Pub/Sub. Subscribers clients are instantiated by our client libraries to pull messages from a subscription.

> Is it possible to somehow create permanent subscriptions and reuse them? 

Subscriptions are permanent, and exist on the Pub/Sub. Subscriber clients are ephemeral. We do not have plans to introduce named / permanent subscriber clients.

> Or could you provide a method on subscription to find out how many subscribers there are? 

I recommend filing a feature request on our [Pub/Sub issue tracker](https://issuetracker.google.com/issues/new?component=187173&template=1162763), since this isn't a Go client library specific request. 

> And also a method to delete subscription. This probably can be achieved by some kind of distributed locking but that requires quite some work as well.

Stopping the subscriber client should be done by cancelling the `sub.Receive` context. There is no way to refer to a specific subscriber client outside of that application, since they aren't named.

> Or maybe have an option on subscription like deliverToAll instead of delivering to one of the subscribers (load balancing).

Delivering the same copy of a message to multiple clients can be done by creating more subscriptions. This is the "one-to-many" pattern described [here](https://cloud.google.com/pubsub/docs/pubsub-basics#choose_a_publish_and_subscribe_pattern).

**Comment by hongalex** [comment]
Closing since per the last comment, there isn't anything that's specific to the Go client library currently. I recommend filling out an issue on the issue tracker for the features that pertain to Pub/Sub as a whole.
