### ISSUE TITLE
compute/instance-groups: allow the ability to get zone information from a regional request

### ISSUE THREAD

**Issue by kwould** [googleapis/google-cloud-go#9623]
**Is your feature request related to a problem? Please describe.**
There's no easy way to find out what zone a instance is in. This is easy to do with `gcloud` tool but it seems intentionally omitted with the sdk. 
For instance I can do:
```
gcloud compute instance-groups list-instances  <instance_group> --project=<project> --region=<region>
```
and the output I get shows me the zones each instance is in. The corresponding sdk call appears to be: https://github.com/googleapis/google-cloud-go/blob/main/compute/apiv1/instance_groups_client.go#L127 which gives me an `InstanceWithNamedPortsIterator` which does not have any zonal information.
 
**Describe the solution you'd like**
It would be nice if this endpoint returned a InstanceIterator, so that I could get the zone information for the instance.

**Describe alternatives you've considered**
The current workaround that I have to do is to query the individual zones in the distribution policy for the Instance group. Though this does work, It's not at all efficient.

**Comment by quartzmo** [comment]
Hi @kwould 
The Compute client is auto-generated from an interface description published by the product team. We are only able to assist with issues that pertain to the behaviors of this library. Because the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

You can also check the existing [Compute Engine issues](https://issuetracker.google.com/savedsearches/559755) and file an issue there if there is not one already. All cloud issue trackers can be found at https://cloud.google.com/support/docs/issue-trackers.
